{% set version = '1.3-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-colorspace
  version: {{ version|replace("-", "_") }}

source:
  fn: colorspace_1.3-2.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/colorspace_1.3-2.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/colorspace/colorspace_1.3-2.tar.gz  # [linux or win32]
  sha256: dd9fd2342b650456901d014e7ff6d2e201f8bec0b555be63b1a878d2e1513e34  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/colorspace_1.3-2.zip  # [win64]
  sha256: 8c8559ff85046b0586c6415bd391a0271214577e739d10be3481b2e1e71a9f16  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/colorspace_1.3-2.tgz  # [osx]
  sha256: 63412f59fd37485f2d36ec64dd909511d75164e47c5a3364d38c098a320db5b2  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: datasets, stats, utils, KernSmooth, MASS, kernlab, mvtnorm, vcd, dichromat, tcltk, shiny, shinyjs
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('colorspace')"           # [not win]
    - "\"%R%\" -e \"library('colorspace')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://hclwizard.org/
  license: BSD_3_clause + file LICENSE
  summary: Carries out mapping between assorted color spaces including RGB, HSV, HLS, CIEXYZ,
    CIELUV, HCL (polar CIELUV), CIELAB and polar CIELAB. Qualitative, sequential, and
    diverging color palettes based on HCL colors are provided along with an interactive
    palette picker (with either a Tcl/Tk or a shiny GUI).
  license_family: BSD

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: colorspace
# Version: 1.3-2
# Date: 2016-12-14
# Title: Color Space Manipulation
# Authors@R: c(person(given = "Ross", family = "Ihaka", role = "aut", email = "ihaka@stat.auckland.ac.nz"), person(given = "Paul", family = "Murrell", role = "aut", email = "paul@stat.auckland.ac.nz"), person(given = "Kurt", family = "Hornik", role = "aut", email = "Kurt.Hornik@R-project.org"), person(given = c("Jason", "C."), family = "Fisher", role = "aut", email = "jfisher@usgs.gov"), person(given = "Reto", family = "Stauffer", role = "aut", email = "Reto.Stauffer@uibk.ac.at"), person(given = "Achim", family = "Zeileis", role = c("aut", "cre"), email = "Achim.Zeileis@R-project.org"))
# Description: Carries out mapping between assorted color spaces including RGB, HSV, HLS, CIEXYZ, CIELUV, HCL (polar CIELUV), CIELAB and polar CIELAB. Qualitative, sequential, and diverging color palettes based on HCL colors are provided along with an interactive palette picker (with either a Tcl/Tk or a shiny GUI).
# Depends: R (>= 2.13.0), methods
# Imports: graphics, grDevices
# Suggests: datasets, stats, utils, KernSmooth, MASS, kernlab, mvtnorm, vcd, dichromat, tcltk, shiny, shinyjs
# License: BSD_3_clause + file LICENSE
# URL: https://hclwizard.org/
# LazyData: yes
# NeedsCompilation: yes
# Packaged: 2016-12-14 22:11:46 UTC; zeileis
# Author: Ross Ihaka [aut], Paul Murrell [aut], Kurt Hornik [aut], Jason C. Fisher [aut], Reto Stauffer [aut], Achim Zeileis [aut, cre]
# Maintainer: Achim Zeileis <Achim.Zeileis@R-project.org>
# Repository: CRAN
# Date/Publication: 2016-12-14 23:28:25

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
