{% set version = '0.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tkrgl
  version: {{ version|replace("-", "_") }}

source:
  fn: tkrgl_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/tkrgl_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/tkrgl/tkrgl_{{ version }}.tar.gz  # [linux or win32]
  sha256: 24fcf76d927decb8c09addcead6393904dda0a3a7ad63f977776b88ba18ab2b0  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/tkrgl_0.8.zip  # [win64]
  sha256: 659e1d2f13c05e3626c13acde439c50ec688b2ce7284b8174f35428c283dd324  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/tkrgl_0.8.tgz  # [osx]
  sha256: 0ce5dac603024d6ba3060a3993fbf6746b9119eabae62f6232cfda95bb20af1d  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - mro-base
    - r-rgl >=0.66

  run:
    - mro-base
    - r-rgl >=0.66

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tkrgl')"           # [not win]
    - "\"%R%\" -e \"library('tkrgl')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.stats.uwo.ca/faculty/murdoch
  license: GPL
  summary: 'Provides ''TK'' widget tools for the ''rgl'' package. '

  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tkrgl
# Title: 'TK' Widget Tools for 'rgl'
# Version: 0.8
# Author: Duncan Murdoch/Ming Chen
# Description: Provides 'TK' widget tools for the 'rgl' package.
# Maintainer: Duncan Murdoch <murdoch@stats.uwo.ca>
# License: GPL
# Depends: R (>= 2.0.0)
# Imports: rgl (>= 0.66), tcltk
# SystemRequirements: rgl packages for rendering
# URL: http://www.stats.uwo.ca/faculty/murdoch
# BugReports: https://r-forge.r-project.org/projects/rgl/
# NeedsCompilation: no
# Packaged: 2018-05-16 11:27:21 UTC; murdoch
# Repository: CRAN
# Date/Publication: 2018-05-16 12:31:45 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
