{% set version = '0.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tkrgl
  version: {{ version|replace("-", "_") }}

source:
  fn: tkrgl_0.7.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/tkrgl_0.7.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/tkrgl/tkrgl_0.7.tar.gz  # [linux or win32]
  sha256: 455f2f9c15e8067afe70d488611c4dd8c59a878e39ba51f20f36e31fcd2df8ce  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/tkrgl_0.7.zip  # [win64]
  sha256: 4b7dbb62d36ebcd4d0ce6f7bcefb5f1fa33d549906b46136bfd044786619953f  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/tkrgl_0.7.tgz  # [osx]
  sha256: 86087f6441e8e0094c6901cd3e65edbe5a4310e8b9ee7eaa91f955aa8071d45f  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:

  host:
    - mro-base
    - r-rgl >=0.66

  run:
    - mro-base
    - r-rgl >=0.66

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tkrgl')"           # [not win]
    - "\"%R%\" -e \"library('tkrgl')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.stats.uwo.ca/faculty/murdoch
  license: GPL
  summary: 'TK widget tools for rgl package '

  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tkrgl
# Title: TK widget tools for rgl package
# Version: 0.7
# Author: Duncan Murdoch/Ming Chen
# Description: TK widget tools for rgl package
# Maintainer: Duncan Murdoch <murdoch@stats.uwo.ca>
# License: GPL
# Depends: R (>= 2.0.0), tcltk, rgl (>= 0.66)
# SystemRequirements: rgl packages for rendering
# URL: http://www.stats.uwo.ca/faculty/murdoch
# BugReports: https://r-forge.r-project.org/projects/rgl/
# Repository: CRAN
# Repository/R-Forge/Project: rgl
# Repository/R-Forge/Revision: 831
# Date/Publication: 2011-11-27 09:14:21
# Packaged: 2011-11-25 22:38:01 UTC; rforge
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
