{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-debugme
  version: {{ version|replace("-", "_") }}

source:
  fn: debugme_1.1.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/debugme_1.1.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/debugme/debugme_1.1.0.tar.gz  # [linux or win32]
  sha256: 4dae0e2450d6689a6eab560e36f8a7c63853abbab64994028220b8fd4b793ab1  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/debugme_1.1.0.zip  # [win64]
  sha256: 56eeb7b723ad0d542d4250764abc36a567ba3a7e143e5ec058beed9f4226b370  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/debugme_1.1.0.tgz  # [osx]
  sha256: 659b6bcc38746b1495e1eebb4291cf1b893de8e5827dfdc1a001d90b4c3263af  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, mockery, R6, testthat, withr
requirements:
  build:

  host:
    - mro-base
    - r-crayon

  run:
    - mro-base
    - r-crayon

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('debugme')"           # [not win]
    - "\"%R%\" -e \"library('debugme')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/debugme#readme
  license: MIT + file LICENSE
  summary: Specify debug messages as special string constants, and control debugging of packages
    via environment variables.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: debugme
# Title: Debug R Packages
# Version: 1.1.0
# Author: Gabor Csardi
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Description: Specify debug messages as special string constants, and control debugging of packages via environment variables.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-lib/debugme#readme
# BugReports: https://github.com/r-lib/debugme/issues
# RoxygenNote: 6.0.1
# Imports: crayon, grDevices
# Suggests: covr, mockery, R6, testthat, withr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2017-10-22 09:14:23 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2017-10-22 14:18:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
