{% set version = '1.0-0.0' %}  # [linux or win32]
{% set version = '1.0-0.0' %}  # [win64]
{% set version = '1.0-0.0' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-perm
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/perm_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/perm/perm_{{ version }}.tar.gz  # [linux or win32]
  sha256: 53c6ee598d5b7b04388915dddc5adf1f8f313b73c3bceb3708db7a632857e500  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/perm_1.0-0.0.zip  # [win64]
  sha256: a2dc993ecda1a9efc542897cd8f86ab1ffae8e082a3455a9cf93b64f72c42f13  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/perm_1.0-0.0.tgz  # [osx]
  sha256: a73d7a5b53aff9609eeff64d40e2d832a5bd297f48ff4e3ee31a05b18e6f1f5c  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: coin
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('perm')"           # [not win]
    - "\"%R%\" -e \"library('perm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=perm
  license: GPL
  summary: Perform Exact or Asymptotic permutation tests
  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: perm
# Type: Package
# Title: Exact or Asymptotic permutation tests
# Version: 1.0-0.0
# Date: 2010-07-29
# Author: Michael Fay
# Maintainer: Michael Fay <mfay@niaid.nih.gov>
# Depends: R (>= 2.2.1), stats
# Suggests: coin
# Description: Perform Exact or Asymptotic permutation tests
# License: GPL
# Packaged: 2010-07-29 15:28:08 UTC; faym
# Repository: CRAN
# Date/Publication: 2010-07-29 15:46:08
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
