{% set version = '1.2-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-formula
  version: {{ version|replace("-", "_") }}

source:
  fn: Formula_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Formula_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/Formula/Formula_{{ version }}.tar.gz  # [linux or win32]
  sha256: 1411349b20bd09611a9fd0ee6d15f780c758ad2b0e490e908facb49433823872  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/Formula_1.2-3.zip  # [win64]
  sha256: 3a21e834c6d0f3b8392957a43a9b6ced22ca6b1b36177b252da1f48255b4c1c0  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/Formula_1.2-3.tgz  # [osx]
  sha256: 48ef35fc7e5134d7dc36604176718e2ce6bcc2ff8ca7ad76223443dc4ec4bb0e  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('Formula')"           # [not win]
    - "\"%R%\" -e \"library('Formula')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=Formula
  license: GPL-2 | GPL-3
  summary: Infrastructure for extended formulas with multiple parts on the right-hand side and/or
    multiple responses on the left-hand side (see <DOI:10.18637/jss.v034.i01>).
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: Formula
# Version: 1.2-3
# Date: 2018-05-02
# Title: Extended Model Formulas
# Description: Infrastructure for extended formulas with multiple parts on the right-hand side and/or multiple responses on the left-hand side (see <DOI:10.18637/jss.v034.i01>).
# Authors@R: c(person(given = "Achim", family = "Zeileis", role = c("aut", "cre"), email = "Achim.Zeileis@R-project.org", comment = c(ORCID = "0000-0003-0918-3766")), person(given = "Yves", family = "Croissant", role = "aut", email = "Yves.Croissant@univ-reunion.fr"))
# Depends: R (>= 2.0.0), stats
# License: GPL-2 | GPL-3
# NeedsCompilation: no
# Packaged: 2018-05-02 23:06:48 UTC; zeileis
# Author: Achim Zeileis [aut, cre] (<https://orcid.org/0000-0003-0918-3766>), Yves Croissant [aut]
# Maintainer: Achim Zeileis <Achim.Zeileis@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-05-03 07:53:28 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
