{% set version = '0.8-69' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-foreign
  version: {{ version|replace("-", "_") }}

source:
  fn: foreign_0.8-69.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/foreign_0.8-69.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/foreign/foreign_0.8-69.tar.gz  # [linux or win32]
  sha256: 13689f5ec1ab09e8973be81c7f1799b7de4313176072887a9fa0b5825aed3468  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/foreign_0.8-69.zip  # [win64]
  sha256: aa2e423876bf3fab14d4d7713965e23a9ed545c665015a56a4d95aea415bd96c  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/foreign_0.8-69.tgz  # [osx]
  sha256: fa4dbaefc7265c767c021dcb72953d1be097b94a1bb9912ed1b7f65cc60b973a  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('foreign')"           # [not win]
    - "\"%R%\" -e \"library('foreign')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=foreign
  license: GPL (>= 2)
  summary: Reading and writing data stored by some versions of 'Epi Info', 'Minitab', 'S', 'SAS',
    'SPSS', 'Stata', 'Systat', 'Weka', and for reading and writing some 'dBase' files.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: foreign
# Priority: recommended
# Version: 0.8-69
# Date: 2017-06-21
# Title: Read Data Stored by 'Minitab', 'S', 'SAS', 'SPSS', 'Stata', 'Systat', 'Weka', 'dBase', ...
# Depends: R (>= 3.0.0)
# Imports: methods, utils, stats
# Authors@R: c( person("R Core Team", email = "R-core@R-project.org", role = c("aut", "cph", "cre")), person("Roger", "Bivand", role = c("ctb", "cph")), person(c("Vincent", "J."), "Carey", role = c("ctb", "cph")), person("Saikat", "DebRoy", role = c("ctb", "cph")), person("Stephen", "Eglen", role = c("ctb", "cph")), person("Rajarshi", "Guha", role = c("ctb", "cph")), person("Swetlana", "Herbrandt", role = "ctb"), person("Nicholas", "Lewin-Koh", role = c("ctb", "cph")), person("Mark", "Myatt", role = c("ctb", "cph")), person("Ben", "Pfaff", role = "ctb"), person("Brian", "Quistorff", role = "ctb"), person("Frank", "Warmerdam", role = c("ctb", "cph")), person("Stephen", "Weigand", role = c("ctb", "cph")), person("Free Software Foundation, Inc.", role = "cph"))
# Copyright: see file COPYRIGHTS
# Description: Reading and writing data stored by some versions of 'Epi Info', 'Minitab', 'S', 'SAS', 'SPSS', 'Stata', 'Systat', 'Weka', and for reading and writing some 'dBase' files.
# ByteCompile: yes
# Biarch: yes
# License: GPL (>= 2)
# BugReports: https://bugs.r-project.org
# NeedsCompilation: yes
# Packaged: 2017-06-21 15:59:59 UTC; ligges
# Author: R Core Team [aut, cph, cre], Roger Bivand [ctb, cph], Vincent J. Carey [ctb, cph], Saikat DebRoy [ctb, cph], Stephen Eglen [ctb, cph], Rajarshi Guha [ctb, cph], Swetlana Herbrandt [ctb], Nicholas Lewin-Koh [ctb, cph], Mark Myatt [ctb, cph], Ben Pfaff [ctb], Brian Quistorff [ctb], Frank Warmerdam [ctb, cph], Stephen Weigand [ctb, cph], Free Software Foundation, Inc. [cph]
# Maintainer: R Core Team <R-core@R-project.org>
# Repository: CRAN
# Date/Publication: 2017-06-21 18:03:34 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
