{% set version = '7.3-14' %}  # [linux or win32]
{% set version = '7.3-14' %}  # [win64]
{% set version = '7.3-14' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-class
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/class_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/class/class_{{ version }}.tar.gz  # [linux or win32]
  sha256: 18b876dbc18bebe6a00890eab7d04ef72b903ba0049d5ce50731406a82426b9c  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/class_7.3-14.zip  # [win64]
  sha256: 7d12ff05008140866258fa623bb0aeb3308b5e81153e124025fb7d0ba7fb3cb2  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/macosx/el-capitan/contrib/3.5/class_7.3-14.tgz  # [osx]
  sha256: d5da03807145bd139991174de709179a1b6c0270339f0cc72f5cfa23158358df  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]
    - {{posix}}sed               # [win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-mass

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-mass

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('class')"           # [not win]
    - "\"%R%\" -e \"library('class')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.stats.ox.ac.uk/pub/MASS4/
  license: GPL-2 | GPL-3
  summary: Various functions for classification, including k-nearest neighbour, Learning Vector
    Quantization and Self-Organizing Maps.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: class
# Priority: recommended
# Version: 7.3-14
# Date: 2015-08-29
# Depends: R (>= 3.0.0), stats, utils
# Imports: MASS
# Authors@R: c(person("Brian", "Ripley", role = c("aut", "cre", "cph"), email = "ripley@stats.ox.ac.uk"), person("William", "Venables", role = "cph"))
# Description: Various functions for classification, including k-nearest neighbour, Learning Vector Quantization and Self-Organizing Maps.
# Title: Functions for Classification
# ByteCompile: yes
# License: GPL-2 | GPL-3
# URL: http://www.stats.ox.ac.uk/pub/MASS4/
# NeedsCompilation: yes
# Packaged: 2015-08-28 15:25:36 UTC; ripley
# Author: Brian Ripley [aut, cre, cph], William Venables [cph]
# Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
# Repository: CRAN
# Date/Publication: 2015-08-30 08:59:38

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
