{% set version = '0.2.20' %}  # [linux or win32]
{% set version = '0.2.20' %}  # [win64]
{% set version = '0.2.20' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rjson
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/rjson_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/rjson/rjson_{{ version }}.tar.gz  # [linux or win32]
  sha256: 3a287c1e5ee7c333ed8385913c0a307daf99335fbdf803e9dcca6e3d5adb3f6c  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/rjson_0.2.20.zip  # [win64]
  sha256: 79f2fba30138d92caf9fad7b5593ea263e88e3341010b24ff14e1f5e8c8ef711  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/rjson_0.2.20.tgz  # [osx]
  sha256: bc733905b4e029d7d4aa9bbdcbe99719c1054cf4c85c219f083233cf9a6a91ef  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux or osx]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rjson')"           # [not win]
    - "\"%R%\" -e \"library('rjson')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=rjson
  license: GPL-2
  summary: Converts R object into JSON objects and vice-versa.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rjson
# Version: 0.2.20
# Date: 2018-05-18
# Title: JSON for R
# Author: Alex Couture-Beil <rjson_pkg@mofo.ca>
# Maintainer: Alex Couture-Beil <rjson_pkg@mofo.ca>
# Depends: R (>= 3.1.0)
# Description: Converts R object into JSON objects and vice-versa.
# License: GPL-2
# Repository: CRAN
# Date/Publication: 2018-06-08 17:23:00 UTC
# Packaged: 2018-06-07 22:29:50 UTC; root
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
