{% set version = '0.2.15' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rjson
  version: {{ version|replace("-", "_") }}

source:
  fn: rjson_0.2.15.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/rjson_0.2.15.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/rjson/rjson_0.2.15.tar.gz  # [linux or win32]
  sha256: 77d00d8f6a1c936329b46f3b8b0be79a165f8c5f1989497f942ecc53dcf6f2ef  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/rjson_0.2.15.zip  # [win64]
  sha256: 03286038bb91e207f52fb0d3ca73b24620b48ee046f28c797ed089e61ffdc1dc  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/rjson_0.2.15.tgz  # [osx]
  sha256: e4998760cd5423684f24b13a995a656909e67aeebdaed79bd8ae017187b27f6a  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rjson')"           # [not win]
    - "\"%R%\" -e \"library('rjson')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=rjson
  license: GPL-2
  summary: Converts R object into JSON objects and vice-versa
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rjson
# Version: 0.2.15
# Date: 2014-11-02
# Title: JSON for R
# Author: Alex Couture-Beil <rjson_pkg@mofo.ca>
# Maintainer: Alex Couture-Beil <rjson_pkg@mofo.ca>
# Depends: R (>= 3.1.0)
# Description: Converts R object into JSON objects and vice-versa
# License: GPL-2
# Repository: CRAN
# Date/Publication: 2014-11-03 00:35:00
# Packaged: 2014-11-02 21:27:41 UTC; alex
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
