{% set version = '0.15.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgexf
  version: {{ version|replace("-", "_") }}

source:
  fn: rgexf_0.15.3.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/rgexf_0.15.3.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/rgexf/rgexf_0.15.3.tar.gz  # [linux or win32]
  sha256: 2e8a7978d1fb977318e6310ba65b70a9c8890185c819a7951ac23425c6dc8147  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/rgexf_0.15.3.zip  # [win64]
  sha256: d9743c3fe4836889cf309e7aa5e813f6c385d0b931ceafa3382f2fff1f43af57  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/rgexf_0.15.3.tgz  # [osx]
  sha256: 25e160fe9fb9326ec0943b4580e019e94bb31cbb457d133f5d0edbffad17832a  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-rook
    - r-xml
    - r-igraph

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-rook
    - r-xml
    - r-igraph

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rgexf')"           # [not win]
    - "\"%R%\" -e \"library('rgexf')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://bitbucket.org/gvegayon/rgexf, http://www.ggvega.com
  license: GPL (>= 3)
  summary: Create, read and write GEXF (Graph Exchange XML Format) graph files (used in Gephi
    and others). Using the XML package, it allows the user to easily build/read graph
    files including attributes, GEXF viz attributes (such as color, size, and position),
    network dynamics (for both edges and nodes) and edge weighting. Users can build/handle
    graphs element-by-element or massively through data-frames, visualize the graph
    on a web browser through "sigmajs" (a javascript library) and interact with the
    igraph package.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rgexf
# Type: Package
# Encoding: UTF-8
# Title: Build, Import and Export GEXF Graph Files
# Version: 0.15.3
# Date: 2015-03-24
# Author: George Vega Yon <gvegayon@caltech.edu> [aut], Jorge FAbrega Lacoa <jorge.fabrega@uai.cl> [ctb], Joshua B. Kunst <jbkunst@gmail.com> [ctb]
# Maintainer: George Vega Yon <gvegayon@caltech.edu>
# Description: Create, read and write GEXF (Graph Exchange XML Format) graph files (used in Gephi and others). Using the XML package, it allows the user to easily build/read graph files including attributes, GEXF viz attributes (such as color, size, and position), network dynamics (for both edges and nodes) and edge weighting. Users can build/handle graphs element-by-element or massively through data-frames, visualize the graph on a web browser through "sigmajs" (a javascript library) and interact with the igraph package.
# URL: http://bitbucket.org/gvegayon/rgexf, http://www.ggvega.com
# Depends: XML, Rook, igraph
# License: GPL (>= 3)
# LazyLoad: yes
# Packaged: 2015-03-24 15:40:34 UTC; george
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2015-03-24 18:27:03

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
