{% set version = '4.1-11' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpart
  version: {{ version|replace("-", "_") }}

source:
  fn: rpart_4.1-11.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/rpart_4.1-11.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/rpart/rpart_4.1-11.tar.gz  # [linux or win32]
  sha256: 38ab80959f59bcdd2c4c72860e8dd0deab0307668cbbf24f96014d7a2496ad98  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/rpart_4.1-11.zip  # [win64]
  sha256: fda0eb3ba14e69bbe1be37da706acdeb774a4c50ebdda0f01db890331a6aaacd  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/rpart_4.1-11.tgz  # [osx]
  sha256: 40a18165863afbe82c6e83ef792662f79a48ef7493df5c340384f8ae27c8500f  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: survival
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rpart')"           # [not win]
    - "\"%R%\" -e \"library('rpart')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=rpart
  license: GPL-2 | GPL-3
  summary: Recursive partitioning for classification,  regression and survival trees.  An implementation
    of most of the  functionality of the 1984 book by Breiman, Friedman, Olshen and
    Stone.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rpart
# Priority: recommended
# Version: 4.1-11
# Date: 2017-03-12
# Authors@R: c(person("Terry", "Therneau", role = "aut", email = "therneau@mayo.edu"), person("Beth", "Atkinson", role = "aut",	 email = "atkinson@mayo.edu"), person("Brian", "Ripley", role = c("aut", "trl", "cre"), email = "ripley@stats.ox.ac.uk", comment = "author of initial R port"))
# Description: Recursive partitioning for classification,  regression and survival trees.  An implementation of most of the  functionality of the 1984 book by Breiman, Friedman, Olshen and Stone.
# Title: Recursive Partitioning and Regression Trees
# Depends: R (>= 2.15.0), graphics, stats, grDevices
# Suggests: survival
# License: GPL-2 | GPL-3
# LazyData: yes
# ByteCompile: yes
# Note: Maintainers are not available to give advice on using a package they did not author.
# NeedsCompilation: yes
# Packaged: 2017-03-12 21:36:08 UTC; ripley
# Author: Terry Therneau [aut], Beth Atkinson [aut], Brian Ripley [aut, trl, cre] (author of initial R port)
# Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
# Repository: CRAN
# Date/Publication: 2017-04-21 13:33:37 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
