{% set version = '1.10.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proc
  version: {{ version|replace("-", "_") }}

source:
  fn: pROC_1.10.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/pROC_1.10.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/pROC/pROC_1.10.0.tar.gz  # [linux or win32]
  sha256: 4039fb71e531b1fcff319fc656657813465bf818476535d02a16f7271c44a066  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/pROC_1.10.0.zip  # [win64]
  sha256: 8ced817e31944b56674075a519c58463c8d4f7d2b6eba0644fd66fc47761b069  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/pROC_1.10.0.tgz  # [osx]
  sha256: 66382e26490c9bc0f1f84fe22ca5416d5e51037b93c65183419603be4e4cf0a7  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: microbenchmark, tcltk, MASS, logcondens, doParallel, testthat
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-rcpp >=0.11.1
    - r-ggplot2
    - r-plyr

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-rcpp >=0.11.1
    - r-ggplot2
    - r-plyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pROC')"           # [not win]
    - "\"%R%\" -e \"library('pROC')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://expasy.org/tools/pROC/
  license: GPL (>= 3)
  summary: Tools for visualizing, smoothing and comparing receiver operating characteristic (ROC
    curves). (Partial) area under the curve (AUC) can be compared with statistical tests
    based on U-statistics or bootstrap. Confidence intervals can be computed for (p)AUC
    or ROC curves.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: pROC
# Type: Package
# Title: Display and Analyze ROC Curves
# Version: 1.10.0
# Date: 2017-06-10
# Encoding: UTF-8
# Depends: R (>= 2.14)
# Imports: plyr, utils, methods, Rcpp (>= 0.11.1), ggplot2,
# Suggests: microbenchmark, tcltk, MASS, logcondens, doParallel, testthat
# LinkingTo: Rcpp
# Authors@R: c(person("Xavier", "Robin", role = c("cre", "aut"),  email = "robin@lindinglab.org"), person("Natacha", "Turck", role = "aut"), person("Alexandre", "Hainard", role = "aut"), person("Natalia", "Tiberti", role = "aut"), person("Frederique", "Lisacek", role = "aut"), person("Jean-Charles", "Sanchez", role = "aut"), person("Markus", "Muller", role = "aut"), person("Stefan", "Siegert", role = "ctb",  comment = "Fast DeLong code",  email = "stefan_siegert@gmx.de"))
# Description: Tools for visualizing, smoothing and comparing receiver operating characteristic (ROC curves). (Partial) area under the curve (AUC) can be compared with statistical tests based on U-statistics or bootstrap. Confidence intervals can be computed for (p)AUC or ROC curves.
# License: GPL (>= 3)
# URL: http://expasy.org/tools/pROC/
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2017-06-10 14:21:52 UTC; xavier
# Author: Xavier Robin [cre, aut], Natacha Turck [aut], Alexandre Hainard [aut], Natalia Tiberti [aut], Frederique Lisacek [aut], Jean-Charles Sanchez [aut], Markus Muller [aut], Stefan Siegert [ctb] (Fast DeLong code)
# Maintainer: Xavier Robin <robin@lindinglab.org>
# Repository: CRAN
# Date/Publication: 2017-06-10 21:17:21 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
