{% set version = '0.3.1' %}  # [linux or win32]
{% set version = '0.3.1' %}  # [win64]
{% set version = '0.3.1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rappdirs
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/rappdirs_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/rappdirs/rappdirs_{{ version }}.tar.gz  # [linux or win32]
  sha256: 2fd891ec16d28862f65bb57e4a78f77a597930abb59380e757afd8b6c6d3264a  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/rappdirs_0.3.1.zip  # [win64]
  sha256: 3221d76cb54e8577370c1ced7290a6582990806639ba299453403c8bcf19e397  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/rappdirs_0.3.1.tgz  # [osx]
  sha256: 7377762ae006cad0e6162e6db4cb417d0e8dfcb0bea612c4eaa443190361167c  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, roxygen2
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rappdirs')"           # [not win]
    - "\"%R%\" -e \"library('rappdirs')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/rappdirs https://github.com/ActiveState/appdirs
  license: MIT + file LICENSE
  summary: An easy way to determine which directories on the users computer you should use to
    save data, caches and logs. A port of Python's 'Appdirs' (\url{https://github.com/ActiveState/appdirs})
    to R.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rappdirs
# Type: Package
# Title: Application Directories: Determine Where to Save Data, Caches, and Logs
# Version: 0.3.1
# Authors@R: c( person("Hadley", "Wickham", email = "hadley@rstudio.com", role = c("trl", "cre", "cph")), person("RStudio", role = "cph"), person("Sridhar", "Ratnakumar", role = "aut"), person("Trent", "Mick", role = "aut"), person("ActiveState", role = "cph", comment = "R/appdir.r, R/cache.r, R/data.r, R/log.r translated from appdirs"), person("Eddy", "Petrisor", role = "ctb"), person("Trevor", "Davis", role = c("trl", "aut")), person("Gabor", "Csardi", role = "ctb"), person("Gregory", "Jefferis", role = "ctb") )
# Depends: R (>= 2.14), methods
# Suggests: testthat, roxygen2
# Description: An easy way to determine which directories on the users computer you should use to save data, caches and logs. A port of Python's 'Appdirs' (\url{https://github.com/ActiveState/appdirs}) to R.
# BugReports: https://github.com/hadley/rappdirs/issues
# URL: https://github.com/hadley/rappdirs https://github.com/ActiveState/appdirs
# License: MIT + file LICENSE
# Copyright: Original python appdirs module copyright (c) 2010 ActiveState Software Inc. R port copyright Hadley Wickham, RStudio. See file LICENSE for details.
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2016-03-28 19:04:15 UTC; hadley
# Author: Hadley Wickham [trl, cre, cph], RStudio [cph], Sridhar Ratnakumar [aut], Trent Mick [aut], ActiveState [cph] (R/appdir.r, R/cache.r, R/data.r, R/log.r translated from appdirs), Eddy Petrisor [ctb], Trevor Davis [trl, aut], Gabor Csardi [ctb], Gregory Jefferis [ctb]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2016-03-28 23:10:10

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
