{% set version = '1.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mongolite
  version: {{ version|replace("-", "_") }}

source:
  fn: mongolite_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/mongolite_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/mongolite/mongolite_{{ version }}.tar.gz  # [linux or win32]
  sha256: 5ef2e4f006ca57db030257f66782c79aa4f52aacf079d576a7e4b5194cf1191b  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/mongolite_1.5.zip  # [win64]
  sha256: d59b1dfadc0a8178e471b9b594fc6feb894cc7f28180841155f9c1ad8dccec90  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/mongolite_1.5.tgz  # [osx]
  sha256: 33311a9ac6c48ef8f41b47138376e061d74bc5a8883bf82404638c329ce47979  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: spelling
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}sed               # [win32]
    - {{posix}}grep              # [win32]
    - {{posix}}autoconf          # [linux or win32]
    - {{posix}}automake-wrapper  # [win32]
    - {{posix}}automake          # [win32]
    - {{posix}}pkg-config
    - {{posix}}make              # [linux or win32]

  host:
    - mro-base
    - r-jsonlite >=1.4
    - r-openssl >=0.9.4
    - {{native}}openssl
    - {{native}}cyrus-sasl       # [linux]
    - {{native}}zlib 1.2.8       # [win32]
    - {{native}}zlib             # [linux]

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-jsonlite >=1.4
    - r-openssl >=0.9.4
    - {{native}}openssl
    - {{native}}cyrus-sasl       # [linux]
    - {{native}}zlib 1.2.8       # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mongolite')"           # [not win]
    - "\"%R%\" -e \"library('mongolite')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/jeroen/mongolite/ (devel) https://jeroen.github.io/mongolite/ (user
    manual) http://mongoc.org/ (upstream)
  license: Apache License 2.0
  summary: 'High-performance ''MongoDB'' client based on ''libmongoc'' and ''jsonlite''. Includes
    support for aggregation, indexing, map-reduce, streaming, encryption, enterprise
    authentication. The online user manual provides an overview of the  available methods
    in the package: <https://jeroen.github.io/mongolite/>.'

  license_family: APACHE

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mongolite
# Type: Package
# Title: Fast and Simple 'MongoDB' Client for R
# Description: High-performance 'MongoDB' client based on 'libmongoc' and 'jsonlite'. Includes support for aggregation, indexing, map-reduce, streaming, encryption, enterprise authentication. The online user manual provides an overview of the  available methods in the package: <https://jeroen.github.io/mongolite/>.
# Version: 1.5
# Authors@R: c( person("Jeroen", "Ooms", ,"jeroen@berkeley.edu", role = c("aut", "cre")), person("MongoDB, Inc", role = "cph", comment = "Bundled mongo-c-driver, see AUTHORS file") )
# Imports: jsonlite (>= 1.4), openssl (>= 0.9.4)
# License: Apache License 2.0
# URL: https://github.com/jeroen/mongolite/ (devel) https://jeroen.github.io/mongolite/ (user manual) http://mongoc.org/ (upstream)
# BugReports: https://github.com/jeroen/mongolite/issues
# SystemRequirements: OpenSSL, Cyrus SASL (aka libsasl2)
# RoxygenNote: 6.0.1.9000
# Suggests: spelling
# Language: en-GB
# NeedsCompilation: yes
# Packaged: 2018-01-02 10:51:01 UTC; jeroen
# Author: Jeroen Ooms [aut, cre], MongoDB, Inc [cph] (Bundled mongo-c-driver, see AUTHORS file)
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-01-03 10:34:59 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
