{% set version = '1.6' %}  # [linux or win32 or osx]
{% set version = '1.6' %}  # [win64]
{% set version = '1.6' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mongolite
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/mongolite_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/mongolite/mongolite_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 06757ef06a5b98eadcba097a3c98e0998a091f431fb8ba672ceddce2961e5571  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/mongolite_1.6.zip  # [win64]
  sha256: c9919901bfe145d7567f476c1221f51b727d86d02b39cd06804663947dc5a1e9  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/mongolite_1.6.tgz  # [osx and false]
  sha256: a1158354ed92f0dcbe9213507f333a1e6c3b31513139fef212b4bfd317137dc4  # [osx and false]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib

# Suggests: spelling, nycflights13, ggplot2
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-jsonlite >=1.4
    - r-mime
    - r-openssl >=0.9.4
    - {{native}}openssl          # [linux or win32 or osx]
    - {{native}}cyrus-sasl	 # [linux or osx]
    - {{native}}zlib 1.2.8	 # [win32]
    - {{native}}zlib             # [linux or osx]

  run:
    - mro-base
    - r-jsonlite >=1.4
    - r-mime
    - r-openssl >=0.9.4

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mongolite')"           # [not win]
    - "\"%R%\" -e \"library('mongolite')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/jeroen/mongolite/ (devel) https://jeroen.github.io/mongolite/ (user
    manual) http://mongoc.org/ (upstream)
  license: Apache License 2.0
  summary: 'High-performance ''MongoDB'' client based on ''libmongoc'' and ''jsonlite''. Includes
    support for aggregation, indexing, map-reduce, streaming, encryption, enterprise
    authentication. The online user manual provides an overview of the  available methods
    in the package: <https://jeroen.github.io/mongolite/>.'

  license_family: APACHE

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mongolite
# Type: Package
# Title: Fast and Simple 'MongoDB' Client for R
# Description: High-performance 'MongoDB' client based on 'libmongoc' and 'jsonlite'. Includes support for aggregation, indexing, map-reduce, streaming, encryption, enterprise authentication. The online user manual provides an overview of the  available methods in the package: <https://jeroen.github.io/mongolite/>.
# Version: 1.6
# Authors@R: c( person("Jeroen", "Ooms", ,"jeroen@berkeley.edu", role = c("aut", "cre")), person("MongoDB, Inc", role = "cph", comment = "Bundled mongo-c-driver, see AUTHORS file") )
# Imports: jsonlite (>= 1.4), openssl (>= 0.9.4), mime
# License: Apache License 2.0
# URL: https://github.com/jeroen/mongolite/ (devel) https://jeroen.github.io/mongolite/ (user manual) http://mongoc.org/ (upstream)
# BugReports: https://github.com/jeroen/mongolite/issues
# SystemRequirements: OpenSSL, Cyrus SASL (aka libsasl2)
# RoxygenNote: 6.0.1.9000
# Suggests: spelling, nycflights13, ggplot2
# Language: en-GB
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2018-07-02 12:14:51 UTC; jeroen
# Author: Jeroen Ooms [aut, cre], MongoDB, Inc [cph] (Bundled mongo-c-driver, see AUTHORS file)
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-07-02 21:20:06 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
