{% set version = '6.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-roxygen2
  version: {{ version|replace("-", "_") }}

source:
  fn: roxygen2_6.0.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/roxygen2_6.0.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/roxygen2/roxygen2_6.0.1.tar.gz  # [linux or win32]
  sha256: d22ddc05cd5308a48b8359b932e1f7f4c23fdf0c857ac8e52c42381b6bfcff76  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/roxygen2_6.0.1.zip  # [win64]
  sha256: 285aaa4691a7d91720ada55dc223f0aaf01b887ffb87e65724bdefd4d5c952f4  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/roxygen2_6.0.1.tgz  # [osx]
  sha256: 63e62ff80e044c20c5247ddd59039d790d9cd5251ff2af75e0cd044ad8a34b14  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 0.8.0), knitr, devtools, rmarkdown, covr
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-r6
    - r-rcpp >=0.11.0
    - r-brew
    - r-commonmark
    - r-desc
    - r-digest
    - r-stringi
    - r-stringr >=0.5
    - r-xml2

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-r6
    - r-rcpp >=0.11.0
    - r-brew
    - r-commonmark
    - r-desc
    - r-digest
    - r-stringi
    - r-stringr >=0.5
    - r-xml2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('roxygen2')"           # [not win]
    - "\"%R%\" -e \"library('roxygen2')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/klutometis/roxygen
  license: GPL (>= 2)
  summary: Generate your Rd documentation, 'NAMESPACE' file, and collation  field using specially
    formatted comments. Writing documentation in-line with code makes it easier to keep
    your documentation up-to-date as your requirements change. 'Roxygen2' is inspired
    by the 'Doxygen' system for C++.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: roxygen2
# Title: In-Line Documentation for R
# Description: Generate your Rd documentation, 'NAMESPACE' file, and collation  field using specially formatted comments. Writing documentation in-line with code makes it easier to keep your documentation up-to-date as your requirements change. 'Roxygen2' is inspired by the 'Doxygen' system for C++.
# Version: 6.0.1
# License: GPL (>= 2)
# Authors@R: c( person("Hadley", "Wickham",, "hadley@rstudio.com", c("aut", "cre", "cph")), person("Peter", "Danenberg",, "pcd@roxygen.org", c("aut", "cph")), person("Manuel", "Eugster", role = c("aut", "cph")), person("RStudio", role = "cph") )
# Depends: R (>= 3.0.2)
# Imports: stringr (>= 0.5), stringi, brew, digest, methods, Rcpp (>= 0.11.0), R6, desc, commonmark, xml2, utils
# Suggests: testthat (>= 0.8.0), knitr, devtools, rmarkdown, covr
# VignetteBuilder: knitr
# LinkingTo: Rcpp
# RoxygenNote: 6.0.1
# URL: https://github.com/klutometis/roxygen
# BugReports: https://github.com/klutometis/roxygen/issues
# NeedsCompilation: yes
# Packaged: 2017-02-06 14:33:02 UTC; hadley
# Author: Hadley Wickham [aut, cre, cph], Peter Danenberg [aut, cph], Manuel Eugster [aut, cph], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-02-06 16:37:05

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
