{% set version = '6.1.0' %}  # [linux or win32]
{% set version = '6.1.0' %}  # [win64]
{% set version = '6.1.0' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-roxygen2
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/roxygen2_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/roxygen2/roxygen2_{{ version }}.tar.gz  # [linux or win32]
  sha256: 4af522cf79beebf96e591b8caf1465018e91310d12bb1a39a2cbed153499294a  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/roxygen2_6.1.0.zip  # [win64]
  sha256: dd38a306845e5b5556778378c357fd51ebb05356ae697825af310c604ae223e0  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/roxygen2_6.1.0.tgz  # [osx]
  sha256: 94aec27fb8aa4dbabb1d1f6c89beb5db5d1336f1843d7a921a79bb589b45cedc  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, devtools, knitr, rmarkdown, testthat (>= 0.8.0)
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-r6 >=2.1.2
    - r-rcpp >=0.11.0
    - r-brew
    - r-commonmark
    - r-desc
    - r-digest
    - r-pkgload
    - r-purrr
    - r-stringi
    - r-stringr >=1.0.0
    - r-xml2

  run:
    - mro-base
    - r-r6 >=2.1.2
    - r-rcpp >=0.11.0
    - r-brew
    - r-commonmark
    - r-desc
    - r-digest
    - r-pkgload
    - r-purrr
    - r-stringi
    - r-stringr >=1.0.0
    - r-xml2
    - libcxx >=4.0.1             # [osx]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('roxygen2')"           # [not win]
    - "\"%R%\" -e \"library('roxygen2')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/klutometis/roxygen
  license: GPL (>= 2)
  summary: Generate your Rd documentation, 'NAMESPACE' file, and collation  field using specially
    formatted comments. Writing documentation in-line with code makes it easier to keep
    your documentation up-to-date as your requirements change. 'Roxygen2' is inspired
    by the 'Doxygen' system for C++.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: roxygen2
# Title: In-Line Documentation for R
# Version: 6.1.0
# Authors@R: c( person("Hadley", "Wickham",, "hadley@rstudio.com", c("aut", "cre", "cph")), person("Peter", "Danenberg",, "pcd@roxygen.org", c("aut", "cph")), person("Manuel", "Eugster", role = c("aut", "cph")), person("RStudio", role = "cph") )
# Description: Generate your Rd documentation, 'NAMESPACE' file, and collation  field using specially formatted comments. Writing documentation in-line with code makes it easier to keep your documentation up-to-date as your requirements change. 'Roxygen2' is inspired by the 'Doxygen' system for C++.
# License: GPL (>= 2)
# URL: https://github.com/klutometis/roxygen
# BugReports: https://github.com/klutometis/roxygen/issues
# Depends: R (>= 3.1)
# Imports: brew, commonmark, desc, digest, methods, pkgload, purrr, R6 (>= 2.1.2), Rcpp (>= 0.11.0), stringi, stringr (>= 1.0.0), utils, xml2
# Suggests: covr, devtools, knitr, rmarkdown, testthat (>= 0.8.0)
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: yes
# Packaged: 2018-07-25 20:48:13 UTC; hadley
# Author: Hadley Wickham [aut, cre, cph], Peter Danenberg [aut, cph], Manuel Eugster [aut, cph], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-07-27 21:10:02 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
