{% set version = '0.1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-recipes
  version: {{ version|replace("-", "_") }}

source:
  fn: recipes_0.1.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/recipes_0.1.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/recipes/recipes_0.1.1.tar.gz  # [linux or win32]
  sha256: 04bcbf0c49e5edd0be8034d841b6e2bec1f1966ef1f64978ac8938150f33a445  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/recipes_0.1.1.zip  # [win64]
  sha256: b088cd5da6234ad4ee5753269914eb87b2e3bfe72af508d314b314183143e564  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/recipes_0.1.1.tgz  # [osx]
  sha256: d921b46de1bae22579d53dae0a245eee6e3716e5601ea9c31e985df8dd3fef0f  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, rpart, kernlab, fastICA, RANN, igraph, knitr, caret, ggplot2, rmarkdown, covr
requirements:
  build:

  host:
    - mro-base
    - r-matrix
    - r-rcpproll
    - r-broom
    - r-ddalpha
    - r-dimred >=0.1.0
    - r-dplyr
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-rlang >=0.1.1
    - r-tibble
    - r-tidyselect >=0.1.1
    - r-timedate

  run:
    - mro-base
    - r-matrix
    - r-rcpproll
    - r-broom
    - r-ddalpha
    - r-dimred >=0.1.0
    - r-dplyr
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-rlang >=0.1.1
    - r-tibble
    - r-tidyselect >=0.1.1
    - r-timedate

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('recipes')"           # [not win]
    - "\"%R%\" -e \"library('recipes')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/topepo/recipes
  license: GPL-2
  summary: 'An extensible framework to create and preprocess  design matrices. Recipes consist
    of one or more data manipulation  and analysis "steps". Statistical parameters for
    the steps can  be estimated from an initial data set and then applied to  other
    data sets. The resulting design matrices can then be used  as inputs into statistical
    or machine learning models. '

  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: recipes
# Title: Preprocessing Tools to Create Design Matrices
# Version: 0.1.1
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("RStudio", role = "cph"))
# Description: An extensible framework to create and preprocess  design matrices. Recipes consist of one or more data manipulation  and analysis "steps". Statistical parameters for the steps can  be estimated from an initial data set and then applied to  other data sets. The resulting design matrices can then be used  as inputs into statistical or machine learning models.
# URL: https://github.com/topepo/recipes
# BugReports: https://github.com/topepo/recipes/issues
# Depends: R (>= 3.1), dplyr, broom
# Imports: tibble, stats, ipred, dimRed (>= 0.1.0), lubridate, timeDate, ddalpha, purrr, rlang (>= 0.1.1), gower, RcppRoll, tidyselect (>= 0.1.1), magrittr, Matrix
# Suggests: testthat, rpart, kernlab, fastICA, RANN, igraph, knitr, caret, ggplot2, rmarkdown, covr
# License: GPL-2
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-11-20 15:59:11 UTC; max
# Author: Max Kuhn [aut, cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-11-20 17:33:39 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
