{% set version = '10.0.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-revoutils
  version: {{ version|replace("-", "_") }}

source:
  fn: RevoUtils_10.0.8.tar.gz
  url:
    - RevoUtils_10.0.8.tar.gz
  sha256: 59a9840c44da2207857ef665272ae2cfc6f759578b956c1b7a05827750445ae2







build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RevoUtils')"           # [not win]
    - "\"%R%\" -e \"library('RevoUtils')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=RevoUtils
  license: GPL-2
  summary: Utility functions for Microsoft R
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: RevoUtils
# Version: 10.0.8
# Date: 2018-02-03
# RevoBuildID: 10.0.8.0120
# Title: Microsoft R Utility Package
# Author: Microsoft Corporation
# Maintainer: Microsoft Corporation <mrspack@microsoft.com>
# SystemRequirements: R (>= 3.0.0)
# Description: Utility functions for Microsoft R
# License: GPL-2
# Copyright: Microsoft Corporation
# MRANDate: 2017-09-01
# NeedsCompilation: no
# Packaged: 2018-02-07 01:49:48 UTC; richcala

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
