{% set version = '1.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-commonmark
  version: {{ version|replace("-", "_") }}

source:
  fn: commonmark_1.4.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/commonmark_1.4.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/commonmark/commonmark_1.4.tar.gz  # [linux or win32]
  sha256: 865ecf9432763393ca9de52d0106a58c4be9e8d5196da60e068eed0b67ca68ed  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/commonmark_1.4.zip  # [win64]
  sha256: 92b08fc793a906ef211b5f09b6ee3626d408ead2b0f396a4e636c5e8de77eb14  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/commonmark_1.4.tgz  # [osx]
  sha256: 4f52758f6fcfface987b62ca61c5103ccd99eb91663163dc25f840a4539311c3  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: curl
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('commonmark')"           # [not win]
    - "\"%R%\" -e \"library('commonmark')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/jeroen/commonmark (devel) https://github.github.com/gfm/ (spec)
  license: BSD_2_clause + file LICENSE
  summary: The CommonMark specification defines a rationalized version of markdown syntax. This
    package uses the 'cmark' reference implementation for converting markdown text into
    various formats including html, latex and groff man. In addition it exposes the
    markdown parse tree in xml format. The latest version of this package also adds
    support for Github extensions including tables, autolinks and strikethrough text.
  license_family: BSD

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: commonmark
# Type: Package
# Title: High Performance CommonMark and Github Markdown Rendering in R
# Version: 1.4
# Authors@R: c( person("Jeroen", "Ooms", ,"jeroen@berkeley.edu", role = c("aut", "cre")), person("John MacFarlane", role = "cph", comment = "Author of cmark") )
# URL: http://github.com/jeroen/commonmark (devel) https://github.github.com/gfm/ (spec)
# BugReports: http://github.com/jeroen/commonmark/issues
# Description: The CommonMark specification defines a rationalized version of markdown syntax. This package uses the 'cmark' reference implementation for converting markdown text into various formats including html, latex and groff man. In addition it exposes the markdown parse tree in xml format. The latest version of this package also adds support for Github extensions including tables, autolinks and strikethrough text.
# License: BSD_2_clause + file LICENSE
# Suggests: curl
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-08-31 21:37:58 UTC; jeroen
# Author: Jeroen Ooms [aut, cre], John MacFarlane [cph] (Author of cmark)
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2017-09-01 09:47:38 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
