{% set version = '1.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-proto
  version: {{ version|replace("-", "_") }}

source:
  fn: proto_1.0.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/proto_1.0.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/proto/proto_1.0.0.tar.gz  # [linux or win32]
  sha256: 9294d9a3b2b680bb6fac17000bfc97453d77c87ef68cfd609b4c4eb6d11d04d1  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/proto_1.0.0.zip  # [win64]
  sha256: 7bd4e77c6c9b65acaea23676c7d47758a585d1165bdf2334400c562611f447c0  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/proto_1.0.0.tgz  # [osx]
  sha256: d5af058453f276419e6bccb81bf20cccfd4f078d02fb39ff054dc509b00dec79  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, covr
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('proto')"           # [not win]
    - "\"%R%\" -e \"library('proto')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/proto
  license: GPL-2
  summary: An object oriented system using object-based, also called prototype-based, rather
    than class-based object oriented ideas.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: proto
# Version: 1.0.0
# Title: Prototype Object-Based Programming
# Description: An object oriented system using object-based, also called prototype-based, rather than class-based object oriented ideas.
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", "cre"), person("Gabor", "Grothendieck", , "ggrothendieck@gmail.com", "aut"), person("Louis", "Kates", role = "aut"), person("Thomas", "Petzoldt", role = "aut") )
# License: GPL-2
# URL: https://github.com/hadley/proto
# BugReports: https://github.com/hadley/proto/issues
# Suggests: testthat, covr
# RoxygenNote: 5.0.1.9000
# NeedsCompilation: no
# Packaged: 2016-10-28 22:08:08 UTC; hadley
# Author: Hadley Wickham [cre], Gabor Grothendieck [aut], Louis Kates [aut], Thomas Petzoldt [aut]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2016-10-29 00:23:07

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
