{% set version = '0.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-testit
  version: {{ version|replace("-", "_") }}

source:
  fn: testit_0.7.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/testit_0.7.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/testit/testit_0.7.tar.gz  # [linux or win32]
  sha256: 03332889bffe8b69d36e696e3a6a1a29713cdcbccf1efced6cddbf061fb41a1f  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/testit_0.7.zip  # [win64]
  sha256: 9256885dd45a3d80ffc5db9bcc7bbde9927c56434d429a2864f1c93a3830467a  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/testit_0.7.tgz  # [osx]
  sha256: f84cc119c6a9d4906e243908196f7e088f1b1f44b35bd13ff3ee9f3295e6292e  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rstudioapi
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('testit')"           # [not win]
    - "\"%R%\" -e \"library('testit')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/yihui/testit
  license: GPL
  summary: Provides two convenience functions assert() and test_pkg() to facilitate testing R
    packages.
  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: testit
# Type: Package
# Title: A Simple Package for Testing R Packages
# Version: 0.7
# Date: 2017-05-21
# Author: Yihui Xie
# Maintainer: Yihui Xie <xie@yihui.name>
# Description: Provides two convenience functions assert() and test_pkg() to facilitate testing R packages.
# License: GPL
# URL: https://github.com/yihui/testit
# BugReports: https://github.com/yihui/testit/issues
# Suggests: rstudioapi
# Collate: 'testit.R' 'utils.R'
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-05-21 04:53:18 UTC; yihui
# Repository: CRAN
# Date/Publication: 2017-05-22 05:16:36 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
