{% set version = '0.21-2' %}  # [linux or win32]
{% set version = '0.21-2' %}  # [win64]
{% set version = '0.21-2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-afex
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/afex_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/afex/afex_{{ version }}.tar.gz  # [linux or win32]
  sha256: bfcee80813aa2b96217621f390530c799f12b2580ac970b95e6287c9dd76c671  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/afex_0.21-2.zip  # [win64]
  sha256: 7c1ac87bc6ea009e7fe18f982b74167dbcee2c11ad7a3a78f74b790e6c814696  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/afex_0.21-2.tgz  # [osx]
  sha256: 29d744fc6b9fbd901e7572cd3e6acb7145bbc5c8b0b31b6dccab3629bf2fe616  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: coin, xtable, parallel, plyr, optimx, nloptr, knitr, rmarkdown, R.rsp, lattice, latticeExtra, multcomp, testthat, mlmRev, dplyr, tidyr, dfoptim, Matrix, psych, ggplot2, MEMSS, effects, carData
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-car
    - r-emmeans >=1.1.2
    - r-lme4 >=1.1_8
    - r-lmertest >=3.0_0
    - r-pbkrtest >=0.4_1
    - r-reshape2

  run:
    - mro-base
    - r-car
    - r-emmeans >=1.1.2
    - r-lme4 >=1.1_8
    - r-lmertest >=3.0_0
    - r-pbkrtest >=0.4_1
    - r-reshape2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('afex')"           # [not win]
    - "\"%R%\" -e \"library('afex')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://afex.singmann.science/, https://github.com/singmann/afex
  license: GPL (>= 2)
  summary: Convenience functions for analyzing factorial experiments using ANOVA or mixed models.
    aov_ez(), aov_car(), and aov_4() allow specification of between, within (i.e., repeated-measures),
    or mixed between-within (i.e., split-plot) ANOVAs for data in long format (i.e.,
    one observation per row), aggregating multiple observations per individual and cell
    of the design. mixed() fits mixed models using lme4::lmer() and computes p-values
    for all fixed effects using either Kenward-Roger or Satterthwaite approximation
    for degrees of freedom (LMM only), parametric bootstrap (LMMs and GLMMs), or likelihood
    ratio tests (LMMs and GLMMs). afex uses type 3 sums of squares as default (imitating
    commercial statistical software).
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: afex
# Type: Package
# Title: Analysis of Factorial Experiments
# Depends: R (>= 3.1.0), lme4 (>= 1.1-8), emmeans (>= 1.1.2)
# Suggests: coin, xtable, parallel, plyr, optimx, nloptr, knitr, rmarkdown, R.rsp, lattice, latticeExtra, multcomp, testthat, mlmRev, dplyr, tidyr, dfoptim, Matrix, psych, ggplot2, MEMSS, effects, carData
# Imports: pbkrtest (>= 0.4-1), lmerTest (>= 3.0-0), car, reshape2, stats, methods
# Description: Convenience functions for analyzing factorial experiments using ANOVA or mixed models. aov_ez(), aov_car(), and aov_4() allow specification of between, within (i.e., repeated-measures), or mixed between-within (i.e., split-plot) ANOVAs for data in long format (i.e., one observation per row), aggregating multiple observations per individual and cell of the design. mixed() fits mixed models using lme4::lmer() and computes p-values for all fixed effects using either Kenward-Roger or Satterthwaite approximation for degrees of freedom (LMM only), parametric bootstrap (LMMs and GLMMs), or likelihood ratio tests (LMMs and GLMMs). afex uses type 3 sums of squares as default (imitating commercial statistical software).
# URL: http://afex.singmann.science/, https://github.com/singmann/afex
# BugReports: https://github.com/singmann/afex/issues
# License: GPL (>= 2)
# Encoding: UTF-8
# VignetteBuilder: knitr, R.rsp
# Authors@R: c(person(given="Henrik", family="Singmann", role=c("aut", "cre"), email="singmann+afex@gmail.com", comment=c(ORCID="0000-0002-4842-3657")), person(given="Ben", family="Bolker", role=c("aut")), person(given="Jake", family="Westfall", role=c("aut")), person(given="Frederik", family="Aust", role=c("aut"), comment = c(ORCID = "0000-0003-4900-788X")), person(given="Sren", family="Hjsgaard", role=c("ctb")), person(given="John", family="Fox", role=c("ctb")), person(given="Michael A.", family="Lawrence", role=c("ctb")), person(given="Ulf", family="Mertens", role=c("ctb")), person(given="Jonathon", family="Love", role=c("ctb")), person(given="Russell", family="Lenth", role=c("ctb")), person(given="Rune", family="Haubo Bojesen Christensen", role=c("ctb")) )
# Version: 0.21-2
# Date: 2018-06-24
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-06-24 16:41:15 UTC; henrik
# Author: Henrik Singmann [aut, cre] (<https://orcid.org/0000-0002-4842-3657>), Ben Bolker [aut], Jake Westfall [aut], Frederik Aust [aut] (<https://orcid.org/0000-0003-4900-788X>), Sren Hjsgaard [ctb], John Fox [ctb], Michael A. Lawrence [ctb], Ulf Mertens [ctb], Jonathon Love [ctb], Russell Lenth [ctb], Rune Haubo Bojesen Christensen [ctb]
# Maintainer: Henrik Singmann <singmann+afex@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-06-24 17:25:52 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
