{% set version = '0.2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lazyeval
  version: {{ version|replace("-", "_") }}

source:
  fn: lazyeval_0.2.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/lazyeval_0.2.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/lazyeval/lazyeval_0.2.1.tar.gz  # [linux or win32]
  sha256: 83b3a43e94c40fe7977e43eb607be0a3cd64c02800eae4f2774e7866d1e93f61  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/lazyeval_0.2.1.zip  # [win64]
  sha256: fe2c8803d8a2b4a304dd1a09a930fa5971d451bd28e4dacbed27c97a391251ab  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/lazyeval_0.2.1.tgz  # [osx]
  sha256: c7c41d8ade7e02055dcd6bac6a8fe057b69fbccdbf1125fe5b2e04df4e978adc  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown (>= 0.2.65), testthat, covr
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lazyeval')"           # [not win]
    - "\"%R%\" -e \"library('lazyeval')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=lazyeval
  license: GPL-3
  summary: An alternative approach to non-standard evaluation using formulas. Provides a full
    implementation of LISP style 'quasiquotation', making it easier to generate code
    with other code.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: lazyeval
# Version: 0.2.1
# Title: Lazy (Non-Standard) Evaluation
# Description: An alternative approach to non-standard evaluation using formulas. Provides a full implementation of LISP style 'quasiquotation', making it easier to generate code with other code.
# Authors@R: c( person("Hadley", "Wickham", ,"hadley@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph") )
# License: GPL-3
# LazyData: true
# Depends: R (>= 3.1.0)
# Suggests: knitr, rmarkdown (>= 0.2.65), testthat, covr
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-10-18 22:37:44 UTC; lionel
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-10-29 22:59:36 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
