{% set version = '0.9.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-manipulatewidget
  version: {{ version|replace("-", "_") }}

source:
  fn: manipulateWidget_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/manipulateWidget_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/manipulateWidget/manipulateWidget_{{ version }}.tar.gz  # [linux or win32]
  sha256: 5bf4bdb702263b0e156f40f3354922a06db7db544e497addcd6c98d9860bf3a3  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/manipulateWidget_0.9.0.zip  # [win64]
  sha256: 4fe67eb4100dbaed02d72dd2416ecd87adff1ca0bc2eb8fe4e326814ab748814  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/manipulateWidget_0.9.0.tgz  # [osx]
  sha256: 9544ae665bd77e1a8d3122f88757b4709da6941a7dd6d58402b3ffde0ea62db1  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: dygraphs, leaflet, plotly, xts, rmarkdown, testthat, covr
requirements:
  build:

  host:
    - mro-base
    - r-base64enc
    - r-codetools
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-miniui
    - r-shiny >=1.0.3

  run:
    - mro-base
    - r-base64enc
    - r-codetools
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-miniui
    - r-shiny >=1.0.3

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('manipulateWidget')"           # [not win]
    - "\"%R%\" -e \"library('manipulateWidget')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rte-antares-rpackage/manipulateWidget
  license: GPL (>= 2) | file LICENSE
  summary: Like package 'manipulate' does for static graphics, this package helps to easily add
    controls like sliders, pickers, checkboxes, etc. that  can be used to modify the
    input data or the parameters of an interactive  chart created with package 'htmlwidgets'.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: manipulateWidget
# Type: Package
# Title: Add Even More Interactivity to Interactive Charts
# Version: 0.9.0
# Date: 2018-03-26
# Authors@R: c( person("Jalal-Edine", "ZAWAM", email = "jalal-edine.zawam@rte-france.com", role = c("aut", "cre")), person("Francois", "Guillem", email = "francois.guillem@rte-france.com", role = c("aut")), person("RTE", role = "cph"), person("JJ", "Allaire", role = "ctb"), person("Marion", "Praz", email="mnpraz@gmail.com", role = "ctb", comment = "New user interface"), person("Benoit", "Thieurmel", role = "ctb", email = "benoit.thieurmel@datastorm.fr"), person(given = "Titouan", family = "Robert", email = "titouan.robert@datastorm.fr", role = "ctb"), person("Duncan", "Murdoch", email = "murdoch.duncan@gmail.com", role = "ctb") )
# Description: Like package 'manipulate' does for static graphics, this package helps to easily add controls like sliders, pickers, checkboxes, etc. that  can be used to modify the input data or the parameters of an interactive  chart created with package 'htmlwidgets'.
# URL: https://github.com/rte-antares-rpackage/manipulateWidget
# BugReports: https://goo.gl/pV7o5c
# License: GPL (>= 2) | file LICENSE
# Imports: shiny (>= 1.0.3), miniUI, htmltools, htmlwidgets, knitr, methods, tools, base64enc, grDevices, codetools
# Suggests: dygraphs, leaflet, plotly, xts, rmarkdown, testthat, covr
# LazyData: TRUE
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2018-03-26 15:02:06 UTC; jalazawa
# Author: Jalal-Edine ZAWAM [aut, cre], Francois Guillem [aut], RTE [cph], JJ Allaire [ctb], Marion Praz [ctb] (New user interface), Benoit Thieurmel [ctb], Titouan Robert [ctb], Duncan Murdoch [ctb]
# Maintainer: Jalal-Edine ZAWAM <jalal-edine.zawam@rte-france.com>
# Repository: CRAN
# Date/Publication: 2018-03-26 15:15:56 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
