{% set version = '1.0.2' %}  # [linux or win32]
{% set version = '1.0.2' %}  # [win64]
{% set version = '1.0.2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lintr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/lintr_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/lintr/lintr_{{ version }}.tar.gz  # [linux or win32]
  sha256: f61eb02fe102f30aedf60b8f526659623eeb87c1c520de49e45ab05645748692  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/lintr_1.0.2.zip  # [win64]
  sha256: e5ba96b0a64cc39b22bd5af0f8854d6e99edf74e9fb802a142c0f564e142ac21  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/lintr_1.0.2.tgz  # [osx]
  sha256: 53c01d9a5cdb5ac33468f6c18e8a95de9a5fd4b145451331276f99b6a23b9d3b  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rmarkdown, mockery
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-codetools
    - r-crayon
    - r-digest
    - r-httr
    - r-igraph
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-rstudioapi >=0.2
    - r-stringdist
    - r-testthat

  run:
    - mro-base
    - r-codetools
    - r-crayon
    - r-digest
    - r-httr
    - r-igraph
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-rstudioapi >=0.2
    - r-stringdist
    - r-testthat

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lintr')"           # [not win]
    - "\"%R%\" -e \"library('lintr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/jimhester/lintr
  license: MIT + file LICENSE
  summary: Checks adherence to a given style, syntax errors and possible semantic issues.  Supports
    on the fly checking of R code edited with 'RStudio IDE', 'Emacs', 'Vim', 'Sublime
    Text' and 'Atom'.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: lintr
# Title: A 'Linter' for R Code
# Version: 1.0.2
# Authors@R: person("Jim", "Hester", email = "james.f.hester@gmail.com", role = c("aut", "cre"))
# URL: https://github.com/jimhester/lintr
# BugReports: https://github.com/jimhester/lintr/issues
# Description: Checks adherence to a given style, syntax errors and possible semantic issues.  Supports on the fly checking of R code edited with 'RStudio IDE', 'Emacs', 'Vim', 'Sublime Text' and 'Atom'.
# Depends: R (>= 3.1.1)
# Imports: rex, crayon, codetools, stringdist, testthat, digest, igraph, rstudioapi (>= 0.2), httr, jsonlite, knitr, stats, utils
# Suggests: rmarkdown, mockery
# License: MIT + file LICENSE
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-11-08 15:30:13 UTC; jhester
# Author: Jim Hester [aut, cre]
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-11-08 15:35:50 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
