{% set version = '3.0' %}  # [linux or win32]
{% set version = '3.0' %}  # [win64]
{% set version = '3.0' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-leaps
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/leaps_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/leaps/leaps_{{ version }}.tar.gz  # [linux or win32]
  sha256: 55a879cdad5a4c9bc3b5697dd4d364b3a094a49d8facb6692f5ce6af82adf285  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/leaps_3.0.zip  # [win64]
  sha256: e970df4614ce6736fb6b617d87cc2f73f0ef4ae045359321b476a401772b520b  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/leaps_3.0.tgz  # [osx]
  sha256: 056792052b67fd5a90e0aff6fc19cf4871cdb8cae76f6148e81cddec61030c09  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: biglm
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('fortran') }}  # [linux or osx]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('leaps')"           # [not win]
    - "\"%R%\" -e \"library('leaps')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=leaps
  license: GPL (>= 2)
  summary: Regression subset selection, including exhaustive search.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: leaps
# Title: Regression Subset Selection
# Version: 3.0
# Author: Thomas Lumley based on Fortran code by Alan Miller
# Description: Regression subset selection, including exhaustive search.
# Depends:
# Suggests: biglm
# License: GPL (>= 2)
# Maintainer: Thomas Lumley <t.lumley@auckland.ac.nz>
# NeedsCompilation: yes
# Packaged: 2017-01-09 20:18:20 UTC; tlumley
# Repository: CRAN
# Date/Publication: 2017-01-10 00:04:32

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
