cran_mirror:
  - https://mran.microsoft.com/snapshot/2018-08-01
target_platform:
  - win-64  # [win]
  - osx-64  # [osx]
  - linux-64  # [linux]
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
libopenblas:
  - 0.3.2
