{% set version = '0.3.2' %}  # [linux or win32]
{% set version = '0.3.2' %}  # [win64]
{% set version = '0.3.2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvest
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/rvest_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/rvest/rvest_{{ version }}.tar.gz  # [linux or win32]
  sha256: 0d6e8837fb1df79b1c83e7b48d8f1e6245f34a10c4bb6952e7bec7867e4abb12  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/rvest_0.3.2.zip  # [win64]
  sha256: e409b2cfcb3f9ed912231626aeb6b76c7c9c77e8b0bd921c63a390402c1cdd03  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/rvest_0.3.2.tgz  # [osx]
  sha256: 55b4fdeb8545493c0d554d3f0da39c5db883a5aef348bdb0370674086f0567c0  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, png, stringi (>= 0.3.1), rmarkdown, covr
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-httr >=0.5
    - r-magrittr
    - r-selectr
    - r-xml2

  run:
    - mro-base
    - r-httr >=0.5
    - r-magrittr
    - r-selectr
    - r-xml2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rvest')"           # [not win]
    - "\"%R%\" -e \"library('rvest')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/rvest
  license: GPL-3
  summary: Wrappers around the 'xml2' and 'httr' packages to make it easy to download, then manipulate,
    HTML and XML.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rvest
# Version: 0.3.2
# Title: Easily Harvest (Scrape) Web Pages
# Description: Wrappers around the 'xml2' and 'httr' packages to make it easy to download, then manipulate, HTML and XML.
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph") )
# Depends: R (>= 3.0.1), xml2
# Imports: httr (>= 0.5), selectr, magrittr
# Suggests: testthat, knitr, png, stringi (>= 0.3.1), rmarkdown, covr
# Encoding: UTF-8
# License: GPL-3
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 5.0.1
# URL: https://github.com/hadley/rvest
# BugReports: https://github.com/hadley/rvest/issues
# NeedsCompilation: no
# Packaged: 2016-06-16 16:20:43 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2016-06-17 08:57:12

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
