{% set version = '0.1.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gower
  version: {{ version|replace("-", "_") }}

source:
  fn: gower_0.1.2.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/gower_0.1.2.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/gower/gower_0.1.2.tar.gz  # [linux or win32]
  sha256: eb91b2d2784d237c7055abcf3cfa4fc0b2226b855a0c29fc5a4e8eaa689079d5  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/gower_0.1.2.zip  # [win64]
  sha256: 76d4b8d4b360e52ad145b389eed358a6ebabf62d3e3196767be34687eb371050  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/gower_0.1.2.tgz  # [osx]
  sha256: f4aa5e4f07dda60bf5a4c8af4eb0641eea70db2e3183a133cb0e394473b9bc47  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gower')"           # [not win]
    - "\"%R%\" -e \"library('gower')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/markvanderloo/gower
  license: GPL-3
  summary: Compute Gower's distance (or similarity) coefficient between records. Compute  the
    top-n matches between records. Core algorithms are executed in parallel on systems
    supporting OpenMP.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: gower
# Maintainer: Mark van der Loo <mark.vanderloo@gmail.com>
# License: GPL-3
# Title: Gower's Distance
# LazyData: no
# Type: Package
# LazyLoad: yes
# Authors@R: c( person("Mark", "van der Loo", role=c("aut","cre"),email="mark.vanderloo@gmail.com"))
# Description: Compute Gower's distance (or similarity) coefficient between records. Compute  the top-n matches between records. Core algorithms are executed in parallel on systems supporting OpenMP.
# Version: 0.1.2
# URL: https://github.com/markvanderloo/gower
# BugReports: https://github.com/markvanderloo/gower/issues
# Date: 2017-02-23
# Suggests: testthat, knitr, rmarkdown
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2017-02-23 20:13:17 UTC; mark
# Author: Mark van der Loo [aut, cre]
# Repository: CRAN
# Date/Publication: 2017-02-23 23:35:17

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
