{% set version = '4.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bcp
  version: {{ version|replace("-", "_") }}

source:
  fn: bcp_4.0.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/bcp_4.0.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/bcp/bcp_4.0.0.tar.gz  # [linux or win32]
  sha256: f5b54d26fb09d087cf187dec0bc105a52476bf162b1c5a4a9a9e2929023a6dae  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/bcp_4.0.0.zip  # [win64]
  sha256: f802b284c12c7930e0e6a412250770cf97014d14f05dc30c17d6bb4a6eea9132  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/bcp_4.0.0.tgz  # [osx]
  sha256: 95084255430198035f1c5df2fa6bd3de0c1eddb5d7fff0418ec7cec7eca19a0d  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: DNAcopy, coda, strucchange, vegan, ggplot2, igraph
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{ compiler('fortran') }}    # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-rcpp >=0.9.2
    - r-rcpparmadillo

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-rcpp >=0.9.2
    - r-rcpparmadillo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bcp')"           # [not win]
    - "\"%R%\" -e \"library('bcp')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=bcp
  license: GPL (>= 2)
  summary: Provides an implementation of the Barry and Hartigan (1993) product partition model
    for the normal errors change point problem using Markov Chain Monte Carlo.  It also
    extends the methodology to regression models on a connected graph (Wang and Emerson,
    2015); this allows estimation of change point models with multivariate responses.
    Parallel MCMC, previously available in bcp v.3.0.0, is currently not implemented.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: bcp
# Type: Package
# Title: Bayesian Analysis of Change Point Problems
# Version: 4.0.0
# Date: 2015-07-14
# Author: Xiaofei Wang, Chandra Erdman, and John W. Emerson
# Maintainer: John W. Emerson <john.emerson@yale.edu>
# Depends: graphics, methods, grid
# Suggests: DNAcopy, coda, strucchange, vegan, ggplot2, igraph
# Description: Provides an implementation of the Barry and Hartigan (1993) product partition model for the normal errors change point problem using Markov Chain Monte Carlo.  It also extends the methodology to regression models on a connected graph (Wang and Emerson, 2015); this allows estimation of change point models with multivariate responses. Parallel MCMC, previously available in bcp v.3.0.0, is currently not implemented.
# License: GPL (>= 2)
# Imports: Rcpp (>= 0.9.2)
# LinkingTo: Rcpp, RcppArmadillo
# NeedsCompilation: yes
# Packaged: 2015-07-14 23:29:06 UTC; jay
# Repository: CRAN
# Date/Publication: 2015-07-15 13:23:42

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
