{% set version = '0.1.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidytext
  version: {{ version|replace("-", "_") }}

source:
  fn: tidytext_0.1.5.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/tidytext_0.1.5.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/tidytext/tidytext_0.1.5.tar.gz  # [linux or win32]
  sha256: 76333715f0834925ff0478e948a499ec95bb145575b80d4f0ad67eb9b96ae3a4  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/tidytext_0.1.5.zip  # [win64]
  sha256: 87a1a6dec36198a8607e51fd095dcb51ee11cdb291654a73b315c6e919631df7  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/tidytext_0.1.5.tgz  # [osx]
  sha256: fab2b1f0550a565b984e214c35910a1f82f3723d4c52ecbba3091b727141f581  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: readr, tidyr, XML, tm, quanteda, wordcloud, knitr, rmarkdown, ggplot2, reshape2, topicmodels, NLP, scales, gutenbergr, testthat, mallet, stm
requirements:
  build:

  host:
    - mro-base
    - r-matrix
    - r-broom
    - r-dplyr
    - r-hunspell
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-rlang
    - r-stringr
    - r-tokenizers

  run:
    - mro-base
    - r-matrix
    - r-broom
    - r-dplyr
    - r-hunspell
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-rlang
    - r-stringr
    - r-tokenizers

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tidytext')"           # [not win]
    - "\"%R%\" -e \"library('tidytext')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/juliasilge/tidytext
  license: MIT + file LICENSE
  summary: Text mining for word processing and sentiment analysis using 'dplyr', 'ggplot2', and
    other tidy tools.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tidytext
# Type: Package
# Title: Text Mining using 'dplyr', 'ggplot2', and Other Tidy Tools
# Version: 0.1.5
# Authors@R: c(person("Gabriela", "De Queiroz", email = "gabidequeiroz@gmail.com", role = c("ctb")), person("Oliver", "Keyes", email = "ironholds@gmail.com", role = c("ctb")), person("David", "Robinson", email = "admiral.david@gmail.com", role = c("aut")), person("Julia", "Silge", email = "julia.silge@gmail.com", role = c("aut", "cre")))
# Description: Text mining for word processing and sentiment analysis using 'dplyr', 'ggplot2', and other tidy tools.
# License: MIT + file LICENSE
# LazyData: TRUE
# URL: http://github.com/juliasilge/tidytext
# BugReports: http://github.com/juliasilge/tidytext/issues
# RoxygenNote: 6.0.1
# Depends: R (>= 2.10)
# Imports: rlang, dplyr, stringr, hunspell, broom, Matrix, tokenizers, janeaustenr, purrr (>= 0.1.1), methods
# Suggests: readr, tidyr, XML, tm, quanteda, wordcloud, knitr, rmarkdown, ggplot2, reshape2, topicmodels, NLP, scales, gutenbergr, testthat, mallet, stm
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2017-11-18 02:48:42 UTC; juliasilge
# Author: Gabriela De Queiroz [ctb], Oliver Keyes [ctb], David Robinson [aut], Julia Silge [aut, cre]
# Maintainer: Julia Silge <julia.silge@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-11-18 06:38:08 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
