{% set version = '1.3.1' %}  # [linux or win32]
{% set version = '1.3.1' %}  # [win64]
{% set version = '1.3.1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rngtools
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/rngtools_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/rngtools/rngtools_{{ version }}.tar.gz  # [linux or win32]
  sha256: 763fc493cb821a4d3e514c0dc876d602a692c528e1d67f295dde70c77009e224  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/rngtools_1.3.1.zip  # [win64]
  sha256: a8189801d0b7d180ab8f7b6896b26aa3b9d8b3c36efd262646e0f58ec88fcbd5  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/rngtools_1.3.1.tgz  # [osx]
  sha256: 30810be6b7c3376a6cc8ceb6cf5d1d67e28210e8e3d9f42c7854acaab83d9a96  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit, testthat
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-digest
    - r-pkgmaker >=0.20
    - r-stringr

  run:
    - mro-base
    - r-digest
    - r-pkgmaker >=0.20
    - r-stringr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rngtools')"           # [not win]
    - "\"%R%\" -e \"library('rngtools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://renozao.github.io/rngtools
  license: GPL-3
  summary: Provides a set of functions for working with Random Number Generators (RNGs). In particular,
    a generic S4 framework is defined for getting/setting the current RNG, or RNG data
    that are embedded into objects for reproducibility. Notably, convenient default
    methods greatly facilitate the way current RNG settings can be changed.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rngtools
# Authors@R: person("Renaud", "Gaujoux", email = "renozao@protonmail.com", role = c("aut", "cre"))
# Version: 1.3.1
# License: GPL-3
# Title: Utility Functions for Working with Random Number Generators
# Description: Provides a set of functions for working with Random Number Generators (RNGs). In particular, a generic S4 framework is defined for getting/setting the current RNG, or RNG data that are embedded into objects for reproducibility. Notably, convenient default methods greatly facilitate the way current RNG settings can be changed.
# URL: https://renozao.github.io/rngtools
# BugReports: http://github.com/renozao/rngtools/issues
# Encoding: UTF-8
# Depends: R (>= 3.0.0), methods, pkgmaker (>= 0.20)
# Imports: stringr, digest, utils, stats, parallel
# Suggests: RUnit, testthat
# Collate: 'rngtools-package.r' 'format.R' 'RNG.R' 'RNGseq.R'
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-05-15 11:15:29 UTC; renaud
# Author: Renaud Gaujoux [aut, cre]
# Maintainer: Renaud Gaujoux <renozao@protonmail.com>
# Repository: CRAN
# Date/Publication: 2018-05-15 16:41:13 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
