{% set version = '0.2.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-formattable
  version: {{ version|replace("-", "_") }}

source:
  fn: formattable_0.2.0.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/formattable_0.2.0.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/formattable/formattable_0.2.0.1.tar.gz  # [linux or win32]
  sha256: 2e935699fb8c68f55cad824ee2ff76acdb6ee0f363a4342a6f9b0809ea93f2e8  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/formattable_0.2.0.1.zip  # [win64]
  sha256: 38143369246acb8a9d6542365c68d9909c0586945c0a13089308c554a8793f22  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/formattable_0.2.0.1.tgz  # [osx]
  sha256: bd7a1fc661567113e3df96dff43c692880cfbc98a7035ba3c75c5e517516a054  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, DT, shiny, covr
requirements:
  build:

  host:
    - mro-base
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-rmarkdown

  run:
    - mro-base
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-rmarkdown

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('formattable')"           # [not win]
    - "\"%R%\" -e \"library('formattable')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://renkun.me/formattable, https://github.com/renkun-ken/formattable
  license: MIT + file LICENSE
  summary: Provides functions to create formattable vectors and data frames. 'Formattable' vectors
    are printed with text formatting, and formattable data frames are printed with multiple
    types of formatting in HTML to improve the readability of data presented in tabular
    form rendered in web pages.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: formattable
# Title: Create 'Formattable' Data Structures
# Version: 0.2.0.1
# Authors@R: c( person("Kun", "Ren", role = c("aut", "cre"), email = "ken@renkun.me"), person("Kenton", "Russell", role = "aut", email = "kent.russell@timelyportfolio.com") )
# Description: Provides functions to create formattable vectors and data frames. 'Formattable' vectors are printed with text formatting, and formattable data frames are printed with multiple types of formatting in HTML to improve the readability of data presented in tabular form rendered in web pages.
# Depends: R (> 3.0.2)
# Date: 2016-08-05
# Imports: methods, htmltools, htmlwidgets, knitr, rmarkdown
# License: MIT + file LICENSE
# LazyData: true
# URL: https://renkun.me/formattable, https://github.com/renkun-ken/formattable
# BugReports: https://github.com/renkun-ken/formattable/issues
# ByteCompile: TRUE
# Suggests: testthat, DT, shiny, covr
# RoxygenNote: 5.0.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2016-08-05 01:44:15 UTC; renkun
# Author: Kun Ren [aut, cre], Kenton Russell [aut]
# Maintainer: Kun Ren <ken@renkun.me>
# Repository: CRAN
# Date/Publication: 2016-08-05 11:53:18

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
