{% set version = '1.95-4.11' %}  # [linux or win32]
{% set version = '1.95-4.11' %}  # [win64]
{% set version = '1.95-4.11' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcurl
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/RCurl_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/RCurl/RCurl_{{ version }}.tar.gz  # [linux or win32]
  sha256: 792a091cf5b80c460d98ed80fe1cad5d9406d0afc32e466e970ee4d2f68c97bf  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/RCurl_1.95-4.11.zip  # [win64]
  sha256: 8100212cf9a996407d4a36fd667d8c36672acf82a7b28c4d63e56aa600172af5  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/RCurl_1.95-4.11.tgz  # [osx]
  sha256: b5c4f9efa2f622f149fb6c316a7e5a8d5cefc61f314f35845c5db9a3bafb1165  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: Rcompression, XML
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{native}}rtools           # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-bitops

  run:
    - mro-base
    - r-bitops

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RCurl')"           # [not win]
    - "\"%R%\" -e \"library('RCurl')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.omegahat.net/RCurl
  license: BSD
  summary: A wrapper for 'libcurl' <http://curl.haxx.se/libcurl/> Provides functions to allow
    one to compose general HTTP requests and provides convenient functions to fetch
    URIs, get & post forms, etc. and process the results returned by the Web server.
    This provides a great deal of control over the HTTP/FTP/... connection and the form
    of the request while providing a higher-level interface than is available just using
    R socket connections.  Additionally, the underlying implementation is robust and
    extensive, supporting FTP/FTPS/TFTP (uploads and downloads), SSL/HTTPS, telnet,
    dict, ldap, and also supports cookies, redirects, authentication, etc.
  license_family: BSD

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: RCurl
# Version: 1.95-4.11
# Title: General Network (HTTP/FTP/...) Client Interface for R
# Author: Duncan Temple Lang and the CRAN team
# SystemRequirements: GNU make, libcurl
# Maintainer: Duncan Temple Lang <duncan@r-project.org>
# Description: A wrapper for 'libcurl' <http://curl.haxx.se/libcurl/> Provides functions to allow one to compose general HTTP requests and provides convenient functions to fetch URIs, get & post forms, etc. and process the results returned by the Web server. This provides a great deal of control over the HTTP/FTP/... connection and the form of the request while providing a higher-level interface than is available just using R socket connections.  Additionally, the underlying implementation is robust and extensive, supporting FTP/FTPS/TFTP (uploads and downloads), SSL/HTTPS, telnet, dict, ldap, and also supports cookies, redirects, authentication, etc.
# License: BSD
# Depends: R (>= 3.0.0), methods, bitops
# Suggests: Rcompression, XML
# URL: http://www.omegahat.net/RCurl
# Additional_repositories: http://www.omegahat.net/R/
# Limitations: One doesn't yet have full control over the contents of a POST form such as specifying files, content type. Error handling uses a single global variable at present.
# Note: This will be used generally to communicate with HTTP servers and specifically in the SOAP package, HTML forms and for accessing data on Web sites that require more state information than simply URL access (e.g. cookies).
# Check: To run R CMD check, one really needs network access. It is an HTTP client! This can be problematic as a Web site may be down when you run but the real tests are important.
# Collate: aclassesEnums.R bitClasses.R xbits.R base64.R binary.S classes.S curl.S curlAuthConstants.R curlEnums.R curlError.R curlInfo.S dynamic.R form.S getFormParams.R getURLContent.R header.R http.R httpError.R httpErrors.R iconv.R info.S mime.R multi.S options.S scp.R support.S upload.R urlExists.R zclone.R zzz.R
# NeedsCompilation: yes
# Packaged: 2018-07-15 16:08:05 UTC; ripley
# Repository: CRAN
# Date/Publication: 2018-07-15 17:13:41 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
