{% set version = '0.4.1' %}  # [linux or win32]
{% set version = '0.4.1' %}  # [win64]
{% set version = '0.4.1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clipr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/clipr_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/clipr/clipr_{{ version }}.tar.gz  # [linux or win32]
  sha256: 1bebc57ddad830c469415a99b13124aee14b91f4b1701fd20defb04623413d18  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/clipr_0.4.1.zip  # [win64]
  sha256: 97b453b9321ba3f76294ac384fd62014fb117ffab88ce9600f6440d4d408c3ff  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/clipr_0.4.1.tgz  # [osx]
  sha256: 568af5c54cf68395342d550130ab5301f12825f171f854c5ca98d7f0a66dbae3  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rstudioapi (>= 0.5), testthat, covr
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('clipr')"           # [not win]
    - "\"%R%\" -e \"library('clipr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/mdlincoln/clipr
  license: GPL-3
  summary: Simple utility functions to read from and write to the Windows, OS X, and X11 clipboards.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: clipr
# Type: Package
# Title: Read and Write from the System Clipboard
# Version: 0.4.1
# Authors@R: c( person("Matthew", "Lincoln", email = "matthew.d.lincoln@gmail.com", role = c("aut", "cre")), person("Louis", "Maddox", role = "ctb"), person("Steve", "Simpson", role = "ctb"), person("Jennifer", "Bryan", role = "ctb"))
# Description: Simple utility functions to read from and write to the Windows, OS X, and X11 clipboards.
# Imports: utils
# SystemRequirements: xclip (https://github.com/astrand/xclip) or xsel (http://www.vergenet.net/~conrad/software/xsel/) for accessing the X11 clipboard
# License: GPL-3
# LazyData: TRUE
# Suggests: rstudioapi (>= 0.5), testthat, covr
# URL: https://github.com/mdlincoln/clipr
# BugReports: https://github.com/mdlincoln/clipr/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-06-23 19:32:09 UTC; admin
# Author: Matthew Lincoln [aut, cre], Louis Maddox [ctb], Steve Simpson [ctb], Jennifer Bryan [ctb]
# Maintainer: Matthew Lincoln <matthew.d.lincoln@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-06-23 19:47:55 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
