{% set version = '0.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-functional
  version: {{ version|replace("-", "_") }}

source:
  fn: functional_0.6.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/functional_0.6.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/functional/functional_0.6.tar.gz  # [linux or win32]
  sha256: 19b78e27c27b1081245222c42da4dd1cb65c5643e6da9d6c1a6e997755c21888  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/functional_0.6.zip  # [win64]
  sha256: 024707bc62f5686a0643bf67eb8d53f0ee806131ad4eabc0808f6b54c0e75d0a  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/functional_0.6.tgz  # [osx]
  sha256: fcc46fec9e19aab8b4122a548ed3e71ae46180d53cf6fa95168fa7b25fda01bc  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('functional')"           # [not win]
    - "\"%R%\" -e \"library('functional')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=functional
  license: GPL (>= 2)
  summary: Curry, Compose, and other higher-order functions
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: functional
# Type: Package
# Title: Curry, Compose, and other higher-order functions
# Version: 0.6
# Date: 2014-07-15
# Author: Peter Danenberg <pcd@roxygen.org>
# Maintainer: Peter Danenberg <pcd@roxygen.org>
# Description: Curry, Compose, and other higher-order functions
# License: GPL (>= 2)
# LazyLoad: yes
# Packaged: 2014-07-15 23:41:35 UTC; danenberg
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-07-16 07:38:04

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
