{% set version = '0.9-1' %}  # [linux or win32]
{% set version = '0.9-1' %}  # [win64]
{% set version = '0.9-1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qvcalc
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/qvcalc_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/qvcalc/qvcalc_{{ version }}.tar.gz  # [linux or win32]
  sha256: de2311ade76dae311b2b5632633003667aa46cdb8703a330b84b67c4b90f87d2  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/qvcalc_0.9-1.zip  # [win64]
  sha256: 6ba3c67cb2084e7ea2f6fee424e73df904a084042158b0750e2a8a07af48f6a2  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/macosx/el-capitan/contrib/3.5/qvcalc_0.9-1.tgz  # [osx]
  sha256: 7a4affe2db65acc3907746fbe7198f3e7a4bcd3b2f190baadd9658a1ab229b3f  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: relimp, MASS
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('qvcalc')"           # [not win]
    - "\"%R%\" -e \"library('qvcalc')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/DavidFirth/qvcalc
  license: GPL-2 | GPL-3
  summary: Functions to compute quasi variances and associated measures of approximation error.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: qvcalc
# Version: 0.9-1
# Date: 2017-09-18
# Title: Quasi Variances for Factor Effects in Statistical Models
# Author: David Firth
# Maintainer: David Firth <d.firth@warwick.ac.uk>
# URL: https://github.com/DavidFirth/qvcalc
# Description: Functions to compute quasi variances and associated measures of approximation error.
# Suggests: relimp, MASS
# Enhances: psychotools
# License: GPL-2 | GPL-3
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-09-18 12:24:45 UTC; david
# Repository: CRAN
# Date/Publication: 2017-09-19 16:18:11 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
