{% set version = '1.2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-emmeans
  version: {{ version|replace("-", "_") }}

source:
  fn: emmeans_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/emmeans_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/emmeans/emmeans_{{ version }}.tar.gz  # [linux or win32]
  sha256: 75cb8670d012066c16c1260e3491f05beb08aa48ab4adfac2c25885116a1a166  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/emmeans_1.2.1.zip  # [win64]
  sha256: e63fe193a8eec9f0e9125970e50d50f1e66466629eecacc596c464a0288b793f  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/emmeans_1.2.1.tgz  # [osx]
  sha256: 581e65cf7c233b02b437ea506cf6151e1744477083f44aff109e44140f00ceec  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bayesplot, brms, car, lattice, mediation, multcompView, ordinal, pbkrtest (>= 0.4-1), lme4, lmerTest (>= 2.0.32), MASS, rsm, knitr, rmarkdown, testthat
requirements:
  build:

  host:
    - mro-base
    - r-coda >=0.17
    - r-estimability >=1.3
    - r-ggplot2
    - r-multcomp
    - r-mvtnorm
    - r-nlme
    - r-plyr
    - r-xtable >=1.8_2

  run:
    - mro-base
    - r-coda >=0.17
    - r-estimability >=1.3
    - r-ggplot2
    - r-multcomp
    - r-mvtnorm
    - r-nlme
    - r-plyr
    - r-xtable >=1.8_2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('emmeans')"           # [not win]
    - "\"%R%\" -e \"library('emmeans')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rvlenth/emmeans
  license: GPL-2 | GPL-3
  summary: 'Obtain estimated marginal means (EMMs) for many linear, generalized  linear, and
    mixed models. Compute contrasts or linear functions of EMMs, trends, and comparisons
    of slopes. Plots and compact letter displays. Least-squares means are discussed,
    and the term "estimated marginal means" is suggested, in Searle, Speed, and Milliken
    (1980) Population marginal means  in the linear model: An alternative to least squares
    means, The American  Statistician 34(4), 216-221 <doi:10.1080/00031305.1980.10483031>.'

  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: emmeans
# Type: Package
# Title: Estimated Marginal Means, aka Least-Squares Means
# Version: 1.2.1
# Date: 2018-05-20
# Authors@R: c(person("Russell", "Lenth", role = c("aut", "cre", "cph"),  email = "russell-lenth@uiowa.edu"), person("Henrik", "Singmann", role = "ctb"), person("Jonathon", "Love", role = "ctb"), person("Paul", "Buerkner", role = "ctb"), person("Maxime", "Herve", role = "ctb"))
# Depends: R (>= 3.2)
# Imports: estimability (>= 1.3), ggplot2, graphics, methods, stats, utils, nlme, coda (>= 0.17), multcomp, plyr, mvtnorm, xtable (>= 1.8-2)
# Suggests: bayesplot, brms, car, lattice, mediation, multcompView, ordinal, pbkrtest (>= 0.4-1), lme4, lmerTest (>= 2.0.32), MASS, rsm, knitr, rmarkdown, testthat
# Enhances: CARBayes, coxme, gee, geepack, glmmADMB, MCMCglmm, MCMCpack, nnet, pscl, rstanarm, survival
# Additional_repositories: http://glmmadmb.r-forge.r-project.org/repos
# URL: https://github.com/rvlenth/emmeans
# BugReports: https://github.com/rvlenth/emmeans/issues
# LazyData: yes
# ByteCompile: yes
# Description: Obtain estimated marginal means (EMMs) for many linear, generalized  linear, and mixed models. Compute contrasts or linear functions of EMMs, trends, and comparisons of slopes. Plots and compact letter displays. Least-squares means are discussed, and the term "estimated marginal means" is suggested, in Searle, Speed, and Milliken (1980) Population marginal means  in the linear model: An alternative to least squares means, The American  Statistician 34(4), 216-221 <doi:10.1080/00031305.1980.10483031>.
# License: GPL-2 | GPL-3
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-05-20 18:01:23 UTC; Russell
# Author: Russell Lenth [aut, cre, cph], Henrik Singmann [ctb], Jonathon Love [ctb], Paul Buerkner [ctb], Maxime Herve [ctb]
# Maintainer: Russell Lenth <russell-lenth@uiowa.edu>
# Repository: CRAN
# Date/Publication: 2018-05-21 16:46:31 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
