{% set version = '3.0.4' %}  # [linux or win32 or osx]
{% set version = '3.0.4' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kohonen
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/kohonen_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/kohonen/kohonen_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 429864d72858c29d4187bed48ac1c17cf2ecb08f18090b6bf44dff55174609ab  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/kohonen_3.0.4.zip  # [win64]
  sha256: eaaa8cc7f5602ef4446475bb99de4949317f077e0711b70bbd5e921cc658c4cc  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{ compiler('cxx') }}      # [linux or osx]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32 or osx]
    - {{posix}}sed               # [win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-mass
    - r-rcpp >=0.12.7

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-mass
    - r-rcpp >=0.12.7

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('kohonen')"           # [not win]
    - "\"%R%\" -e \"library('kohonen')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=kohonen
  license: GPL (>= 2)
  summary: Functions to train self-organising maps (SOMs). Also interrogation of the maps and
    prediction using trained maps are supported. The name of the package refers to Teuvo
    Kohonen, the inventor of the SOM.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: kohonen
# Version: 3.0.4
# Title: Supervised and Unsupervised Self-Organising Maps
# Author: Ron Wehrens and Johannes Kruisselbrink
# Maintainer: Ron Wehrens <ron.wehrens@gmail.com>
# Description: Functions to train self-organising maps (SOMs). Also interrogation of the maps and prediction using trained maps are supported. The name of the package refers to Teuvo Kohonen, the inventor of the SOM.
# License: GPL (>= 2)
# Depends: R (>= 2.10)
# Imports: MASS, Rcpp (>= 0.12.7)
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2017-08-28 15:23:15 UTC; ron
# Repository: CRAN
# Date/Publication: 2017-08-28 18:51:19 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
