{% set version = '7.3-11' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatial
  version: {{ version|replace("-", "_") }}

source:
  fn: spatial_7.3-11.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/spatial_7.3-11.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/spatial/spatial_7.3-11.tar.gz  # [linux or win32]
  sha256: 624448d2ac22e1798097d09fc5dc4605908a33f490b8ec971fc6ea318a445c11  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/spatial_7.3-11.zip  # [win64]
  sha256: 113042ec9665be208f2d23db8be156f616c918b2519fdff18afd9c4816218f65  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/spatial_7.3-11.tgz  # [osx]
  sha256: e63f8cc3764ab43d56c8692fe454ab3e8adb8457bd7b0d897ad7861e2725b3dd  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('spatial')"           # [not win]
    - "\"%R%\" -e \"library('spatial')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.stats.ox.ac.uk/pub/MASS4/
  license: GPL-2 | GPL-3
  summary: Functions for kriging and point pattern analysis.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: spatial
# Priority: recommended
# Version: 7.3-11
# Date: 2015-08-29
# Depends: R (>= 3.0.0), graphics, stats, utils
# Suggests: MASS
# Authors@R: c(person("Brian", "Ripley", role = c("aut", "cre", "cph"), email = "ripley@stats.ox.ac.uk"), person("Roger", "Bivand", role = "ctb"), person("William", "Venables", role = "cph"))
# Description: Functions for kriging and point pattern analysis.
# Title: Functions for Kriging and Point Pattern Analysis
# LazyLoad: yes
# ByteCompile: yes
# License: GPL-2 | GPL-3
# URL: http://www.stats.ox.ac.uk/pub/MASS4/
# NeedsCompilation: yes
# Packaged: 2015-08-28 15:25:37 UTC; ripley
# Author: Brian Ripley [aut, cre, cph], Roger Bivand [ctb], William Venables [cph]
# Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
# Repository: CRAN
# Date/Publication: 2015-08-30 08:59:41

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
