{% set version = '0.9-35' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lmtest
  version: {{ version|replace("-", "_") }}

source:
  fn: lmtest_0.9-35.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/lmtest_0.9-35.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/lmtest/lmtest_0.9-35.tar.gz  # [linux or win32]
  sha256: 2f4982f1b6cd133ef36fe9718f4ff2f4fa5c20716100fdd5ee5c947b68c8eb80  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/lmtest_0.9-35.zip  # [win64]
  sha256: d4995f8211c37d1765e986598801f17456985d7e4df537dc650b9298fa24f87e  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/lmtest_0.9-35.tgz  # [osx]
  sha256: 8e3cbbfc4f5ccdb50afcaf5db7e645e360a8ab1c4a238df82d57c3108137bad8  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: car, strucchange, sandwich, dynlm, stats4, survival, AER
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('fortran') }}    # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-zoo

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lmtest')"           # [not win]
    - "\"%R%\" -e \"library('lmtest')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=lmtest
  license: GPL-2 | GPL-3
  summary: A collection of tests, data sets, and examples for diagnostic checking in linear regression
    models. Furthermore, some generic tools for inference in parametric models are provided.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: lmtest
# Title: Testing Linear Regression Models
# Version: 0.9-35
# Date: 2017-02-11
# Authors@R: c(person(given = "Torsten", family = "Hothorn", role = "aut", email = "Torsten.Hothorn@R-project.org"), person(given = "Achim", family = "Zeileis", role = c("aut", "cre"), email = "Achim.Zeileis@R-project.org"), person(given = c("Richard", "W."), family = "Farebrother", role = "aut", comment = "pan.f"), person(given = "Clint", family = "Cummins", role = "aut", comment = "pan.f"), person(given = "Giovanni", family = "Millo", role = "ctb"), person(given = "David", family = "Mitchell", role = "ctb"))
# Description: A collection of tests, data sets, and examples for diagnostic checking in linear regression models. Furthermore, some generic tools for inference in parametric models are provided.
# LazyData: yes
# Depends: R (>= 2.10.0), stats, zoo
# Suggests: car, strucchange, sandwich, dynlm, stats4, survival, AER
# Imports: graphics
# License: GPL-2 | GPL-3
# NeedsCompilation: yes
# Packaged: 2017-02-11 09:30:28 UTC; zeileis
# Author: Torsten Hothorn [aut], Achim Zeileis [aut, cre], Richard W. Farebrother [aut] (pan.f), Clint Cummins [aut] (pan.f), Giovanni Millo [ctb], David Mitchell [ctb]
# Maintainer: Achim Zeileis <Achim.Zeileis@R-project.org>
# Repository: CRAN
# Date/Publication: 2017-02-11 10:43:09

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
