{% set version = '2.23-15' %}  # [linux or win32]
{% set version = '2.23-15' %}  # [win64]
{% set version = '2.23-15' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kernsmooth
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/KernSmooth_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/KernSmooth/KernSmooth_{{ version }}.tar.gz  # [linux or win32]
  sha256: 8b72d23ed121a54af188b2cda4441e3ce2646359309885f6455b82c0275210f6  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/KernSmooth_2.23-15.zip  # [win64]
  sha256: 35cf843ee20168aac520ff9011be98c6fab7ff9e84ee09e1a1a605d0d8b3f238  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/KernSmooth_2.23-15.tgz  # [osx]
  sha256: f877d8dd47469d539ed9fefebb3f5d9b0e9b21ec373d4472d4cc5d08790dcf21  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('KernSmooth')"           # [not win]
    - "\"%R%\" -e \"library('KernSmooth')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=KernSmooth
  license: Unlimited
  summary: 'Functions for kernel smoothing (and density estimation) corresponding to the book:  Wand,
    M.P. and Jones, M.C. (1995) "Kernel Smoothing".'

  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: KernSmooth
# Priority: recommended
# Version: 2.23-15
# Date: 2015-06-29
# Title: Functions for Kernel Smoothing Supporting Wand & Jones (1995)
# Authors@R: c(person("Matt", "Wand", role = "aut", email = "Matt.Wand@uts.edu.au"), person("Brian", "Ripley", role = c("trl", "cre", "ctb"), email = "ripley@stats.ox.ac.uk", comment = "R port and updates"))
# Depends: R (>= 2.5.0), stats
# Suggests: MASS
# Description: Functions for kernel smoothing (and density estimation) corresponding to the book:  Wand, M.P. and Jones, M.C. (1995) "Kernel Smoothing".
# License: Unlimited
# ByteCompile: yes
# NeedsCompilation: yes
# Packaged: 2015-06-29 08:37:00 UTC; ripley
# Author: Matt Wand [aut], Brian Ripley [trl, cre, ctb] (R port and updates)
# Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
# Repository: CRAN
# Date/Publication: 2015-06-29 17:15:14

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
