{% set version = '4.6-12' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-randomforest
  version: {{ version|replace("-", "_") }}

source:
  fn: randomForest_4.6-12.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/randomForest_4.6-12.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/randomForest/randomForest_4.6-12.tar.gz  # [linux or win32]
  sha256: 6e512f8f88a51c01a918360acba61f1f39432f6e690bc231b7864218558b83c4  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/randomForest_4.6-12.zip  # [win64]
  sha256: d9b4c97a81a7ce199905a26c987e3fa2049480534576325ae83b47b19a85b4b6  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/randomForest_4.6-12.tgz  # [osx]
  sha256: 48836db0e31581d837b4af381b6c4242c832b57a9e076b49cf71897ecec797f7  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RColorBrewer, MASS
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('fortran') }}    # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('randomForest')"           # [not win]
    - "\"%R%\" -e \"library('randomForest')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://www.stat.berkeley.edu/~breiman/RandomForests/
  license: GPL (>= 2)
  summary: Classification and regression based on a forest of trees using random inputs.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: randomForest
# Title: Breiman and Cutler's Random Forests for Classification and Regression
# Version: 4.6-12
# Date: 2015-10-06
# Depends: R (>= 2.5.0), stats
# Suggests: RColorBrewer, MASS
# Author: Fortran original by Leo Breiman and Adele Cutler, R port by Andy Liaw and Matthew Wiener.
# Description: Classification and regression based on a forest of trees using random inputs.
# Maintainer: Andy Liaw <andy_liaw@merck.com>
# License: GPL (>= 2)
# URL: https://www.stat.berkeley.edu/~breiman/RandomForests/
# NeedsCompilation: yes
# Packaged: 2015-10-06 18:28:23 UTC; Liawand
# Repository: CRAN
# Date/Publication: 2015-10-07 08:38:34

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
