{% set version = '4.6-14' %}  # [linux or win32]
{% set version = '4.6-14' %}  # [win64]
{% set version = '4.6-14' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-randomforest
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/randomForest_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/randomForest/randomForest_{{ version }}.tar.gz  # [linux or win32]
  sha256: f4b88920419eb0a89d0bc5744af0416d92d112988702dc726882394128a8754d  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/randomForest_4.6-14.zip  # [win64]
  sha256: 5aa96b7937961145e9a40de7a1478a5af25390fb5ce47a7ce6c64d2bf242c5d9  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/macosx/el-capitan/contrib/3.5/randomForest_4.6-14.tgz  # [osx]
  sha256: f50b44e247df061d138398429140bae15508a8379d144a899b032044635818f2  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RColorBrewer, MASS
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]
    - {{posix}}sed               # [win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('randomForest')"           # [not win]
    - "\"%R%\" -e \"library('randomForest')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://www.stat.berkeley.edu/~breiman/RandomForests/
  license: GPL (>= 2)
  summary: Classification and regression based on a forest of trees using random inputs, based
    on Breiman (2001) <DOI:10.1023/A:1010933404324>.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: randomForest
# Title: Breiman and Cutler's Random Forests for Classification and Regression
# Version: 4.6-14
# Date: 2018-03-22
# Depends: R (>= 3.2.2), stats
# Suggests: RColorBrewer, MASS
# Author: Fortran original by Leo Breiman and Adele Cutler, R port by Andy Liaw and Matthew Wiener.
# Description: Classification and regression based on a forest of trees using random inputs, based on Breiman (2001) <DOI:10.1023/A:1010933404324>.
# Maintainer: Andy Liaw <andy_liaw@merck.com>
# License: GPL (>= 2)
# URL: https://www.stat.berkeley.edu/~breiman/RandomForests/
# NeedsCompilation: yes
# Packaged: 2018-03-22 14:27:01 UTC; liawand
# Repository: CRAN
# Date/Publication: 2018-03-25 15:00:24 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
