{% set version = '2.1.16' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-yaml
  version: {{ version|replace("-", "_") }}

source:
  fn: yaml_2.1.16.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/yaml_2.1.16.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/yaml/yaml_2.1.16.tar.gz  # [linux or win32]
  sha256: 75da4b175089b1634b532b5d4c4bf3eb72177c30c0a09e1333fc004315ae9af6  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/yaml_2.1.16.zip  # [win64]
  sha256: 12fbc50b619423c3078a2c15cdf1fee846cf01d70d7a4948d79d335ee0e1faa2  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/yaml_2.1.16.tgz  # [osx]
  sha256: 7343c79e30186dc2f58fccd20a2ad069f2784d4a2130a75de4d7edc5897a8ccf  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('yaml')"           # [not win]
    - "\"%R%\" -e \"library('yaml')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/viking/r-yaml/
  license: BSD_3_clause + file LICENSE
  summary: Implements the 'libyaml' 'YAML' 1.1 parser and emitter (<http://pyyaml.org/wiki/LibYAML>)
    for R.
  license_family: BSD

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: yaml
# Type: Package
# Title: Methods to Convert R Data to YAML and Back
# Version: 2.1.16
# Suggests: testthat
# Date: 2017-12-12
# Author: Jeremy Stephens <jeremy.stephens@vanderbilt.edu>
# Maintainer: Jeremy Stephens <jeremy.stephens@vanderbilt.edu>
# License: BSD_3_clause + file LICENSE
# Description: Implements the 'libyaml' 'YAML' 1.1 parser and emitter (<http://pyyaml.org/wiki/LibYAML>) for R.
# URL: https://github.com/viking/r-yaml/
# BugReports: https://github.com/viking/r-yaml/issues
# NeedsCompilation: yes
# Packaged: 2017-12-12 21:22:51 UTC; stephej1
# Repository: CRAN
# Date/Publication: 2017-12-12 22:10:58 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
