{% set version = '1.3.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ddalpha
  version: {{ version|replace("-", "_") }}

source:
  fn: ddalpha_1.3.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/ddalpha_1.3.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/ddalpha/ddalpha_1.3.1.tar.gz  # [linux or win32]
  sha256: 707d72464c37726f4a067417d6a8927a232b59cf67fa77aa48eef8414ae29f5d  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/ddalpha_1.3.1.zip  # [win64]
  sha256: 83e1b3bdd57cfb84c9fb2d5855857582767785e635e8f2a55d5bf134bd845a99  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/ddalpha_1.3.1.tgz  # [osx]
  sha256: 707243b96e7b73c5440d3b02df2ddb0ab1c4d18f3097b2fdf49d2140e7eaf9f3  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{ compiler('fortran') }}    # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-bh
    - r-mass
    - r-rcpp >=0.11.0
    - r-class
    - r-robustbase
    - r-sfsmisc

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-bh
    - r-mass
    - r-rcpp >=0.11.0
    - r-class
    - r-robustbase
    - r-sfsmisc

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ddalpha')"           # [not win]
    - "\"%R%\" -e \"library('ddalpha')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=ddalpha
  license: GPL-2
  summary: Contains procedures for depth-based supervised learning, which are entirely non-parametric,
    in particular the DDalpha-procedure (Lange, Mosler and Mozharovskyi, 2014). The
    training data sample is transformed by a statistical depth function to a compact
    low-dimensional space, where the final classification is done. It also offers an
    extension to functional data and routines for calculating certain notions of statistical
    depth functions. 50 multivariate and 5 functional classification problems are included.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: ddalpha
# Type: Package
# Title: Depth-Based Classification and Calculation of Data Depth
# Version: 1.3.1
# Date: 2017-09-27
# Authors@R: c(person("Oleksii", "Pokotylo", role=c("aut", "cre"), email = "alexey.pokotylo@gmail.com"), person("Pavlo", "Mozharovskyi", role=c("aut"), email = "pavlo.mozharovskyi@ensai.fr"), person("Rainer", "Dyckerhoff", role=c("aut"), email = "rainer.dyckerhoff@statistik.uni-koeln.de"), person("Stanislav", "Nagy", role=c("aut"), email = "nagy@karlin.mff.cuni.cz"))
# SystemRequirements: C++11
# Depends: stats, utils, graphics, grDevices, MASS, class, robustbase, sfsmisc
# Imports: Rcpp (>= 0.11.0)
# LinkingTo: BH, Rcpp
# Description: Contains procedures for depth-based supervised learning, which are entirely non-parametric, in particular the DDalpha-procedure (Lange, Mosler and Mozharovskyi, 2014). The training data sample is transformed by a statistical depth function to a compact low-dimensional space, where the final classification is done. It also offers an extension to functional data and routines for calculating certain notions of statistical depth functions. 50 multivariate and 5 functional classification problems are included.
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2017-09-27 18:51:34 UTC; User
# Author: Oleksii Pokotylo [aut, cre], Pavlo Mozharovskyi [aut], Rainer Dyckerhoff [aut], Stanislav Nagy [aut]
# Maintainer: Oleksii Pokotylo <alexey.pokotylo@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-09-27 20:30:35 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
