{% set version = '1.3.4' %}  # [linux or win32]
{% set version = '1.3.4' %}  # [win64]
{% set version = '1.3.4' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ddalpha
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/ddalpha_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/ddalpha/ddalpha_{{ version }}.tar.gz  # [linux or win32]
  sha256: 41ba9952deb2e81713f2e308357d3b7adfe348135ba7e3c94c347db5e0029699  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/ddalpha_1.3.4.zip  # [win64]
  sha256: cbe6474523454cf91e86ca365ad0dddd3408af0add335d654672585e94e0acb7  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/ddalpha_1.3.4.tgz  # [osx]
  sha256: f79240b62b4f98d08b5b12b1291c2641564e7e5b116d32283ac78e6c50c55ba3  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux or osx]
    - {{ compiler('fortran') }}  # [linux or osx]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-bh
    - r-mass
    - r-rcpp >=0.11.0
    - r-class
    - r-geometry
    - r-robustbase
    - r-sfsmisc

  run:
    - mro-base
    - r-bh
    - r-mass
    - r-rcpp >=0.11.0
    - r-class
    - r-geometry
    - r-robustbase
    - r-sfsmisc

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ddalpha')"           # [not win]
    - "\"%R%\" -e \"library('ddalpha')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=ddalpha
  license: GPL-2
  summary: Contains procedures for depth-based supervised learning, which are entirely non-parametric,
    in particular the DDalpha-procedure (Lange, Mosler and Mozharovskyi, 2014 <doi:10.1007/s00362-012-0488-4>).
    The training data sample is transformed by a statistical depth function to a compact
    low-dimensional space, where the final classification is done. It also offers an
    extension to functional data and routines for calculating certain notions of statistical
    depth functions. 50 multivariate and 5 functional classification problems are included.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: ddalpha
# Type: Package
# Title: Depth-Based Classification and Calculation of Data Depth
# Version: 1.3.4
# Date: 2018-06-22
# Authors@R: c(person("Oleksii", "Pokotylo", role=c("aut", "cre"), email = "alexey.pokotylo@gmail.com"), person("Pavlo", "Mozharovskyi", role=c("aut"), email = "pavlo.mozharovskyi@ensai.fr"), person("Rainer", "Dyckerhoff", role=c("aut"), email = "rainer.dyckerhoff@statistik.uni-koeln.de"), person("Stanislav", "Nagy", role=c("aut"), email = "nagy@karlin.mff.cuni.cz"))
# SystemRequirements: C++11
# Depends: R (>= 2.10), stats, utils, graphics, grDevices, MASS, class, robustbase, sfsmisc, geometry
# Imports: Rcpp (>= 0.11.0)
# LinkingTo: BH, Rcpp
# Description: Contains procedures for depth-based supervised learning, which are entirely non-parametric, in particular the DDalpha-procedure (Lange, Mosler and Mozharovskyi, 2014 <doi:10.1007/s00362-012-0488-4>). The training data sample is transformed by a statistical depth function to a compact low-dimensional space, where the final classification is done. It also offers an extension to functional data and routines for calculating certain notions of statistical depth functions. 50 multivariate and 5 functional classification problems are included.
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2018-06-22 13:03:25 UTC; pavlo.mozharovskyi
# Author: Oleksii Pokotylo [aut, cre], Pavlo Mozharovskyi [aut], Rainer Dyckerhoff [aut], Stanislav Nagy [aut]
# Maintainer: Oleksii Pokotylo <alexey.pokotylo@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-06-23 16:08:17 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
