{% set version = '2.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-visnetwork
  version: {{ version|replace("-", "_") }}

source:
  fn: visNetwork_2.0.2.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/visNetwork_2.0.2.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/visNetwork/visNetwork_2.0.2.tar.gz  # [linux or win32]
  sha256: fb959f48519f294788171aed3689bd055a9c402abc8ecf0e51e3f23451946134  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/visNetwork_2.0.2.zip  # [win64]
  sha256: 2ca7782f307356aba2897955512495067e5222b0a83c028ef487bf8a786c8db5  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/visNetwork_2.0.2.tgz  # [osx]
  sha256: 270a72b1d203e891226a41df65ec293c8976fdf038aecf7fe4bda01613777d68  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, igraph, rpart, shiny, shinyWidgets, colourpicker, sparkline, ggraph, flashClust
requirements:
  build:

  host:
    - mro-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr

  run:
    - mro-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('visNetwork')"           # [not win]
    - "\"%R%\" -e \"library('visNetwork')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://datastorm-open.github.io/visNetwork/
  license: MIT + file LICENSE
  summary: Provides an R interface to the 'vis.js' JavaScript charting library. It allows an
    interactive visualization of networks.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: visNetwork
# Title: Network Visualization using 'vis.js' Library
# Version: 2.0.2
# Date: 2017-12-18
# Authors@R: c( person(family = "Almende B.V.", role = c("aut", "cph"), comment = "vis.js library in htmlwidgets/lib, http://visjs.org, http://www.almende.com/home"), person("Benoit", "Thieurmel", role = c("aut", "cre"), comment = "R interface", email = "benoit.thieurmel@datastorm.fr"), person(given = "Titouan", family = "Robert",  email = "titouan.robert@datastorm.fr", role = c("aut", "ctb")) )
# Maintainer: Benoit Thieurmel <benoit.thieurmel@datastorm.fr>
# Description: Provides an R interface to the 'vis.js' JavaScript charting library. It allows an interactive visualization of networks.
# BugReports: https://github.com/datastorm-open/visNetwork/issues
# URL: http://datastorm-open.github.io/visNetwork/
# Depends: R (>= 3.0)
# Imports: htmlwidgets, htmltools, jsonlite, magrittr, utils, methods, grDevices, stats
# License: MIT + file LICENSE
# Suggests: knitr, igraph, rpart, shiny, shinyWidgets, colourpicker, sparkline, ggraph, flashClust
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-12-19 08:07:24 UTC; Datastorm
# Author: Almende B.V. [aut, cph] (vis.js library in htmlwidgets/lib, http://visjs.org, http://www.almende.com/home), Benoit Thieurmel [aut, cre] (R interface), Titouan Robert [aut, ctb]
# Repository: CRAN
# Date/Publication: 2017-12-19 20:29:33 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
