{% set version = '0.4.6.1' %}  # [linux or win32 or osx]
{% set version = '0.4.6.1' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rlist
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/rlist_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/rlist/rlist_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: bb0148b124997aa4e1c89c6c7cf45927afaf5b23caefcdc5116cfa7caef05c21  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/rlist_0.4.6.1.zip  # [win64]
  sha256: a9c31bc190eb66700065560a8d0cc6ea9bb1ee9de17503328ee45ba2be1756a9  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, stringdist, pipeR
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-xml
    - r-data.table
    - r-jsonlite
    - r-yaml

  run:
    - mro-base
    - r-xml
    - r-data.table
    - r-jsonlite
    - r-yaml

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rlist')"           # [not win]
    - "\"%R%\" -e \"library('rlist')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://renkun.me/rlist, https://github.com/renkun-ken/rlist, https://renkun.me/rlist-tutorial
  license: MIT + file LICENSE
  summary: Provides a set of functions for data manipulation with list objects, including mapping,
    filtering, grouping, sorting, updating, searching, and other useful functions. Most
    functions are designed to be pipeline friendly so that data processing with lists
    can be chained.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rlist
# Type: Package
# Title: A Toolbox for Non-Tabular Data Manipulation
# Version: 0.4.6.1
# Author: Kun Ren <ken@renkun.me>
# Maintainer: Kun Ren <ken@renkun.me>
# Description: Provides a set of functions for data manipulation with list objects, including mapping, filtering, grouping, sorting, updating, searching, and other useful functions. Most functions are designed to be pipeline friendly so that data processing with lists can be chained.
# Depends: R (>= 2.15)
# Date: 2016-04-04
# Suggests: testthat, stringdist, pipeR
# Imports: yaml, jsonlite, XML, data.table
# License: MIT + file LICENSE
# URL: https://renkun.me/rlist, https://github.com/renkun-ken/rlist, https://renkun.me/rlist-tutorial
# BugReports: https://github.com/renkun-ken/rlist/issues
# ByteCompile: TRUE
# LazyData: true
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-04-04 08:55:10 UTC; Kun
# Repository: CRAN
# Date/Publication: 2016-04-04 11:49:36

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
