{% set version = '0.3.0' %}  # [linux or win32 or osx]
{% set version = '0.3.0' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-viridislite
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/viridisLite_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/viridisLite/viridisLite_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 780ea12e7c4024d5ba9029f3a107321c74b8d6d9165262f6e64b79e00aa0c2af  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/viridisLite_0.3.0.zip  # [win64]
  sha256: bd9040343abd6ebef73f4bc33186db2c4d10ca05bc290194e3e4d5c3998fb61f  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: hexbin (>= 1.27.0), ggplot2 (>= 1.0.1), testthat, covr
requirements:
  build:
    - {{native}}rtools           # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('viridisLite')"           # [not win]
    - "\"%R%\" -e \"library('viridisLite')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/sjmgarnier/viridisLite
  license: MIT + file LICENSE
  summary: "Implementation of the 'viridis' - the default -, 'magma', 'plasma',  'inferno', and
    'cividis' color maps for 'R'. 'viridis', 'magma', 'plasma',  and 'inferno' are ported
    from 'matplotlib' <http://matplotlib.org/>, a  popular plotting library for 'python'.
    'cividis', was developed by Jamie R.  Nu\xF1ez and Sean M. Colby. These color maps
    are designed in such a way that  they will analytically be perfectly perceptually-uniform,
    both in regular  form and also when converted to black-and-white. They are also
    designed to  be perceived by readers with the most common form of color blindness
    (all  color maps in this package) and color vision deficiency ('cividis' only).
    \ This is the 'lite' version of the more complete 'viridis' package that can  be
    found at <https://cran.r-project.org/package=viridis>."

  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: viridisLite
# Type: Package
# Title: Default Color Maps from 'matplotlib' (Lite Version)
# Version: 0.3.0
# Authors@R: c( person("Simon", "Garnier", email = "garnier@njit.edu", role = c("aut", "cre")), person("Noam", "Ross", email = "noam.ross@gmail.com", role = c("ctb", "cph")), person("Bob", "Rudis", email = "bob@rud.is", role = c("ctb", "cph")), person("Marco", "Sciaini", email = "sciaini.marco@gmail.com", role = c("ctb", "cph")), person("Cedric", "Scherer", email = "scherer@izw-berlin.de", role = c("ctb", "cph")) )
# Maintainer: Simon Garnier <garnier@njit.edu>
# Description: Implementation of the 'viridis' - the default -, 'magma', 'plasma',  'inferno', and 'cividis' color maps for 'R'. 'viridis', 'magma', 'plasma',  and 'inferno' are ported from 'matplotlib' <http://matplotlib.org/>, a  popular plotting library for 'python'. 'cividis', was developed by Jamie R.  Nunez and Sean M. Colby. These color maps are designed in such a way that  they will analytically be perfectly perceptually-uniform, both in regular  form and also when converted to black-and-white. They are also designed to  be perceived by readers with the most common form of color blindness (all  color maps in this package) and color vision deficiency ('cividis' only).  This is the 'lite' version of the more complete 'viridis' package that can  be found at <https://cran.r-project.org/package=viridis>.
# License: MIT + file LICENSE
# LazyData: TRUE
# Encoding: UTF-8
# Depends: R (>= 2.10)
# Suggests: hexbin (>= 1.27.0), ggplot2 (>= 1.0.1), testthat, covr
# URL: https://github.com/sjmgarnier/viridisLite
# BugReports: https://github.com/sjmgarnier/viridisLite/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-02-01 17:33:56 UTC; simon
# Author: Simon Garnier [aut, cre], Noam Ross [ctb, cph], Bob Rudis [ctb, cph], Marco Sciaini [ctb, cph], Cedric Scherer [ctb, cph]
# Repository: CRAN
# Date/Publication: 2018-02-01 22:45:56 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
