{% set version = '0.2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-viridislite
  version: {{ version|replace("-", "_") }}

source:
  fn: viridisLite_0.2.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/viridisLite_0.2.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/viridisLite/viridisLite_0.2.0.tar.gz  # [linux or win32]
  sha256: 2d4d909f21c51e720bd685f05041ba158294e0a4064e0946d0bd916709818694  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/viridisLite_0.2.0.zip  # [win64]
  sha256: 5b32b3126b5966f508cf522f0dd4343ed1fea5b7f0b7945e5491f023d26f18c2  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/viridisLite_0.2.0.tgz  # [osx]
  sha256: cf597d68c5ef26e4fb71bab2b693e2a52f590dc44c9d1804d5c16f4a7e4aafdd  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: hexbin (>= 1.27.0), ggplot2 (>= 1.0.1), testthat, covr
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('viridisLite')"           # [not win]
    - "\"%R%\" -e \"library('viridisLite')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/sjmgarnier/viridisLite
  license: MIT + file LICENSE
  summary: Port of the new 'matplotlib' color maps ('viridis' - the default -, 'magma', 'plasma'
    and 'inferno') to 'R'. 'matplotlib' <http://matplotlib.org/ > is a popular plotting
    library for 'python'. These color maps are designed in such a way that they will
    analytically be perfectly perceptually-uniform, both in regular form and also when
    converted to black-and-white. They are also designed to be perceived by readers
    with the most common form of color blindness. This is the 'lite' version of the
    more complete 'viridis' package that can be found at <https://cran.r-project.org/package=viridis>.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: viridisLite
# Type: Package
# Title: Default Color Maps from 'matplotlib' (Lite Version)
# Version: 0.2.0
# Authors@R: c( person("Simon", "Garnier", email = "garnier@njit.edu", role = c("aut", "cre")), person("Noam", "Ross", email = "noam.ross@gmail.com", role = c("ctb", "cph")), person("Bob", "Rudis", email = "bob@rud.is", role = c("ctb", "cph")) )
# Maintainer: Simon Garnier <garnier@njit.edu>
# Description: Port of the new 'matplotlib' color maps ('viridis' - the default -, 'magma', 'plasma' and 'inferno') to 'R'. 'matplotlib' <http://matplotlib.org/ > is a popular plotting library for 'python'. These color maps are designed in such a way that they will analytically be perfectly perceptually-uniform, both in regular form and also when converted to black-and-white. They are also designed to be perceived by readers with the most common form of color blindness. This is the 'lite' version of the more complete 'viridis' package that can be found at <https://cran.r-project.org/package=viridis>.
# License: MIT + file LICENSE
# LazyData: TRUE
# Encoding: UTF-8
# Depends: R (>= 2.10)
# Suggests: hexbin (>= 1.27.0), ggplot2 (>= 1.0.1), testthat, covr
# URL: https://github.com/sjmgarnier/viridisLite
# BugReports: https://github.com/sjmgarnier/viridisLite/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-03-23 21:36:52 UTC; simon
# Author: Simon Garnier [aut, cre], Noam Ross [ctb, cph], Bob Rudis [ctb, cph]
# Repository: CRAN
# Date/Publication: 2017-03-24 05:37:14 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
