{% set version = '0.1.1' %}  # [linux or win32 or osx]
{% set version = '0.1.1' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modelr
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/modelr_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/modelr/modelr_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 25b95198d6aa23e28a0bd97dcdc78264ef168ae403928bff01e1ee81ca021ce7  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/modelr_0.1.1.zip  # [win64]
  sha256: 00201685751d35cd90835aad3a9529e2958a8ed7123c51cdbe2f1aaef5dc76d8  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, ggplot2, covr, compiler
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-broom
    - r-dplyr
    - r-lazyeval >=0.2.0
    - r-magrittr
    - r-purrr >=0.2.2
    - r-tibble
    - r-tidyr >=0.6.0

  run:
    - mro-base
    - r-broom
    - r-dplyr
    - r-lazyeval >=0.2.0
    - r-magrittr
    - r-purrr >=0.2.2
    - r-tibble
    - r-tidyr >=0.6.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('modelr')"           # [not win]
    - "\"%R%\" -e \"library('modelr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/modelr
  license: GPL-3
  summary: Functions for modelling that help you seamlessly integrate modelling into a pipeline
    of data manipulation and visualisation.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: modelr
# Version: 0.1.1
# Title: Modelling Functions that Work with the Pipe
# Description: Functions for modelling that help you seamlessly integrate modelling into a pipeline of data manipulation and visualisation.
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph") )
# License: GPL-3
# LazyData: true
# Depends: R (>= 3.1.0)
# Imports: magrittr, purrr (>= 0.2.2), lazyeval (>= 0.2.0), tibble, broom, dplyr, tidyr (>= 0.6.0)
# Suggests: testthat, ggplot2, covr, compiler
# URL: https://github.com/hadley/modelr
# BugReports: https://github.com/hadley/modelr/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-07-22 21:47:57 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-07-24 18:28:20 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
