{% set version = '0.1.2' %}  # [linux or win32 or osx]
{% set version = '0.1.2' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modelr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/modelr_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/modelr/modelr_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 6a9831c510967551a6064716dfd4db48b59dc056dcf1c7f1d2cce05ef0789027  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/modelr_0.1.2.zip  # [win64]
  sha256: 7cdfdc523eaff77c81152d54206e0dc1b6cf2bc4974bbb9fa1e6bb2b9077b172  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: compiler, covr, ggplot2, testthat
requirements:
  build:
    - {{native}}rtools           # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-broom
    - r-dplyr
    - r-magrittr
    - r-purrr >=0.2.2
    - r-rlang >=0.2.0
    - r-tibble
    - r-tidyr >=0.8.0

  run:
    - mro-base
    - r-broom
    - r-dplyr
    - r-magrittr
    - r-purrr >=0.2.2
    - r-rlang >=0.2.0
    - r-tibble
    - r-tidyr >=0.8.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('modelr')"           # [not win]
    - "\"%R%\" -e \"library('modelr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://modelr.tidyverse.org, https://github.com/hadley/modelr
  license: GPL-3
  summary: Functions for modelling that help you seamlessly integrate modelling into a pipeline
    of data manipulation and visualisation.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: modelr
# Title: Modelling Functions that Work with the Pipe
# Version: 0.1.2
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph") )
# Description: Functions for modelling that help you seamlessly integrate modelling into a pipeline of data manipulation and visualisation.
# License: GPL-3
# URL: https://modelr.tidyverse.org, https://github.com/hadley/modelr
# BugReports: https://github.com/hadley/modelr/issues
# Depends: R (>= 3.1)
# Imports: broom, dplyr, magrittr, purrr (>= 0.2.2), tibble, tidyr (>= 0.8.0), rlang (>= 0.2.0)
# Suggests: compiler, covr, ggplot2, testthat
# LazyData: true
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-05-10 22:54:13 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-05-11 03:23:27 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
