{% set version = '2.0-9' %}  # [linux or win32 or osx]
{% set version = '2.0-9' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-uroot
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/uroot_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/uroot/uroot_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 9b7616d64ed87b29ee45368bf7f08d15c0ec058e450c69171fbfecb44943ac5b  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/uroot_2.0-9.zip  # [win64]
  sha256: 5ef1d3bac2d39e91c42e3f16c754e7e51be42a857db2ca5f5d5e303a7a4d9c73  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{ compiler('cxx') }}      # [linux or osx]
    - {{native}}rtools           # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('uroot')"           # [not win]
    - "\"%R%\" -e \"library('uroot')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://jalobe.com
  license: GPL-2
  summary: Seasonal unit roots and seasonal stability tests. P-values based on response surface
    regressions are available for both tests. P-values based on bootstrap are available
    for seasonal unit root tests. A parallel implementation of the bootstrap method
    requires a CUDA capable GPU  with compute capability >= 3.0, otherwise a debugging
    version fully coded in R is used.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: uroot
# Version: 2.0-9
# Date: 2017-01-27
# Title: Unit Root Tests for Seasonal Time Series
# Author: Javier Lopez-de-Lacalle <javlacalle@yahoo.es>
# Maintainer: Javier Lopez-de-Lacalle <javlacalle@yahoo.es>
# Depends: R (>= 3.0.0), stats
# SystemRequirements: nvcc (release >= 7.1) (NVIDIA Cuda Compiler driver)
# Encoding: UTF-8
# Description: Seasonal unit roots and seasonal stability tests. P-values based on response surface regressions are available for both tests. P-values based on bootstrap are available for seasonal unit root tests. A parallel implementation of the bootstrap method requires a CUDA capable GPU  with compute capability >= 3.0, otherwise a debugging version fully coded in R is used.
# NeedsCompilation: yes
# LazyData: yes
# LazyDataCompression: xz
# License: GPL-2
# URL: https://jalobe.com
# Packaged: 2017-01-27 19:58:17 UTC; javlacalle
# Repository: CRAN
# Date/Publication: 2017-01-29 16:25:31

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
