{% set version = '0.2-2' %}  # [linux or win32]
{% set version = '0.2-2' %}  # [win64]
{% set version = '0.2-2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cvst
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/CVST_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/CVST/CVST_{{ version }}.tar.gz  # [linux or win32]
  sha256: 854b8c983427ecf9f2f7798c4fd1c1d06762b5b0bcb1045502baadece6f78316  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/CVST_0.2-2.zip  # [win64]
  sha256: 86e0b2e7d99f91305c1149a9bd9bdf1a8b86afa4e0894aa157566bf809a8f24a  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/CVST_0.2-2.tgz  # [osx]
  sha256: d38532f0d0ae23c8f313398eb76902a1bed181eec714244ae5074449f2ab67e5  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-matrix
    - r-kernlab

  run:
    - mro-base
    - r-matrix
    - r-kernlab

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('CVST')"           # [not win]
    - "\"%R%\" -e \"library('CVST')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=CVST
  license: GPL (>= 2.0)
  summary: The fast cross-validation via sequential testing (CVST) procedure is an improved cross-validation
    procedure which uses non-parametric testing coupled with sequential analysis to
    determine the best parameter set on linearly increasing subsets of the data. By
    eliminating under-performing candidates quickly and keeping promising candidates
    as long as possible, the method speeds up the computation while preserving the capability
    of a full cross-validation. Additionally to the CVST the package contains an implementation
    of the ordinary k-fold cross-validation with a flexible and powerful set of helper
    objects and methods to handle the overall model selection process. The implementations
    of the Cochran's Q test with permutations and the sequential testing framework of
    Wald are generic and can therefore also be used in other contexts.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: CVST
# Type: Package
# Title: Fast Cross-Validation via Sequential Testing
# Version: 0.2-2
# Date: 2018-05-26
# Depends: kernlab,Matrix
# Author: Tammo Krueger, Mikio Braun
# Maintainer: Tammo Krueger <tammokrueger@googlemail.com>
# Description: The fast cross-validation via sequential testing (CVST) procedure is an improved cross-validation procedure which uses non-parametric testing coupled with sequential analysis to determine the best parameter set on linearly increasing subsets of the data. By eliminating under-performing candidates quickly and keeping promising candidates as long as possible, the method speeds up the computation while preserving the capability of a full cross-validation. Additionally to the CVST the package contains an implementation of the ordinary k-fold cross-validation with a flexible and powerful set of helper objects and methods to handle the overall model selection process. The implementations of the Cochran's Q test with permutations and the sequential testing framework of Wald are generic and can therefore also be used in other contexts.
# License: GPL (>= 2.0)
# NeedsCompilation: no
# Packaged: 2018-05-26 15:38:02 UTC; tammok
# Repository: CRAN
# Date/Publication: 2018-05-26 22:01:57 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
