{% set version = '0.1.1' %}  # [linux or win32]
{% set version = '0.1.1' %}  # [win64]
{% set version = '0.1.1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bindr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/bindr_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/bindr/bindr_{{ version }}.tar.gz  # [linux or win32]
  sha256: 7c785ca77ceb3ab9282148bcecf64d1857d35f5b800531d49483622fe67505d0  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/bindr_0.1.1.zip  # [win64]
  sha256: 6cd7ece2b1ee83d857fd0961cf16a2ae4e07a598a57d88d2369dfb423ac37d37  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/bindr_0.1.1.tgz  # [osx]
  sha256: f015959bf69fc5955824a74b50308367e696014a24e2700bc316d980d80c5ddd  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base
    - libcxx >=4.0.1             # [osx]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bindr')"           # [not win]
    - "\"%R%\" -e \"library('bindr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/krlmlr/bindr, https://krlmlr.github.io/bindr
  license: MIT + file LICENSE
  summary: Provides a simple interface for creating active bindings where the bound function
    accepts additional arguments.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: bindr
# Title: Parametrized Active Bindings
# Version: 0.1.1
# Authors@R: c( person("Kirill", "M\u00fcller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org", comment = c(ORCID = "0000-0002-1416-3412")), person("RStudio", role = c("cph", "fnd")) )
# Description: Provides a simple interface for creating active bindings where the bound function accepts additional arguments.
# Suggests: testthat
# LazyData: true
# Date: 2018-03-13
# BugReports: https://github.com/krlmlr/bindr/issues
# URL: https://github.com/krlmlr/bindr, https://krlmlr.github.io/bindr
# RoxygenNote: 6.0.1.9000
# License: MIT + file LICENSE
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2018-03-13 00:31:30 UTC; muelleki
# Author: Kirill Muller [aut, cre] (<https://orcid.org/0000-0002-1416-3412>), RStudio [cph, fnd]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2018-03-13 08:21:23 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
