{% set version = '1.11.2' %}  # [linux or win32 or osx]
{% set version = '1.11.2' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmltable
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/htmlTable_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/htmlTable/htmlTable_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 64a273b1cdf07a7c57b9031315ca665f95d78e70b4320d020f64a139278877d1  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/htmlTable_1.11.2.zip  # [win64]
  sha256: da782386eed595bedfb647d47019499fb6ef4dfa8e3cb06df7d114d4f98291e5  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, XML, xtable, ztable, Hmisc, reshape, rmarkdown, pander, chron, lubridate, tibble, tidyr (>= 0.7.2), dplyr (>= 0.7.4)
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-checkmate
    - r-htmltools
    - r-htmlwidgets
    - r-knitr >=1.6
    - r-magrittr >=1.5
    - r-rstudioapi >=0.6
    - r-stringr

  run:
    - mro-base
    - r-checkmate
    - r-htmltools
    - r-htmlwidgets
    - r-knitr >=1.6
    - r-magrittr >=1.5
    - r-rstudioapi >=0.6
    - r-stringr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('htmlTable')"           # [not win]
    - "\"%R%\" -e \"library('htmlTable')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://gforge.se/packages/
  license: GPL (>= 3)
  summary: Tables with state-of-the-art layout elements such as row spanners, column spanners,
    table spanners, zebra striping, and more. While allowing advanced layout, the underlying
    css-structure is simple in order to maximize compatibility with word processors
    such as 'MS Word' or 'LibreOffice'. The package also contains a few text formatting
    functions that help outputting text compatible with HTML/'LaTeX'.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: htmlTable
# Version: 1.11.2
# Date: 2018-01-20
# Title: Advanced Tables for Markdown/HTML
# Authors@R: c( person("Max", "Gordon", email = "max@gforge.se", role = c("aut", "cre")), person("Stephen", "Gragg", role=c("aut")), person("Peter", "Konings", role=c("aut")))
# Maintainer: Max Gordon <max@gforge.se>
# Description: Tables with state-of-the-art layout elements such as row spanners, column spanners, table spanners, zebra striping, and more. While allowing advanced layout, the underlying css-structure is simple in order to maximize compatibility with word processors such as 'MS Word' or 'LibreOffice'. The package also contains a few text formatting functions that help outputting text compatible with HTML/'LaTeX'.
# License: GPL (>= 3)
# URL: http://gforge.se/packages/
# BugReports: https://github.com/gforge/htmlTable/issues
# Biarch: yes
# Imports: stringr, knitr (>= 1.6), magrittr (>= 1.5), methods, checkmate, htmlwidgets, htmltools, rstudioapi (>= 0.6)
# Suggests: testthat, XML, xtable, ztable, Hmisc, reshape, rmarkdown, pander, chron, lubridate, tibble, tidyr (>= 0.7.2), dplyr (>= 0.7.4)
# Encoding: UTF-8
# NeedsCompilation: no
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# Packaged: 2018-01-20 14:03:06 UTC; Max
# Author: Max Gordon [aut, cre], Stephen Gragg [aut], Peter Konings [aut]
# Repository: CRAN
# Date/Publication: 2018-01-20 15:30:21 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
