{% set version = '0.6.1' %}  # [linux or win32]
{% set version = '0.6.1' %}  # [win64]
{% set version = '0.6.1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xlsxjars
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/xlsxjars_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/xlsxjars/xlsxjars_{{ version }}.tar.gz  # [linux or win32]
  sha256: 37c1517f95f8bca6e3514429394d2457b9e62383305eba288416fb53ab2e6ae6  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/xlsxjars_0.6.1.zip  # [win64]
  sha256: 8f87ea3893e3a7a1ab28b1ae9a62354eebd81780169f710cbc73ec13e9f337e2  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/xlsxjars_0.6.1.tgz  # [osx]
  sha256: 16a466f814c4a12e475aee7f8fcce5fa4d353ec41d2b0fc7994eaed01d81f931  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-rjava

  run:
    - mro-base
    - r-rjava

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('xlsxjars')"           # [not win]
    - "\"%R%\" -e \"library('xlsxjars')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=xlsxjars
  license: GPL-3
  summary: The xlsxjars package collects all the external jars required for the xlxs package.
    This release corresponds to POI 3.10.1.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: xlsxjars
# Type: Package
# Title: Package required POI jars for the xlsx package
# Version: 0.6.1
# Date: 2014-08-21
# Depends: rJava
# LazyLoad: yes
# Authors@R: c(person(c("Adrian", "A."), "Dragulescu",  role = c("aut", "cre"), email = "adrian.dragulescu@gmail.com"),  person("The Apache Software Foundation",  role = c("ctb", "cph"),  comment = "Apache POI, Apache XMLBeans", "Apache Commons Codec"),  person("MetaStuff, Ltd.",  role = c("ctb", "cph"), comment = "Dom4j"))
# Description: The xlsxjars package collects all the external jars required for the xlxs package. This release corresponds to POI 3.10.1.
# License: GPL-3
# Copyright: See file COPYRIGHTS
# NeedsCompilation: no
# Repository: CRAN
# Packaged: 2014-08-21 21:18:37 UTC; adrian
# Author: Adrian A. Dragulescu [aut, cre], The Apache Software Foundation Apache Commons Codec [ctb, cph] (Apache POI, Apache XMLBeans), MetaStuff, Ltd. [ctb, cph] (Dom4j)
# Maintainer: Adrian A. Dragulescu <adrian.dragulescu@gmail.com>
# Date/Publication: 2014-08-22 07:19:16

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
