{% set version = '0.1.7' %}  # [linux or win32]
{% set version = '0.1.7' %}  # [win64]
{% set version = '0.1.7' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sourcetools
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/sourcetools_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/sourcetools/sourcetools_{{ version }}.tar.gz  # [linux or win32]
  sha256: 47984406efb3b3face133979ccbae9fefb7360b9a6ca1a1c11473681418ed2ca  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/sourcetools_0.1.7.zip  # [win64]
  sha256: 86f84b034a3fd42becd1d6f5305f1fc990add71a9ac850b7d005c146ed38a474  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/sourcetools_0.1.7.tgz  # [osx]
  sha256: 637f4fc196b3779eff37eb06c2ae9090deddf5378108e3e41d39a44eff78447b  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux or osx]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sourcetools')"           # [not win]
    - "\"%R%\" -e \"library('sourcetools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=sourcetools
  license: MIT + file LICENSE
  summary: Tools for the reading and tokenization of R code. The 'sourcetools' package provides
    both an R and C++ interface for the tokenization of R code, and helpers for interacting
    with the tokenized representation of R code.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: sourcetools
# Type: Package
# Title: Tools for Reading, Tokenizing and Parsing R Code
# Version: 0.1.7
# Author: Kevin Ushey
# Maintainer: Kevin Ushey <kevinushey@gmail.com>
# Description: Tools for the reading and tokenization of R code. The 'sourcetools' package provides both an R and C++ interface for the tokenization of R code, and helpers for interacting with the tokenized representation of R code.
# License: MIT + file LICENSE
# LazyData: TRUE
# Depends: R (>= 3.0.2)
# Suggests: testthat
# RoxygenNote: 5.0.1
# BugReports: https://github.com/kevinushey/sourcetools/issues
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2018-04-25 03:19:22 UTC; kevin
# Repository: CRAN
# Date/Publication: 2018-04-25 03:38:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
