{% set version = '0.4.2' %}  # [linux or win32]
{% set version = '0.4.2' %}  # [win64]
{% set version = '0.4.2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gistr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/gistr_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/gistr/gistr_{{ version }}.tar.gz  # [linux or win32]
  sha256: 43c00c7f565732125f45f6c067724771ba1b337d6dd3a6e301639fe16e11032e  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/gistr_0.4.2.zip  # [win64]
  sha256: 717f40d316eefb897ef50d7c5c531c34bc76054bb54d0e5707f800ab3b0ab2af  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/gistr_0.4.2.tgz  # [osx]
  sha256: d5ed1d9f197b49e406dc83b1de7a793bc1bf8cc8c7aafb8b15e30eb3159cf9a9  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: git2r, testthat
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-assertthat
    - r-dplyr
    - r-httr >=1.2.0
    - r-jsonlite >=1.4
    - r-knitr
    - r-magrittr
    - r-rmarkdown

  run:
    - mro-base
    - r-assertthat
    - r-dplyr
    - r-httr >=1.2.0
    - r-jsonlite >=1.4
    - r-knitr
    - r-magrittr
    - r-rmarkdown

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gistr')"           # [not win]
    - "\"%R%\" -e \"library('gistr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropensci/gistr
  license: MIT + file LICENSE
  summary: 'Work with ''GitHub'' ''gists'' from ''R'' (e.g.,  <http://en.wikipedia.org/wiki/GitHub#Gist>,  <https://help.github.com/articles/about-gists/>).
    A ''gist'' is simply one or more files with code/text/images/etc. This package allows
    the user to create new ''gists'', update ''gists'' with new files, rename files,
    delete files, get and delete ''gists'', star and ''un-star'' ''gists'', fork ''gists'',
    open a ''gist'' in your default browser, get embed code for a ''gist'', list ''gist''
    ''commits'', and get rate limit information when ''authenticated''. Some requests
    require authentication and some do not. ''Gists'' website:  <https://gist.github.com/>.'

  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: gistr
# Title: Work with 'GitHub' 'Gists'
# Description: Work with 'GitHub' 'gists' from 'R' (e.g.,  <http://en.wikipedia.org/wiki/GitHub#Gist>,  <https://help.github.com/articles/about-gists/>). A 'gist' is simply one or more files with code/text/images/etc. This package allows the user to create new 'gists', update 'gists' with new files, rename files, delete files, get and delete 'gists', star and 'un-star' 'gists', fork 'gists', open a 'gist' in your default browser, get embed code for a 'gist', list 'gist' 'commits', and get rate limit information when 'authenticated'. Some requests require authentication and some do not. 'Gists' website:  <https://gist.github.com/>.
# Version: 0.4.2
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut", "cre"),  email = "myrmecocystus@gmail.com",  comment = c(ORCID="0000-0003-1444-9135")), person("Ramnath", "Vaidyanathan", role = "aut"), person("Karthik", "Ram", role = "aut") )
# License: MIT + file LICENSE
# URL: https://github.com/ropensci/gistr
# BugReports: https://github.com/ropensci/gistr/issues
# VignetteBuilder: knitr
# Imports: jsonlite (>= 1.4), httr (>= 1.2.0), magrittr, assertthat, knitr, rmarkdown, dplyr
# Suggests: git2r, testthat
# RoxygenNote: 6.0.1
# X-schema.org-applicationCategory: Web
# X-schema.org-keywords: http, https, API, web-services, GitHub, GitHub API, gist, gists, code, script, snippet
# X-schema.org-isPartOf: https://ropensci.org
# NeedsCompilation: no
# Packaged: 2018-06-27 22:31:37 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>), Ramnath Vaidyanathan [aut], Karthik Ram [aut]
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-06-28 05:05:47 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
