{% set version = '0.0-24' %}  # [linux or win32 or osx]
{% set version = '0.0-24' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tkrplot
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/tkrplot_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/tkrplot/tkrplot_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 2873630a37d7ae1e09a5803d9a89ca0494edd83526c7b1860d9246543722f311  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/tkrplot_0.0-24.zip  # [win64]
  sha256: 0d785e38071150d0e8d14bf591dffd852fe98c4eedf7f9eae55ed1f9e4247504  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{native}}rtools           # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tkrplot')"           # [not win]
    - "\"%R%\" -e \"library('tkrplot')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=tkrplot
  license: GPL
  summary: Simple mechanism for placing R graphics in a Tk widget.
  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tkrplot
# Version: 0.0-24
# Author: Luke Tierney <luke-tierney@uiowa.edu>
# Description: Simple mechanism for placing R graphics in a Tk widget.
# Title: TK Rplot
# Depends: R (>= 2.13), grDevices, tcltk
# License: GPL
# Maintainer: Luke Tierney <luke-tierney@uiowa.edu>
# NeedsCompilation: yes
# Packaged: 2018-07-19 15:46:12 UTC; luke
# Repository: CRAN
# Date/Publication: 2018-07-19 20:40:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
