{% set version = '0.7.1' %}  # [linux or win32 or osx]
{% set version = '0.7.1' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-later
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/later_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/later/later_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 7fe7f7e39a59e201f41adfdd6487d5e1976af5331735171efb094fca6af5327d  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/later_0.7.1.zip  # [win64]
  sha256: 118a9e703532b33389b29d9f4d2de72ab87d762261eb3bfed7a9b875cf7a82bf  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{ compiler('cxx') }}      # [linux or osx]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32 or osx]
    - {{posix}}sed               # [win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-bh
    - r-rcpp >=0.12.9
    - r-rlang

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-bh
    - r-rcpp >=0.12.9
    - r-rlang

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('later')"           # [not win]
    - "\"%R%\" -e \"library('later')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/later
  license: GPL (>= 2)
  summary: Executes arbitrary R or C functions some time after the current time, after the R
    execution stack has emptied.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: later
# Type: Package
# Title: Utilities for Delaying Function Execution
# Version: 0.7.1
# Authors@R: c( person("Joe", "Cheng", role = c("aut", "cre"), email = "joe@rstudio.com"), person(family = "RStudio", role = "cph"), person("Marcus", "Geelnard", role = c("ctb", "cph"), comment = "TinyCThread library, https://tinycthread.github.io/"), person("Evan", "Nemerson", role = c("ctb", "cph"), comment = "TinyCThread library, https://tinycthread.github.io/") )
# Description: Executes arbitrary R or C functions some time after the current time, after the R execution stack has emptied.
# URL: https://github.com/r-lib/later
# BugReports: https://github.com/r-lib/later/issues
# License: GPL (>= 2)
# Imports: Rcpp (>= 0.12.9), rlang
# LinkingTo: Rcpp, BH
# RoxygenNote: 6.0.1
# Suggests: knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2018-03-01 21:02:42 UTC; jcheng
# Author: Joe Cheng [aut, cre], RStudio [cph], Marcus Geelnard [ctb, cph] (TinyCThread library, https://tinycthread.github.io/), Evan Nemerson [ctb, cph] (TinyCThread library, https://tinycthread.github.io/)
# Maintainer: Joe Cheng <joe@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-03-07 11:13:08 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
