{% set version = '0.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-later
  version: {{ version|replace("-", "_") }}

source:
  fn: later_0.6.tar.gz  # [linux or win32 or osx]
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/later_0.6.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/later/later_0.6.tar.gz  # [linux or win32 or osx]
  sha256: 1da27b5397f13e0d7dedca42e52fc60848cd6657a96f20b35d5746f3dddff8f4  # [linux or win32 or osx]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/later_0.6.zip  # [win64]
  sha256: 4c37803145fe6d12111fd629288cc49f0b94d8eff26ef95abc834d19e61857d8  # [win64]



build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}          # [linux or osx]
    - {{ compiler('cxx') }}        # [linux or osx]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32 or osx]

  host:
    - mro-base
    - r-bh
    - r-rcpp >=0.12.9
    - r-rlang

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-bh
    - r-rcpp >=0.12.9
    - r-rlang

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('later')"           # [not win]
    - "\"%R%\" -e \"library('later')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/later
  license: GPL (>= 2)
  summary: Executes arbitrary R or C functions some time after the current time, after the R
    execution stack has emptied.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: later
# Type: Package
# Title: Utilities for Delaying Function Execution
# Version: 0.6
# Authors@R: c( person("Joe", "Cheng", role = c("aut", "cre"), email = "joe@rstudio.com"), person(family = "RStudio", role = "cph"), person("Marcus", "Geelnard", role = c("ctb", "cph"), comment = "TinyCThread library, https://tinycthread.github.io/"), person("Evan", "Nemerson", role = c("ctb", "cph"), comment = "TinyCThread library, https://tinycthread.github.io/") )
# Description: Executes arbitrary R or C functions some time after the current time, after the R execution stack has emptied.
# URL: https://github.com/r-lib/later
# BugReports: https://github.com/r-lib/later/issues
# License: GPL (>= 2)
# Imports: Rcpp (>= 0.12.9), rlang
# LinkingTo: Rcpp, BH
# RoxygenNote: 6.0.1
# Suggests: knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2017-11-04 03:32:45 UTC; jcheng
# Author: Joe Cheng [aut, cre], RStudio [cph], Marcus Geelnard [ctb, cph] (TinyCThread library, https://tinycthread.github.io/), Evan Nemerson [ctb, cph] (TinyCThread library, https://tinycthread.github.io/)
# Maintainer: Joe Cheng <joe@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-11-04 06:47:53 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
