{% set version = '1.0.0' %}  # [linux or win32]
{% set version = '1.0.0' %}  # [win64]
{% set version = '1.0.0' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cli
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/cli_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/cli/cli_{{ version }}.tar.gz  # [linux or win32]
  sha256: 8fa3dbfc954ca61b8510f767ede9e8a365dac2ef95fe87c715a0f37d721b5a1d  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/cli_1.0.0.zip  # [win64]
  sha256: ab74c86ba8a28ff975501574461d5bd8bb93541e4890197bd4780a0f8b861dd0  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/cli_1.0.0.tgz  # [osx]
  sha256: 149aaaabf0b4e22435a0bfc2a67bae637c8d83a2d3806c3af954d31bb69a5ff9  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, mockery, testthat, withr
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-assertthat
    - r-crayon

  run:
    - mro-base
    - r-assertthat
    - r-crayon

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('cli')"           # [not win]
    - "\"%R%\" -e \"library('cli')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/cli#readme
  license: MIT + file LICENSE
  summary: A suite of tools designed to build attractive command line interfaces ('CLIs'). Includes
    tools for drawing rules, boxes, trees, and 'Unicode' symbols with 'ASCII' alternatives.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: cli
# Title: Helpers for Developing Command Line Interfaces
# Version: 1.0.0
# Authors@R: c( person("Gabor", "Csardi", , "csardi.gabor@gmail.com", c("aut", "cre")), person("Hadley", "Wickham", role = c("ctb")), person("Kirill", "Muller", role = c("ctb")) )
# Description: A suite of tools designed to build attractive command line interfaces ('CLIs'). Includes tools for drawing rules, boxes, trees, and 'Unicode' symbols with 'ASCII' alternatives.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-lib/cli#readme
# BugReports: https://github.com/r-lib/cli/issues
# RoxygenNote: 6.0.1.9000
# Depends: R (>= 2.10)
# Imports: assertthat, crayon, methods
# Suggests: covr, mockery, testthat, withr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2017-11-03 20:31:55 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre], Hadley Wickham [ctb], Kirill Muller [ctb]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-11-05 12:38:47 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
