{% set version = '1.2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyverse
  version: {{ version|replace("-", "_") }}

source:
  fn: tidyverse_1.2.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/tidyverse_1.2.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/tidyverse/tidyverse_1.2.1.tar.gz  # [linux or win32]
  sha256: ad67a27bb4e89417a15338fe1a40251a7b5dedba60e9b72637963d3de574c37b  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/tidyverse_1.2.1.zip  # [win64]
  sha256: abc7dc9a90a2f254b1e0deabc11940c0ddc61036e06cd8628d44a34a2d1fc3eb  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/tidyverse_1.2.1.tgz  # [osx]
  sha256: a83be276f725e6760a4936c9a7ae559644920305c457fc170f90713454d54640  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: feather (>= 0.3.1), knitr (>= 1.17), rmarkdown (>= 1.7.4)
requirements:
  build:

  host:
    - mro-base
    - r-broom >=0.4.2
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-dbplyr >=1.1.0
    - r-dplyr >=0.7.4
    - r-forcats >=0.2.0
    - r-ggplot2 >=2.2.1
    - r-haven >=1.1.0
    - r-hms >=0.3
    - r-httr >=1.3.1
    - r-jsonlite >=1.5
    - r-lubridate >=1.7.1
    - r-magrittr >=1.5
    - r-modelr >=0.1.1
    - r-purrr >=0.2.4
    - r-readr >=1.1.1
    - r-readxl >=1.0.0
    - r-reprex >=0.1.1
    - r-rlang >=0.1.4
    - r-rstudioapi >=0.7
    - r-rvest >=0.3.2
    - r-stringr >=1.2.0
    - r-tibble >=1.3.4
    - r-tidyr >=0.7.2
    - r-xml2 >=1.1.1

  run:
    - mro-base
    - r-broom >=0.4.2
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-dbplyr >=1.1.0
    - r-dplyr >=0.7.4
    - r-forcats >=0.2.0
    - r-ggplot2 >=2.2.1
    - r-haven >=1.1.0
    - r-hms >=0.3
    - r-httr >=1.3.1
    - r-jsonlite >=1.5
    - r-lubridate >=1.7.1
    - r-magrittr >=1.5
    - r-modelr >=0.1.1
    - r-purrr >=0.2.4
    - r-readr >=1.1.1
    - r-readxl >=1.0.0
    - r-reprex >=0.1.1
    - r-rlang >=0.1.4
    - r-rstudioapi >=0.7
    - r-rvest >=0.3.2
    - r-stringr >=1.2.0
    - r-tibble >=1.3.4
    - r-tidyr >=0.7.2
    - r-xml2 >=1.1.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tidyverse')"           # [not win]
    - "\"%R%\" -e \"library('tidyverse')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://tidyverse.tidyverse.org, https://github.com/tidyverse/tidyverse
  license: GPL-3 | file LICENSE
  summary: The 'tidyverse' is a set of packages that work in harmony because they share common
    data representations and 'API' design. This package is designed to make it easy
    to install and load multiple 'tidyverse' packages in a single step. Learn more about
    the 'tidyverse' at <https://tidyverse.org>.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tidyverse
# Title: Easily Install and Load the 'Tidyverse'
# Version: 1.2.1
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = c("cph", "fnd")) )
# Description: The 'tidyverse' is a set of packages that work in harmony because they share common data representations and 'API' design. This package is designed to make it easy to install and load multiple 'tidyverse' packages in a single step. Learn more about the 'tidyverse' at <https://tidyverse.org>.
# License: GPL-3 | file LICENSE
# URL: http://tidyverse.tidyverse.org, https://github.com/tidyverse/tidyverse
# BugReports: https://github.com/tidyverse/tidyverse/issues
# Imports: broom (>= 0.4.2), cli (>= 1.0.0), crayon (>= 1.3.4), dplyr (>= 0.7.4), dbplyr (>= 1.1.0), forcats (>= 0.2.0), ggplot2 (>= 2.2.1), haven (>= 1.1.0), hms (>= 0.3), httr (>= 1.3.1), jsonlite (>= 1.5), lubridate (>= 1.7.1), magrittr (>= 1.5), modelr (>= 0.1.1), purrr (>= 0.2.4), readr (>= 1.1.1), readxl (>= 1.0.0), reprex (>= 0.1.1), rlang (>= 0.1.4), rstudioapi (>= 0.7), rvest (>= 0.3.2), stringr (>= 1.2.0), tibble (>= 1.3.4), tidyr (>= 0.7.2), xml2 (>= 1.1.1)
# Suggests: feather (>= 0.3.1), knitr (>= 1.17), rmarkdown (>= 1.7.4)
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-11-14 00:57:48 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-11-14 18:09:56 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
