{% set version = '0.12.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-repr
  version: {{ version|replace("-", "_") }}

source:
  fn: repr_0.12.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/repr_0.12.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/repr/repr_0.12.0.tar.gz  # [linux or win32]
  sha256: 03af0059ecb9b49f3d2c625eceecae7c20b88cd82a066b4d244ec5b27c16cadc  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/repr_0.12.0.zip  # [win64]
  sha256: e7672e0334b17ebe0c0958acd4cd3906b89eccf6d135972c96f9712733dea406  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/repr_0.12.0.tgz  # [osx]
  sha256: 65542409ed264b8f6f55b8713adbadd515cfde17dc02545fe12e80a2fd2cc21f  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: methods, highr, Cairo, testthat
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('repr')"           # [not win]
    - "\"%R%\" -e \"library('repr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=repr
  license: GPL-3
  summary: String and binary representations of objects for several formats / mime types.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: repr
# Title: Serializable Representations
# Version: 0.12.0
# Authors@R: c( person('Philipp', 'Angerer', email = 'phil.angerer@gmail.com', role = c('aut', 'cre')), person('Thomas', 'Kluyver', email = 'thomas@kluyver.me.uk', role = 'aut'), person('Jan', 'Schulz', email = 'jasc@gmx.net', role = 'aut'), person('abielr', role = 'ctb'), person('Denilson', 'Figueiredo de Sa', role = 'ctb'), person('Jim', 'Hester', role = 'ctb'), person('karldw', role = 'ctb') )
# Maintainer: Philipp Angerer <phil.angerer@gmail.com>
# Description: String and binary representations of objects for several formats / mime types.
# Depends: R (>= 3.0.1)
# Imports: utils, grDevices
# Suggests: methods, highr, Cairo, testthat
# Enhances: data.table, dplyr, htmlwidgets
# License: GPL-3
# LazyData: true
# Encoding: UTF-8
# Collate: 'generics.r' 'options.r' 'package.r' 'repr_datatable.r' 'utils.r' 'repr_function.r' 'repr_help_files_with_topic.r' 'repr_htmlwidget.r' 'repr_list.r' 'repr_matrix_df.r' 'repr_packageIQR.r' 'repr_recordedplot.r' 'repr_vector.r'
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2017-04-07 09:59:00 UTC; angerer
# Author: Philipp Angerer [aut, cre], Thomas Kluyver [aut], Jan Schulz [aut], abielr [ctb], Denilson Figueiredo de Sa [ctb], Jim Hester [ctb], karldw [ctb]
# Repository: CRAN
# Date/Publication: 2017-04-07 13:08:00 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
