{% set version = '0.5.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xlsx
  version: {{ version|replace("-", "_") }}

source:
  fn: xlsx_0.5.7.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/xlsx_0.5.7.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/xlsx/xlsx_0.5.7.tar.gz  # [linux or win32]
  sha256: 36727bc330c281dab8a028fab2dde92d032345974b15e3dde920ee16dc6db363  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/xlsx_0.5.7.zip  # [win64]
  sha256: 353271d09bc5da44c7b97ac5b13f3d38353ea86d2ae542f51d0e3edde2d14d6a  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/xlsx_0.5.7.tgz  # [osx]
  sha256: 5a1fc26c1e9c9d8659dcae08d36e792e47188296dd30cad320d8830957df934d  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:

  host:
    - mro-base
    - r-rjava
    - r-xlsxjars

  run:
    - mro-base
    - r-rjava
    - r-xlsxjars

test:
  requires:
    - openjdk
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('xlsx')"           # [not win]
    - "\"%R%\" -e \"library('xlsx')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://code.google.com/p/rexcel/, http://groups.google.com/group/R-package-xlsx
  license: GPL-3
  summary: Provide R functions to read/write/format Excel 2007 and Excel 97/2000/XP/2003 file
    formats.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: xlsx
# Type: Package
# Title: Read, write, format Excel 2007 and Excel 97/2000/XP/2003 files
# Version: 0.5.7
# Date: 2014-08-01
# Depends: rJava, xlsxjars
# LazyLoad: yes
# Author: Adrian A. Dragulescu
# Maintainer: Adrian A. Dragulescu <adrian.dragulescu@gmail.com>
# Description: Provide R functions to read/write/format Excel 2007 and Excel 97/2000/XP/2003 file formats.
# License: GPL-3
# URL: http://code.google.com/p/rexcel/, http://groups.google.com/group/R-package-xlsx
# BugReports: https://code.google.com/p/rexcel/issues/list
# Packaged: 2014-08-02 18:06:51 UTC; adrian
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-08-02 23:32:07

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
