{% set version = '0.0.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-drr
  version: {{ version|replace("-", "_") }}

source:
  fn: DRR_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/DRR_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/DRR/DRR_{{ version }}.tar.gz  # [linux or win32]
  sha256: 7493389c1fb9ddc4d4261e15bf2d4198603227275688b1d3e3994d47e976a1f9  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/DRR_0.0.3.zip  # [win64]
  sha256: f2fb43058aac7d28b92872caf829acf1c2399b727c6829962bec0de87f03373b  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/DRR_0.0.3.tgz  # [osx]
  sha256: cea693c89134abf8967edc0749e883ac6debab4cd219863bce5ab02ccb07d14f  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown
requirements:
  build:

  host:
    - mro-base
    - r-cvst
    - r-matrix
    - r-kernlab

  run:
    - mro-base
    - r-cvst
    - r-matrix
    - r-kernlab

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('DRR')"           # [not win]
    - "\"%R%\" -e \"library('DRR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/gdkrmr/DRR
  license: GPL-3 | file LICENSE
  summary: An Implementation of Dimensionality Reduction via Regression using Kernel Ridge Regression.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: DRR
# Title: Dimensionality Reduction via Regression
# Version: 0.0.3
# Authors@R: person("Guido", "Kraemer", email = "gkraemer@bgc-jena.mpg.de", role = c("aut","cre"))
# Description: An Implementation of Dimensionality Reduction via Regression using Kernel Ridge Regression.
# License: GPL-3 | file LICENSE
# URL: https://github.com/gdkrmr/DRR
# BugReports: https://github.com/gdkrmr/DRR/issues
# Imports: stats, methods
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# LazyData: true
# Depends: kernlab, CVST, Matrix
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-01-05 21:52:34 UTC; gkraemer
# Author: Guido Kraemer [aut, cre]
# Maintainer: Guido Kraemer <gkraemer@bgc-jena.mpg.de>
# Repository: CRAN
# Date/Publication: 2018-01-06 22:34:19 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
