{% set version = '0.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-drr
  version: {{ version|replace("-", "_") }}

source:
  fn: DRR_0.0.2.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/DRR_0.0.2.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/DRR/DRR_0.0.2.tar.gz  # [linux or win32]
  sha256: 02860f05f97a6020012fb6ebfe0d7738dd9e9db0555326f1ef57199fcde58ee9  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/DRR_0.0.2.zip  # [win64]
  sha256: 246c5d28e38a7857c48aa8bc30e9664249e614fe7643bcdf556436a68e53ef18  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/DRR_0.0.2.tgz  # [osx]
  sha256: 9f707321d7570376f5deb618fbc670022046ae645713d5bc5fe261e6af298e03  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr
requirements:
  build:

  host:
    - mro-base
    - r-cvst
    - r-matrix
    - r-kernlab

  run:
    - mro-base
    - r-cvst
    - r-matrix
    - r-kernlab

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('DRR')"           # [not win]
    - "\"%R%\" -e \"library('DRR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=DRR
  license: GPL-3
  summary: An Implementation of Dimensionality Reduction via Regression using Kernel Ridge Regression.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: DRR
# Title: Dimensionality Reduction via Regression
# Version: 0.0.2
# Authors@R: person("Guido", "Kraemer", email = "gkraemer@bgc-jena.mpg.de", role = c("aut","cre"))
# Description: An Implementation of Dimensionality Reduction via Regression using Kernel Ridge Regression.
# License: GPL-3
# Imports: stats, methods
# Suggests: knitr
# VignetteBuilder: knitr
# LazyData: true
# Depends: kernlab, CVST, Matrix
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-09-15 09:54:12 UTC; gkraemer
# Author: Guido Kraemer [aut, cre]
# Maintainer: Guido Kraemer <gkraemer@bgc-jena.mpg.de>
# Repository: CRAN
# Date/Publication: 2016-09-15 15:46:27

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
