{% set version = '0.2.5' %}  # [linux or win32]
{% set version = '0.2.5' %}  # [win64]
{% set version = '0.2.5' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-purrr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/purrr_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/purrr/purrr_{{ version }}.tar.gz  # [linux or win32]
  sha256: a4a68a453f5341ae84c3e8d77b0587ed586f36eb51f64f1315750eabfe1f8535  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/purrr_0.2.5.zip  # [win64]
  sha256: d2561cab1b61d8a879e7b6a047795b4125294f567eb2bae1e92f66b138d8270a  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/purrr_0.2.5.tgz  # [osx]
  sha256: c4048a7b80ba96f39cc6b7ac247ff4e3a833be41b0bc36e30b9a4812184f492c  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, dplyr (>= 0.7.5), knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-magrittr >=1.5
    - r-rlang >=0.1
    - r-tibble

  run:
    - mro-base
    - r-magrittr >=1.5
    - r-rlang >=0.1
    - r-tibble

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('purrr')"           # [not win]
    - "\"%R%\" -e \"library('purrr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://purrr.tidyverse.org, https://github.com/tidyverse/purrr
  license: GPL-3 | file LICENSE
  summary: A complete and consistent functional programming toolkit for R.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: purrr
# Title: Functional Programming Tools
# Version: 0.2.5
# Authors@R: c( person("Lionel", "Henry", , "lionel@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("RStudio", role = c("cph", "fnd")) )
# Description: A complete and consistent functional programming toolkit for R.
# License: GPL-3 | file LICENSE
# URL: http://purrr.tidyverse.org, https://github.com/tidyverse/purrr
# BugReports: https://github.com/tidyverse/purrr/issues
# Depends: R (>= 3.1)
# Imports: magrittr (>= 1.5), rlang (>= 0.1), tibble
# Suggests: covr, dplyr (>= 0.7.5), knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2018-05-29 14:46:54 UTC; lionel
# Author: Lionel Henry [aut, cre], Hadley Wickham [aut], RStudio [cph, fnd]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-05-29 16:46:33 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
