{% set version = '0.4.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-irdisplay
  version: {{ version|replace("-", "_") }}

source:
  fn: IRdisplay_0.4.4.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/IRdisplay_0.4.4.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/IRdisplay/IRdisplay_0.4.4.tar.gz  # [linux or win32]
  sha256: e83a0bc52800618bf9a3ac5ef3d432512e00f392b7216fd515fca319377584a6  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/IRdisplay_0.4.4.zip  # [win64]
  sha256: 451d910ce6af2482027134cf50c7ad2e7b2f7f1da7f83576f7b31c54e89a3bfe  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/IRdisplay_0.4.4.tgz  # [osx]
  sha256: abb9be21edd914c6c089adf149990da68ef9f7888e6a8877d6a6ed0b3356e299  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, withr
requirements:
  build:

  host:
    - mro-base
    - r-repr

  run:
    - mro-base
    - r-repr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('IRdisplay')"           # [not win]
    - "\"%R%\" -e \"library('IRdisplay')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=IRdisplay
  license: MIT + file LICENSE
  summary: ' An interface to the rich display capabilities of ''Jupyter'' front-ends (e.g. ''Jupyter
    Notebook'') <https://jupyter.org>. Designed to be used from a running ''IRkernel''
    session <https://irkernel.github.io>.'

  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: IRdisplay
# Title: 'Jupyter' Display Machinery
# Description:  An interface to the rich display capabilities of 'Jupyter' front-ends (e.g. 'Jupyter Notebook') <https://jupyter.org>. Designed to be used from a running 'IRkernel' session <https://irkernel.github.io>.
# Version: 0.4.4
# Authors@R: c( person('Thomas', 'Kluyver', role = c('aut', 'cph'), email = 'thomas@kluyver.me.uk'), person('Philipp', 'Angerer', role = c('aut', 'cph', 'cre'), email = 'phil.angerer@gmail.com'), person('Jan', 'Schulz', role = c('aut', 'cph'), email = 'jasc@gmx.net'))
# Depends: R (>= 3.0.1)
# Suggests: testthat, withr
# Imports: repr
# License: MIT + file LICENSE
# LazyData: true
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-08-02 11:52:46 UTC; angerer
# Author: Thomas Kluyver [aut, cph], Philipp Angerer [aut, cph, cre], Jan Schulz [aut, cph]
# Maintainer: Philipp Angerer <phil.angerer@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-08-02 14:45:35

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
