{% set version = '0.23-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ttr
  version: {{ version|replace("-", "_") }}

source:
  fn: TTR_0.23-2.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/TTR_0.23-2.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/TTR/TTR_0.23-2.tar.gz  # [linux or win32]
  sha256: 1a1fc1d2361d58d573d6ec645633521840d3f606406314a992967e8c17c75436  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/TTR_0.23-2.zip  # [win64]
  sha256: 86ebfb9a33de62373cba418df9dfa4ac6e45542e0bfebbeb056bf1d37d900724  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/TTR_0.23-2.tgz  # [osx]
  sha256: de81fe6a8e261456de82f3b71a89d5b126a144629b53b172f84d8e51a9f38e19  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('fortran') }}    # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-curl
    - r-xts >=0.10_0
    - r-zoo

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-curl
    - r-xts >=0.10_0
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('TTR')"           # [not win]
    - "\"%R%\" -e \"library('TTR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/joshuaulrich/TTR
  license: GPL-2
  summary: Functions and data to construct technical trading rules with R.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: TTR
# Type: Package
# Title: Technical Trading Rules
# Version: 0.23-2
# Date: 2017-07-07
# Author: Joshua Ulrich
# Maintainer: Joshua Ulrich <josh.m.ulrich@gmail.com>
# Imports: xts (>= 0.10-0), zoo, curl
# LinkingTo: xts
# Enhances: quantmod
# Suggests: RUnit
# Description: Functions and data to construct technical trading rules with R.
# License: GPL-2
# URL: https://github.com/joshuaulrich/TTR
# BugReports: https://github.com/joshuaulrich/TTR/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-07-10 17:18:49 UTC; josh
# Repository: CRAN
# Date/Publication: 2017-07-11 05:34:20 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
