{% set version = '0.6-22' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-misctools
  version: {{ version|replace("-", "_") }}

source:
  fn: miscTools_0.6-22.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/miscTools_0.6-22.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/miscTools/miscTools_0.6-22.tar.gz  # [linux or win32]
  sha256: d00bb2602d1d31e9e1e13c8868cfe69d432bbe15afa8d4bbb83b3c9e0b9dcfea  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/miscTools_0.6-22.zip  # [win64]
  sha256: 0f22d4d29008eede247f74afd10e2fcaaff2f0aa38492c6d67b548757f86bbfc  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/miscTools_0.6-22.tgz  # [osx]
  sha256: 9c24afeb1c8594321d00834b153eb6ee5ab52d03365795fbdd11d6a2af053103  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: Ecdat (>= 0.1-5)
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('miscTools')"           # [not win]
    - "\"%R%\" -e \"library('miscTools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.micEcon.org
  license: GPL (>= 2)
  summary: Miscellaneous small tools and utilities. Many of them facilitate the work with matrices,
    e.g. inserting rows or columns, creating symmetric matrices, or checking for semidefiniteness.
    Other tools facilitate the work with regression models, e.g. extracting the standard
    errors, obtaining the number of (estimated) parameters, or calculating R-squared
    values.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: miscTools
# Version: 0.6-22
# Date: 2016-11-25
# Title: Miscellaneous Tools and Utilities
# Author: Arne Henningsen, Ott Toomet
# Maintainer: Arne Henningsen <arne.henningsen@gmail.com>
# Depends: R (>= 2.14.0)
# Suggests: Ecdat (>= 0.1-5)
# Description: Miscellaneous small tools and utilities. Many of them facilitate the work with matrices, e.g. inserting rows or columns, creating symmetric matrices, or checking for semidefiniteness. Other tools facilitate the work with regression models, e.g. extracting the standard errors, obtaining the number of (estimated) parameters, or calculating R-squared values.
# License: GPL (>= 2)
# URL: http://www.micEcon.org
# NeedsCompilation: no
# Packaged: 2016-11-25 07:44:12 UTC; arne
# Repository: CRAN
# Date/Publication: 2016-11-25 14:14:33

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
