{% set version = '0.3.14' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-inline
  version: {{ version|replace("-", "_") }}

source:
  fn: inline_0.3.14.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/inline_0.3.14.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/inline/inline_0.3.14.tar.gz  # [linux or win32]
  sha256: fd34d6bf965148d26d983a022a0ff7bc1a5831f6ca066deee3f6139894dfc931  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/inline_0.3.14.zip  # [win64]
  sha256: 3fda5ef16ddb620e7cb46d5cfb0ec52979a76c8a9b8a0804e940d0a3168647bd  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/inline_0.3.14.tgz  # [osx]
  sha256: 9249aceeb112193b6b1ca2d162e42a533599873fbb0544f1be60fd40a6313b18  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: Rcpp (>= 0.11.0)
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('inline')"           # [not win]
    - "\"%R%\" -e \"library('inline')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=inline
  license: LGPL
  summary: Functionality to dynamically define R functions and S4 methods with inlined C, C++
    or Fortran code supporting .C and .Call calling conventions.
  license_family: LGPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: inline
# Version: 0.3.14
# Date: 2015-04-11
# Title: Functions to Inline C, C++, Fortran Function Calls from R
# Author: Oleg Sklyar, Duncan Murdoch, Mike Smith, Dirk Eddelbuettel,  Romain Francois, Karline Soetaert
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Depends: R (>= 2.4.0), methods
# Suggests: Rcpp (>= 0.11.0)
# Description: Functionality to dynamically define R functions and S4 methods with inlined C, C++ or Fortran code supporting .C and .Call calling conventions.
# License: LGPL
# Copyright: Oleg Sklyar, 2005-2010 and other authors per their commits
# LazyLoad: yes
# BugReports: https://github.com/eddelbuettel/inline/issues
# NeedsCompilation: no
# Packaged: 2015-04-12 14:35:08.942414 UTC; edd
# Repository: CRAN
# Date/Publication: 2015-04-13 09:20:41

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
