{% set version = '0.20-35' %}  # [linux or win32]
{% set version = '0.20-35' %}  # [win64]
{% set version = '0.20-35' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lattice
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/lattice_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/lattice/lattice_{{ version }}.tar.gz  # [linux or win32]
  sha256: 0829ab0f4dec55aac6a73bc3411af68441ddb1b5b078d680a7c2643abeaa965d  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/lattice_0.20-35.zip  # [win64]
  sha256: 3b0dadafcfdec00b6f0c13042bd0e7fbc1b1367c0188c7b44a03e26fcb21da6e  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/lattice_0.20-35.tgz  # [osx]
  sha256: f7212a7678e93910ce59747f7ffc513587168f485d30f770a78ec1af98f5c3d4  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: KernSmooth, MASS, latticeExtra
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lattice')"           # [not win]
    - "\"%R%\" -e \"library('lattice')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://lattice.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: A powerful and elegant high-level data visualization system inspired by Trellis graphics,
    with an emphasis on multivariate data. Lattice is sufficient for typical graphics
    needs, and is also flexible enough to handle most nonstandard requirements. See
    ?Lattice for an introduction.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: lattice
# Version: 0.20-35
# Date: 2017-03-23
# Priority: recommended
# Title: Trellis Graphics for R
# Author: Deepayan Sarkar <deepayan.sarkar@r-project.org>
# Maintainer: Deepayan Sarkar <deepayan.sarkar@r-project.org>
# Description: A powerful and elegant high-level data visualization system inspired by Trellis graphics, with an emphasis on multivariate data. Lattice is sufficient for typical graphics needs, and is also flexible enough to handle most nonstandard requirements. See ?Lattice for an introduction.
# Depends: R (>= 3.0.0)
# Suggests: KernSmooth, MASS, latticeExtra
# Imports: grid, grDevices, graphics, stats, utils
# Enhances: chron
# LazyLoad: yes
# LazyData: yes
# License: GPL (>= 2)
# URL: http://lattice.r-forge.r-project.org/
# BugReports: https://github.com/deepayan/lattice/issues
# NeedsCompilation: yes
# Packaged: 2017-03-25 11:25:40 UTC; deepayan
# Repository: CRAN
# Date/Publication: 2017-03-25 18:05:47 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
