{% set version = '1.0.0' %}  # [linux or win32]
{% set version = '1.0.0' %}  # [win64]
{% set version = '1.0.0' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-praise
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/praise_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/praise/praise_{{ version }}.tar.gz  # [linux or win32]
  sha256: 5c035e74fd05dfa59b03afe0d5f4c53fbf34144e175e90c53d09c6baedf5debd  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/praise_1.0.0.zip  # [win64]
  sha256: 187ef0ae3cb6ca56c7c2a3a418b0eaf72a9405efb128c14d4a5a23e226e19418  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/praise_1.0.0.tgz  # [osx]
  sha256: 5d60c8cceacc8de5067bfeef6cc0dee8fd7629b89a8c598df1128e52d6ea1937  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('praise')"           # [not win]
    - "\"%R%\" -e \"library('praise')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/gaborcsardi/praise
  license: MIT + file LICENSE
  summary: Build friendly R packages that praise their users if they have done something good,
    or they just need it to feel better.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: praise
# Title: Praise Users
# Version: 1.0.0
# Author: Gabor Csardi, Sindre Sorhus
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Description: Build friendly R packages that praise their users if they have done something good, or they just need it to feel better.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/gaborcsardi/praise
# BugReports: https://github.com/gaborcsardi/praise/issues
# Suggests: testthat
# Collate: 'adjective.R' 'adverb.R' 'exclamation.R' 'verb.R' 'rpackage.R' 'package.R'
# NeedsCompilation: no
# Packaged: 2015-08-11 02:01:43 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2015-08-11 08:22:28

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
