{% set version = '0.3-2' %}  # [linux or win32]
{% set version = '0.3-2' %}  # [win64]
{% set version = '0.3-2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-whisker
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/whisker_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/whisker/whisker_{{ version }}.tar.gz  # [linux or win32]
  sha256: 484836510fcf123a66ddd13cdc8f32eb98e814cad82ed30c0294f55742b08c7c  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/whisker_0.3-2.zip  # [win64]
  sha256: 2e3451148f11e90dd64f1d0ec07db590b996b4369d91a336892d30fb66c78fed  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/whisker_0.3-2.tgz  # [osx]
  sha256: eb01a1e31dad420e40e46545138d4b2bc18d4f29645a584c29c8d4f3be61182b  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: markdown
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('whisker')"           # [not win]
    - "\"%R%\" -e \"library('whisker')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/edwindj/whisker
  license: GPL-3
  summary: logicless templating, reuse templates in many programming languages including R
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: whisker
# Maintainer: Edwin de Jonge <edwindjonge@gmail.com>
# License: GPL-3
# Title: {{mustache}} for R, logicless templating
# Type: Package
# LazyLoad: yes
# Author: Edwin de Jonge
# Description: logicless templating, reuse templates in many programming languages including R
# Version: 0.3-2
# URL: http://github.com/edwindj/whisker
# Date: 2010-12-23
# Collate: 'whisker.R' 'section.R' 'parseTemplate.R' 'partials.R' 'inverted.R' 'pkg.R' 'iteratelist.R' 'delim.R' 'markdown.R' 'rowsplit.R'
# Suggests: markdown
# Packaged: 2013-04-27 22:49:33 UTC; Edwin
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-04-28 07:55:20

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
