{% set version = '1.8-2' %}  # [linux or win32 or osx]
{% set version = '1.8-2' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xtable
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/xtable_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/xtable/xtable_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 1623a1cde2e130fedb46f98840c3a882f1cbb167b292ef2bd86d70baefc4280d  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/xtable_1.8-2.zip  # [win64]
  sha256: 4f6bba9420d216600b95c4bded00b624891c9daff887bb76c3ab6bae810a5635  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, lsmeans, spdep, splm, sphet, plm, zoo, survival
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('xtable')"           # [not win]
    - "\"%R%\" -e \"library('xtable')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://xtable.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: Coerce data to LaTeX and HTML tables.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: xtable
# Version: 1.8-2
# Date: 2016-01-08
# Title: Export Tables to LaTeX or HTML
# Author: David B. Dahl <dahl@stat.byu.edu>
# Maintainer: David Scott <d.scott@auckland.ac.nz>
# Imports: stats, utils
# Suggests: knitr, lsmeans, spdep, splm, sphet, plm, zoo, survival
# VignetteBuilder: knitr
# Description: Coerce data to LaTeX and HTML tables.
# URL: http://xtable.r-forge.r-project.org/
# Depends: R (>= 2.10.0)
# License: GPL (>= 2)
# Repository: CRAN
# NeedsCompilation: no
# Packaged: 2016-02-02 02:58:02 UTC; dsco036
# Date/Publication: 2016-02-05 19:22:18

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
