{% set version = '0.10-44' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tseries
  version: {{ version|replace("-", "_") }}

source:
  fn: tseries_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/tseries_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/tseries/tseries_{{ version }}.tar.gz  # [linux or win32]
  sha256: 4f114a807995a7df6c53842acc144e592370412e5411e4decd97750dcdd9e65b  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/tseries_0.10-44.zip  # [win64]
  sha256: 27022e8346abd1663dabea19d165b9633999d1d89a72b47a27f8445c46f853ba  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/tseries_0.10-44.tgz  # [osx]
  sha256: e153c7702ca64180921d85c4761b796dd04205cd9835e0ff5fbdce116c29782c  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]

  host:
    - mro-base
    - r-quadprog
    - r-quantmod >=0.4.9
    - r-zoo

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-quadprog
    - r-quantmod >=0.4.9
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tseries')"           # [not win]
    - "\"%R%\" -e \"library('tseries')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=tseries
  license: GPL-2
  summary: Time series analysis and computational finance.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tseries
# Version: 0.10-44
# Title: Time Series Analysis and Computational Finance
# Authors@R: c(person("Adrian", "Trapletti", role = "aut", email = "adrian@trapletti.org"), person("Kurt", "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org"), person("Blake", "LeBaron", role = "ctb", comment = "BDS test code"))
# Description: Time series analysis and computational finance.
# Depends: R (>= 2.10.0)
# Imports: graphics, stats, utils, quadprog, zoo, quantmod (>= 0.4.9)
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2018-04-15 15:14:39 UTC; hornik
# Author: Adrian Trapletti [aut], Kurt Hornik [aut, cre], Blake LeBaron [ctb] (BDS test code)
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-04-15 16:35:20 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
