{% set version = '3.98-1.11' %}  # [linux or win32]
{% set version = '3.98-1.11' %}  # [win64]
{% set version = '3.98-1.11' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xml
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/XML_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/XML/XML_{{ version }}.tar.gz  # [linux or win32]
  sha256: 505bd948152213c22e255b8d38b303c0fac5e113c0f9b1bcc9bfa62e1edd3fa2  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/XML_3.98-1.11.zip  # [win64]
  sha256: 7f9d08a2e21e6a9c1c2ec7906f403582dd03051282d9778f13045312708fc04a  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/macosx/el-capitan/contrib/3.5/XML_3.98-1.11.tgz  # [osx]
  sha256: 4eab514424fff778d60d305ee5ba5ba6fdf3149c6d20c41c83a263993fede2aa  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bitops, RCurl
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}sed               # [win32]
    - {{posix}}grep              # [win32]
    - {{posix}}autoconf          # [linux or win32]
    - {{posix}}automake          # [linux]
    - {{posix}}automake-wrapper  # [win32]
    - {{posix}}pkg-config
    - {{posix}}make              # [linux or win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('XML')"           # [not win]
    - "\"%R%\" -e \"library('XML')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.omegahat.net/RSXML
  license: BSD_2_clause + file LICENSE
  summary: Many approaches for both reading and creating XML (and HTML) documents (including
    DTDs), both local and accessible via HTTP or FTP.  Also offers access to an 'XPath'
    "interpreter".
  license_family: BSD

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: XML
# Version: 3.98-1.11
# Author: Duncan Temple Lang and the CRAN Team
# Maintainer: ORPHANED
# Title: Tools for Parsing and Generating XML Within R and S-Plus
# Depends: R (>= 2.13.0), methods, utils
# Suggests: bitops, RCurl
# SystemRequirements: libxml2 (>= 2.6.3)
# Description: Many approaches for both reading and creating XML (and HTML) documents (including DTDs), both local and accessible via HTTP or FTP.  Also offers access to an 'XPath' "interpreter".
# Note: In version 2.4.0 of this package, a new approach to garbage collection has been implemented and it is experimental. You can disable it via the configuration option --enable-nodegc=no. However, you are encouraged to use this and report problems as the results are beneficial and being able to produce any errors should they occur will be very helpful.
# URL: http://www.omegahat.net/RSXML
# License: BSD_2_clause + file LICENSE
# Collate: AAA.R DTD.R DTDClasses.R DTDRef.R SAXMethods.S XMLClasses.R applyDOM.R assignChild.R catalog.R createNode.R dynSupports.R error.R flatTree.R nodeAccessors.R parseDTD.R schema.S summary.R tangle.R toString.S tree.R version.R xmlErrorEnums.R xmlEventHandler.R xmlEventParse.R xmlHandler.R xmlInternalSource.R xmlOutputDOM.R xmlNodes.R xmlOutputBuffer.R xmlTree.R xmlTreeParse.R htmlParse.R hashTree.R zzz.R supports.R parser.R libxmlFeatures.R xmlString.R saveXML.R namespaces.R readHTMLTable.R reflection.R xmlToDataFrame.R bitList.R compare.R encoding.R fixNS.R xmlRoot.R serialize.R xmlMemoryMgmt.R keyValueDB.R solrDocs.R XMLRErrorInfo.R xincludes.R namespaceHandlers.R tangle1.R htmlLinks.R htmlLists.R getDependencies.R getRelativeURL.R xmlIncludes.R simplifyPath.R
# NeedsCompilation: yes
# Packaged: 2018-04-16 15:32:09 UTC; hornik
# X-CRAN-Original-Maintainer: Duncan Temple Lang <duncan@r-project.org>
# X-CRAN-Comment: Orphaned on 2017-06-19: all updates have been by the CRAN team for some years.
# Repository: CRAN
# Date/Publication: 2018-04-16 19:07:42 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
