{% set version = '3.98-1.12' %}  # [linux or win32]
{% set version = '3.98-1.12' %}  # [win64]
{% set version = '3.98-1.12' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xml
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/XML_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/XML/XML_{{ version }}.tar.gz  # [linux or win32]
  sha256: 3b4a58c3ab2c0519e3dfcdc6cf1a3b3dafd9b09132f689e39c6aeb4a788c1340  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/XML_3.98-1.12.zip  # [win64]
  sha256: 24222b859225d7d8c82717b1ab8cbc4a5948661dbb3f173c9c222ed1ed5c3d5f  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/XML_3.98-1.12.tgz  # [osx]
  sha256: 1ef92740bee2914ec3d2d0db24a8a3ffd50e9566bd2f8021e98b39c782dacb15  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bitops, RCurl
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('XML')"           # [not win]
    - "\"%R%\" -e \"library('XML')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.omegahat.net/RSXML
  license: BSD_2_clause + file LICENSE
  summary: Many approaches for both reading and creating XML (and HTML) documents (including
    DTDs), both local and accessible via HTTP or FTP.  Also offers access to an 'XPath'
    "interpreter".
  license_family: BSD

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: XML
# Version: 3.98-1.12
# Author: Duncan Temple Lang and the CRAN Team
# Maintainer: ORPHANED
# Title: Tools for Parsing and Generating XML Within R and S-Plus
# Depends: R (>= 2.13.0), methods, utils
# Suggests: bitops, RCurl
# SystemRequirements: libxml2 (>= 2.6.3)
# Description: Many approaches for both reading and creating XML (and HTML) documents (including DTDs), both local and accessible via HTTP or FTP.  Also offers access to an 'XPath' "interpreter".
# URL: http://www.omegahat.net/RSXML
# License: BSD_2_clause + file LICENSE
# Collate: AAA.R DTD.R DTDClasses.R DTDRef.R SAXMethods.S XMLClasses.R applyDOM.R assignChild.R catalog.R createNode.R dynSupports.R error.R flatTree.R nodeAccessors.R parseDTD.R schema.S summary.R tangle.R toString.S tree.R version.R xmlErrorEnums.R xmlEventHandler.R xmlEventParse.R xmlHandler.R xmlInternalSource.R xmlOutputDOM.R xmlNodes.R xmlOutputBuffer.R xmlTree.R xmlTreeParse.R htmlParse.R hashTree.R zzz.R supports.R parser.R libxmlFeatures.R xmlString.R saveXML.R namespaces.R readHTMLTable.R reflection.R xmlToDataFrame.R bitList.R compare.R encoding.R fixNS.R xmlRoot.R serialize.R xmlMemoryMgmt.R keyValueDB.R solrDocs.R XMLRErrorInfo.R xincludes.R namespaceHandlers.R tangle1.R htmlLinks.R htmlLists.R getDependencies.R getRelativeURL.R xmlIncludes.R simplifyPath.R
# NeedsCompilation: yes
# Packaged: 2018-07-15 17:08:56 UTC; ripley
# X-CRAN-Original-Maintainer: Duncan Temple Lang <duncan@r-project.org>
# X-CRAN-Comment: Orphaned on 2017-06-19: all updates have been by the CRAN team for some years.
# Repository: CRAN
# Date/Publication: 2018-07-15 17:11:40 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
