{% set version = '1.1.13' %}  # [linux or win32]
{% set version = '1.1.13' %}  # [win64]
{% set version = '1.1.13' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-polspline
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/polspline_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/polspline/polspline_{{ version }}.tar.gz  # [linux or win32]
  sha256: 937561842d754e40a48d2e6d0c49638739e3fdc9bb81e9d8d05adea828371f22  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/polspline_1.1.13.zip  # [win64]
  sha256: 793376488083cbf55e5eabd73defe1a71ade664fb75173d8c9e3b2d8e30b20cc  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/polspline_1.1.13.tgz  # [osx]
  sha256: f977b76a18cf46d364b62a35f0aa1ec48f6c187a2ed912616a50bed3eaebe500  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - {{native}}rtools           # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('polspline')"           # [not win]
    - "\"%R%\" -e \"library('polspline')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=polspline
  license: GPL (>= 2)
  summary: Routines for the polynomial spline fitting routines hazard regression, hazard estimation
    with flexible tails, logspline, lspec, polyclass, and polymars, by C. Kooperberg
    and co-authors.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: polspline
# Version: 1.1.13
# Date: 2018-06-14
# Title: Polynomial Spline Routines
# Author: Charles Kooperberg <clk@fredhutch.org>
# Maintainer: Charles Kooperberg <clk@fredhutch.org>
# Description: Routines for the polynomial spline fitting routines hazard regression, hazard estimation with flexible tails, logspline, lspec, polyclass, and polymars, by C. Kooperberg and co-authors.
# Imports: stats, graphics
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2018-06-14 19:39:07 UTC; clk
# Repository: CRAN
# Date/Publication: 2018-06-14 21:55:50 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
