{% set version = '1.7-0' %}  # [linux or win32]
{% set version = '1.7-0' %}  # [win64]
{% set version = '1.7-0' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-e1071
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/e1071_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/e1071/e1071_{{ version }}.tar.gz  # [linux or win32]
  sha256: 93699a2e16826459221cf7c9896d99e87fdc1c0e2e270bda302670760cbf643a  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/e1071_1.7-0.zip  # [win64]
  sha256: 4c6d7ab88afe638fd9815acb3671f2b9d24fce572925840c7a6f13645e5d3a56  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/e1071_1.7-0.tgz  # [osx]
  sha256: ddc7b7e9c4c781092028e5cefe8853b96e6c4abe1315c3bdb3010d18c8340dd9  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: cluster, mlbench, nnet, randomForest, rpart, SparseM, xtable, Matrix, MASS
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux or osx]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-class

  run:
    - mro-base
    - r-class

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('e1071')"           # [not win]
    - "\"%R%\" -e \"library('e1071')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=e1071
  license: GPL-2
  summary: Functions for latent class analysis, short time Fourier transform, fuzzy clustering,
    support vector machines, shortest path computation, bagged clustering, naive Bayes
    classifier, ...
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: e1071
# Version: 1.7-0
# Title: Misc Functions of the Department of Statistics, Probability Theory Group (Formerly: E1071), TU Wien
# Imports: graphics, grDevices, class, stats, methods, utils
# Suggests: cluster, mlbench, nnet, randomForest, rpart, SparseM, xtable, Matrix, MASS
# Authors@R: c(person(given = "David", family = "Meyer", role = c("aut", "cre"), email = "David.Meyer@R-project.org"), person(given = "Evgenia", family = "Dimitriadou", role = c("aut","cph")), person(given = "Kurt", family = "Hornik", role = "aut"), person(given = "Andreas", family = "Weingessel", role = "aut"), person(given = "Friedrich", family = "Leisch", role = "aut"), person(given = "Chih-Chung", family = "Chang", role = c("ctb","cph"), comment = "libsvm C++-code"), person(given = "Chih-Chen", family = "Lin", role = c("ctb","cph"), comment = "libsvm C++-code"))
# Description: Functions for latent class analysis, short time Fourier transform, fuzzy clustering, support vector machines, shortest path computation, bagged clustering, naive Bayes classifier, ...
# License: GPL-2
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2018-07-23 12:08:44 UTC; meyer
# Author: David Meyer [aut, cre], Evgenia Dimitriadou [aut, cph], Kurt Hornik [aut], Andreas Weingessel [aut], Friedrich Leisch [aut], Chih-Chung Chang [ctb, cph] (libsvm C++-code), Chih-Chen Lin [ctb, cph] (libsvm C++-code)
# Maintainer: David Meyer <David.Meyer@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-07-28 15:50:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
