{% set version = '0.2.3' %}  # [linux or win32]
{% set version = '0.2.3' %}  # [win64]
{% set version = '0.2.3' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fansi
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/fansi_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/fansi/fansi_{{ version }}.tar.gz  # [linux or win32]
  sha256: db6dfef8bfe6682d58b654b6a6a1d59cb07225ca41755176b465ab8611fd96c9  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/fansi_0.2.3.zip  # [win64]
  sha256: 701312fc4893c57db9068be9f0e1f311e62b4188e97cff37a6cdb36cf8e7f5ba  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/fansi_0.2.3.tgz  # [osx]
  sha256: 313eca3853c3e9f0b8f9987cec80fbe8a0764354a9e9be7cc48ef1d40a7cefc8  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: unitizer
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('fansi')"           # [not win]
    - "\"%R%\" -e \"library('fansi')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/brodieG/fansi
  license: GPL (>= 2)
  summary: Counterparts to R string manipulation functions that account for the effects of ANSI
    text formatting control sequences.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: fansi
# Title: ANSI Control Sequence Aware String Functions
# Description: Counterparts to R string manipulation functions that account for the effects of ANSI text formatting control sequences.
# Version: 0.2.3
# Authors@R: c( person("Brodie", "Gaslam", email="brodie.gaslam@yahoo.com", role=c("aut", "cre")), person(family="R Core Team", email="R-core@r-project.org", role="cph", comment="UTF8 byte length calcs from src/util.c" ))
# Depends: R (>= 3.1.0)
# License: GPL (>= 2)
# LazyData: true
# URL: https://github.com/brodieG/fansi
# BugReports: https://github.com/brodieG/fansi/issues
# Suggests: unitizer
# RoxygenNote: 6.0.1
# Collate: 'constants.R' 'fansi-package.R' 'has.R' 'internal.R' 'load.R' 'misc.R' 'nchar.R' 'strip.R' 'strwrap.R' 'strtrim.R' 'strsplit.R' 'substr2.R' 'tohtml.R' 'unhandled.R'
# NeedsCompilation: yes
# Packaged: 2018-05-06 14:26:55 UTC; brodie
# Author: Brodie Gaslam [aut, cre], R Core Team [cph] (UTF8 byte length calcs from src/util.c)
# Maintainer: Brodie Gaslam <brodie.gaslam@yahoo.com>
# Repository: CRAN
# Date/Publication: 2018-05-06 18:01:08 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
