{% set version = '4.1.0' %}  # [linux or win32]
{% set version = '4.1.0' %}  # [win64]
{% set version = '4.1.0' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-openxlsx
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/openxlsx_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/openxlsx/openxlsx_{{ version }}.tar.gz  # [linux or win32]
  sha256: ab7b127353061a0e1cd621783366ffdd7c858c6df31cbbdd39aaa353af10ffd8  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/openxlsx_4.1.0.zip  # [win64]
  sha256: 235d8f383b1c7133f4acc0490c0cbb865cdf5b67e59606d063776918dc629618  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/openxlsx_4.1.0.tgz  # [osx]
  sha256: b2b3168d0e7059a00266ef4844e51f004b449793f3ec76690f55dbd770d0806c  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux or osx]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-rcpp
    - r-zip

  run:
    - mro-base
    - r-rcpp
    - r-zip

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('openxlsx')"           # [not win]
    - "\"%R%\" -e \"library('openxlsx')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/awalker89/openxlsx
  license: MIT + file LICENSE
  summary: Simplifies the creation of Excel .xlsx files by providing a high level interface to
    writing, styling and editing worksheets. Through the use of 'Rcpp', read/write times
    are comparable to the 'xlsx' and 'XLConnect' packages with the added benefit of
    removing the dependency on Java.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: openxlsx
# Type: Package
# Title: Read, Write and Edit XLSX Files
# Version: 4.1.0
# Date: 2018-05-26
# Authors@R: c( person("Alexander", "Walker", email = "Alexander.Walker1989@gmail.com", role = c("aut", "cre")), person("Luca", "Braglia", role = "ctb"))
# URL: https://github.com/awalker89/openxlsx
# BugReports: https://github.com/awalker89/openxlsx/issues
# Maintainer: Alexander Walker <Alexander.Walker1989@gmail.com>
# Description: Simplifies the creation of Excel .xlsx files by providing a high level interface to writing, styling and editing worksheets. Through the use of 'Rcpp', read/write times are comparable to the 'xlsx' and 'XLConnect' packages with the added benefit of removing the dependency on Java.
# License: MIT + file LICENSE
# LinkingTo: Rcpp
# Encoding: UTF-8
# Depends: R (>= 3.3.0)
# Imports: methods, Rcpp, grDevices, stats, utils, zip
# VignetteBuilder: knitr
# Suggests: knitr, testthat
# RoxygenNote: 6.0.1.9000
# Collate: 'CommentClass.R' 'HyperlinkClass.R' 'RcppExports.R' 'class_definitions.R' 'StyleClass.R' 'WorkbookClass.R' 'baseXML.R' 'borderFunctions.R' 'chartsheet_class.R' 'conditional_formatting.R' 'helperFunctions.R' 'loadWorkbook.R' 'onUnload.R' 'openXL.R' 'openxlsx.R' 'openxlsxCoerce.R' 'readWorkbook.R' 'sheet_data_class.R' 'workbook_column_widths.R' 'workbook_read_workbook.R' 'workbook_write_data.R' 'worksheet_class.R' 'wrappers.R' 'writeData.R' 'writeDataTable.R' 'writexlsx.R'
# NeedsCompilation: yes
# Packaged: 2018-05-26 13:55:02 UTC; Alex
# Author: Alexander Walker [aut, cre], Luca Braglia [ctb]
# Repository: CRAN
# Date/Publication: 2018-05-26 15:20:49 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
