{% set version = '1.2.6' %}  # [linux or win32]
{% set version = '1.2.6' %}  # [win64]
{% set version = '1.2.6' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapproj
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/mapproj_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/mapproj/mapproj_{{ version }}.tar.gz  # [linux or win32]
  sha256: 62a5aa97837ae95ef9f973d95fe45fe43dbbf482dfa922e9df60f3c510e7efe5  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/mapproj_1.2.6.zip  # [win64]
  sha256: 293b06c01dff07bd9be3dd746c363d4c5a6c81e3895abca4e8091c4305eec445  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/mapproj_1.2.6.tgz  # [osx]
  sha256: e87bd7944a74bcbeeed538967edc8bd7de657b4245d8c55f323d1e47c865edf2  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-maps >=2.3_0

  run:
    - mro-base
    - r-maps >=2.3_0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mapproj')"           # [not win]
    - "\"%R%\" -e \"library('mapproj')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mapproj
  license: Lucent Public License
  summary: Converts latitude/longitude into projected coordinates.
  license_family: OTHER

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mapproj
# Title: Map Projections
# Version: 1.2.6
# Date: 2018-03-29
# Author: Doug McIlroy.  Packaged for R by Ray Brownrigg and Thomas P Minka, transition to Plan 9 codebase by Roger Bivand.
# Description: Converts latitude/longitude into projected coordinates.
# Depends: R (>= 3.0.0), maps (>= 2.3-0)
# Imports: stats, graphics
# License: Lucent Public License
# Maintainer: Alex Deckmyn <alex.deckmyn@meteo.be>
# NeedsCompilation: yes
# Packaged: 2018-03-29 12:55:41 UTC; dalex
# Repository: CRAN
# Date/Publication: 2018-03-29 15:33:42 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
