{% set version = '1.2-5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapproj
  version: {{ version|replace("-", "_") }}

source:
  fn: mapproj_1.2-5.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/mapproj_1.2-5.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/mapproj/mapproj_1.2-5.tar.gz  # [linux or win32]
  sha256: f3026a3a69a550c923b44c18b1ccc60d98e52670a438250d13f3c74cf2195f66  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/mapproj_1.2-5.zip  # [win64]
  sha256: 2882aaffed6bc06f6c2a3f5e5a2549a1e15a9455712d1fc216badf5e61639f7e  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/mapproj_1.2-5.tgz  # [osx]
  sha256: 30a91c0348d54551ce2b050f367cd03d34ada3b2c2242c6624b7bcb9855c1ed2  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-maps >=2.3_0

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-maps >=2.3_0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mapproj')"           # [not win]
    - "\"%R%\" -e \"library('mapproj')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mapproj
  license: Lucent Public License
  summary: Converts latitude/longitude into projected coordinates.
  license_family: OTHER

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mapproj
# Title: Map Projections
# Version: 1.2-5
# Date: 2017-06-06
# Author: Doug McIlroy.  Packaged for R by Ray Brownrigg and Thomas P Minka, transition to Plan 9 codebase by Roger Bivand.
# Description: Converts latitude/longitude into projected coordinates.
# Depends: maps (>= 2.3-0)
# Imports: stats, graphics
# License: Lucent Public License
# Maintainer: Alex Deckmyn <alex.deckmyn@meteo.be>
# NeedsCompilation: yes
# Packaged: 2017-06-07 08:34:30 UTC; dalex
# Repository: CRAN
# Date/Publication: 2017-06-08 04:43:11 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
