{% set version = '2.0-0' %}  # [linux or win32]
{% set version = '2.0-0' %}  # [win64]
{% set version = '2.0-0' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dichromat
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/dichromat_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/dichromat/dichromat_{{ version }}.tar.gz  # [linux or win32]
  sha256: 31151eaf36f70bdc1172da5ff5088ee51cc0a3db4ead59c7c38c25316d580dd1  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/dichromat_2.0-0.zip  # [win64]
  sha256: 83d66222e2b5c7dce3e2a79ead7cb2fb7dea4c602c977df39a841d6b6abcf40e  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/dichromat_2.0-0.tgz  # [osx]
  sha256: 51b34848115ea657e2df849230d3eee6d46efe8a23b9bc43f6a8e862bebc3c41  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('dichromat')"           # [not win]
    - "\"%R%\" -e \"library('dichromat')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=dichromat
  license: GPL-2
  summary: Collapse red-green or green-blue distinctions to simulate the effects of different
    types of color-blindness.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: dichromat
# Version: 2.0-0
# Date: 2013-01-23
# Title: Color Schemes for Dichromats
# Authors@R: c(person(given = "Thomas", family = "Lumley", role = c("aut", "cre"), email = "tlumley@u.washington.edu"), person(given = "Ken", family = "Knoblauch", role = "ctb", email = "ken.knoblauch@inserm.fr"), person(given = "Scott", family = "Waichler", role = "ctb", email = "scott.waichler@pnl.gov"), person(given = "Achim", family = "Zeileis", role = "ctb", email = "Achim.Zeileis@R-project.org"))
# Description: Collapse red-green or green-blue distinctions to simulate the effects of different types of color-blindness.
# Depends: R (>= 2.10), stats
# License: GPL-2
# LazyLoad: Yes
# Packaged: 2013-01-23 06:25:04 UTC; zeileis
# Author: Thomas Lumley [aut, cre], Ken Knoblauch [ctb], Scott Waichler [ctb], Achim Zeileis [ctb]
# Maintainer: Thomas Lumley <tlumley@u.washington.edu>
# Repository: CRAN
# Date/Publication: 2013-01-24 08:18:09
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
