{% set version = '0.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-weatherdata
  version: {{ version|replace("-", "_") }}

source:
  fn: weatherData_0.5.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/weatherData_0.5.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/weatherData/weatherData_0.5.0.tar.gz  # [linux or win32]
  sha256: 49ff581367f13eeec1e04b9fafa4149b44660ce690dfa9c7944072034a3d40d0  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/weatherData_0.5.0.zip  # [win64]
  sha256: 82de05c53ae37b78535ca697c3a09658158e59698e75641f033e139bfb6b9601  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/weatherData_0.5.0.tgz  # [osx]
  sha256: c0724d57988fce6473287d0cd9edfcb40efdd4c543bdd42b17411724f7a20865  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:

  host:
    - mro-base
    - r-curl
    - r-plyr

  run:
    - mro-base
    - r-curl
    - r-plyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('weatherData')"           # [not win]
    - "\"%R%\" -e \"library('weatherData')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://ram-n.github.io/weatherData/
  license: GPL
  summary: Functions that help in fetching weather data from websites. Given a location and a
    date range, these functions help fetch weather data (temperature, pressure etc.)
    for any weather related analysis.
  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: weatherData
# Type: Package
# Title: Get Weather Data from the Web
# Description: Functions that help in fetching weather data from websites. Given a location and a date range, these functions help fetch weather data (temperature, pressure etc.) for any weather related analysis.
# URL: http://ram-n.github.io/weatherData/
# BugReports: https://github.com/ram-n/weatherData/issues
# Version: 0.5.0
# Date: 2017-05-16
# Authors@R: person("Ram", "Narasimhan", email = "ramnarasimhan@gmail.com", role = c("aut", "cre"))
# Suggests: testthat
# Depends: R (>= 2.10)
# Imports: curl, plyr, utils
# LazyData: TRUE
# License: GPL
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-06-05 20:11:46 UTC; Ram
# Author: Ram Narasimhan [aut, cre]
# Maintainer: Ram Narasimhan <ramnarasimhan@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-06-05 21:55:33 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
