{% set version = '1.8-22' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mgcv
  version: {{ version|replace("-", "_") }}

source:
  fn: mgcv_1.8-22.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/mgcv_1.8-22.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/mgcv/mgcv_1.8-22.tar.gz  # [linux or win32]
  sha256: 5a3bb235cc798f617392ef4996f2d502233998b041db2a68377f3cea94b98694  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/mgcv_1.8-22.zip  # [win64]
  sha256: 040f6bb149c4831afef8ef59754c3d457352b934ca0aa32ebe2b1b482b4a36ac  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/mgcv_1.8-22.tgz  # [osx]
  sha256: 36c4d885a69c0dccb7ef52df4e118382ef446117e12833eaea8f1e654d1d083a  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: splines, parallel, survival, MASS
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('fortran') }}    # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-matrix
    - r-nlme >=3.1_64

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-matrix
    - r-nlme >=3.1_64

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mgcv')"           # [not win]
    - "\"%R%\" -e \"library('mgcv')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mgcv
  license: GPL (>= 2)
  summary: Generalized additive (mixed) models, some of their extensions and  other generalized
    ridge regression with multiple smoothing  parameter estimation by (Restricted) Marginal
    Likelihood,  Generalized Cross Validation and similar. Includes a gam()  function,
    a wide variety of smoothers, JAGS support and  distributions beyond the exponential
    family.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mgcv
# Version: 1.8-22
# Author: Simon Wood <simon.wood@r-project.org>
# Maintainer: Simon Wood <simon.wood@r-project.org>
# Title: Mixed GAM Computation Vehicle with Automatic Smoothness Estimation
# Description: Generalized additive (mixed) models, some of their extensions and  other generalized ridge regression with multiple smoothing  parameter estimation by (Restricted) Marginal Likelihood,  Generalized Cross Validation and similar. Includes a gam()  function, a wide variety of smoothers, JAGS support and  distributions beyond the exponential family.
# Priority: recommended
# Depends: R (>= 2.14.0), nlme (>= 3.1-64)
# Imports: methods, stats, graphics, Matrix
# Suggests: splines, parallel, survival, MASS
# LazyLoad: yes
# ByteCompile: yes
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2017-09-18 10:38:41 UTC; sw283
# Repository: CRAN
# Date/Publication: 2017-09-19 00:27:56 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
