{% set version = '1.8-24' %}  # [linux or win32]
{% set version = '1.8-24' %}  # [win64]
{% set version = '1.8-24' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mgcv
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/mgcv_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/mgcv/mgcv_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 2ce542bcf841f722f34b936d44d859a53718a9de18ea24eb6ae843e042356795  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/mgcv_1.8-24.zip  # [win64]
  sha256: 51be651123f0c8c63afb30a008d1737394fe03b5dd352110989da7a84bb619a1  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/mgcv_1.8-24.tgz  # [osx and false]
  sha256: 4d31e113e973583f59128ee1d24921a3e3a0809ea17afdbc642780cc23bbe086  # [osx and false]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: splines, parallel, survival, MASS
requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{ compiler('fortran') }}  # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-matrix
    - r-nlme >=3.1_64

  run:
    - mro-base
    - r-matrix
    - r-nlme >=3.1_64
    - llvm-openmp                # [osx]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mgcv')"           # [not win]
    - "\"%R%\" -e \"library('mgcv')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mgcv
  license: GPL (>= 2)
  summary: Generalized additive (mixed) models, some of their extensions and  other generalized
    ridge regression with multiple smoothing  parameter estimation by (Restricted) Marginal
    Likelihood,  Generalized Cross Validation and similar. Includes a gam()  function,
    a wide variety of smoothers, JAGS support and  distributions beyond the exponential
    family.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mgcv
# Version: 1.8-24
# Author: Simon Wood <simon.wood@r-project.org>
# Maintainer: Simon Wood <simon.wood@r-project.org>
# Title: Mixed GAM Computation Vehicle with Automatic Smoothness Estimation
# Description: Generalized additive (mixed) models, some of their extensions and  other generalized ridge regression with multiple smoothing  parameter estimation by (Restricted) Marginal Likelihood,  Generalized Cross Validation and similar. Includes a gam()  function, a wide variety of smoothers, JAGS support and  distributions beyond the exponential family.
# Priority: recommended
# Depends: R (>= 2.14.0), nlme (>= 3.1-64)
# Imports: methods, stats, graphics, Matrix
# Suggests: splines, parallel, survival, MASS
# LazyLoad: yes
# ByteCompile: yes
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2018-06-18 13:08:20 UTC; sw283
# Repository: CRAN
# Date/Publication: 2018-06-18 19:07:59 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
