{% set version = '1.8-23' %}  # [linux or win32]
{% set version = '1.8-23' %}  # [win64]
{% set version = '1.8-23' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mgcv
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/mgcv_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/mgcv/mgcv_{{ version }}.tar.gz  # [linux or win32]
  sha256: 7771ac5581542904d569388e2e498d3e3b8b65f7a81737acbb45d8ef838359d3  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/mgcv_1.8-23.zip  # [win64]
  sha256: 358f1564f0862e267c077bb93d8b05b4b390a821476852aab5ed3161101a38d4  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/macosx/el-capitan/contrib/3.5/mgcv_1.8-23.tgz  # [osx]
  sha256: d490ca32422ffb0c37606295259c5c10d6379fb083ed2409756dfd6019dd8851  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: splines, parallel, survival, MASS
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]
    - {{posix}}sed               # [win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-matrix
    - r-nlme >=3.1_64

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-matrix
    - r-nlme >=3.1_64

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mgcv')"           # [not win]
    - "\"%R%\" -e \"library('mgcv')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mgcv
  license: GPL (>= 2)
  summary: Generalized additive (mixed) models, some of their extensions and  other generalized
    ridge regression with multiple smoothing  parameter estimation by (Restricted) Marginal
    Likelihood,  Generalized Cross Validation and similar. Includes a gam()  function,
    a wide variety of smoothers, JAGS support and  distributions beyond the exponential
    family.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mgcv
# Version: 1.8-23
# Author: Simon Wood <simon.wood@r-project.org>
# Maintainer: Simon Wood <simon.wood@r-project.org>
# Title: Mixed GAM Computation Vehicle with Automatic Smoothness Estimation
# Description: Generalized additive (mixed) models, some of their extensions and  other generalized ridge regression with multiple smoothing  parameter estimation by (Restricted) Marginal Likelihood,  Generalized Cross Validation and similar. Includes a gam()  function, a wide variety of smoothers, JAGS support and  distributions beyond the exponential family.
# Priority: recommended
# Depends: R (>= 2.14.0), nlme (>= 3.1-64)
# Imports: methods, stats, graphics, Matrix
# Suggests: splines, parallel, survival, MASS
# LazyLoad: yes
# ByteCompile: yes
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2018-01-08 15:15:43 UTC; sw283
# Repository: CRAN
# Date/Publication: 2018-01-15 00:23:36 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
