{% set version = '1.10.4-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-data.table
  version: {{ version|replace("-", "_") }}

source:
  fn: data.table_1.10.4-3.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/data.table_1.10.4-3.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/data.table/data.table_1.10.4-3.tar.gz  # [linux or win32]
  sha256: ba8b4f1b96b16e7f9765fc49c5028f21ef2210fc46cf962f4f7ea7901f9d8a89  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/data.table_1.10.4-3.zip  # [win64]
  sha256: 1d2a27e3f1f52ccf5de063cf74c24bf4f718437bb0ec199450c6e006c68d39fd  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/data.table_1.10.4-3.tgz  # [osx]
  sha256: 289e72a65df2b03559bc859a42c36e87a865c4ef38a9ead9c1b60aa08036294a  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bit64, knitr, nanotime, chron, ggplot2 (>= 0.9.0), plyr, reshape, reshape2, testthat (>= 0.4), hexbin, fastmatch, nlme, xts, gdata, GenomicRanges, caret, curl, zoo, plm, rmarkdown, parallel
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('data.table')"           # [not win]
    - "\"%R%\" -e \"library('data.table')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://r-datatable.com
  license: GPL-3 | file LICENSE
  summary: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete
    of columns by group using no copies at all, list columns, a fast friendly file reader
    and parallel file writer. Offers a natural and flexible syntax, for faster development.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: data.table
# Version: 1.10.4-3
# Title: Extension of `data.frame`
# Authors@R: c( person("Matt","Dowle",      role=c("aut","cre"), email="mattjdowle@gmail.com"), person("Arun","Srinivasan", role="aut", email="arunkumar.sriniv@gmail.com"), person("Jan","Gorecki",     role="ctb"), person("Tom","Short",       role="ctb"), person("Steve","Lianoglou", role="ctb"), person("Eduard","Antonyan", role="ctb") )
# Depends: R (>= 3.0.0)
# Imports: methods
# Suggests: bit64, knitr, nanotime, chron, ggplot2 (>= 0.9.0), plyr, reshape, reshape2, testthat (>= 0.4), hexbin, fastmatch, nlme, xts, gdata, GenomicRanges, caret, curl, zoo, plm, rmarkdown, parallel
# Description: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete of columns by group using no copies at all, list columns, a fast friendly file reader and parallel file writer. Offers a natural and flexible syntax, for faster development.
# License: GPL-3 | file LICENSE
# URL: http://r-datatable.com
# BugReports: https://github.com/Rdatatable/data.table/issues
# MailingList: datatable-help@lists.r-forge.r-project.org
# VignetteBuilder: knitr
# ByteCompile: TRUE
# NeedsCompilation: yes
# Packaged: 2017-10-19 21:11:19.239 UTC; mdowle
# Author: Matt Dowle [aut, cre], Arun Srinivasan [aut], Jan Gorecki [ctb], Tom Short [ctb], Steve Lianoglou [ctb], Eduard Antonyan [ctb]
# Maintainer: Matt Dowle <mattjdowle@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-10-27 07:40:34 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
