{% set version = '1.11.4' %}  # [linux or win32]
{% set version = '1.11.4' %}  # [win64]
{% set version = '1.11.4' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-data.table
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/data.table_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/data.table/data.table_{{ version }}.tar.gz  # [linux or win32]
  sha256: fdccf1dec3f38bb344163163decf3ffa0c0f8e2c70daa1bec8aac422716e81d5  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/data.table_1.11.4.zip  # [win64]
  sha256: 8dbd141e603b630fa7e351bb1c465e3877d2e69042fa056f190ba4712a7eb010  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/data.table_1.11.4.tgz  # [osx]
  sha256: a81d3b47452518bb430ea89c99f3845a63e36a0b2e839429c9d39c4f25a1e6f1  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bit64, curl, knitr, xts, nanotime, zoo, reshape2
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base
    - llvm-openmp                # [osx]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('data.table')"           # [not win]
    - "\"%R%\" -e \"library('data.table')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://r-datatable.com
  license: MPL-2.0 | file LICENSE
  summary: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete
    of columns by group using no copies at all, list columns, friendly and fast character-separated-value
    read/write. Offers a natural and flexible syntax, for faster development.
  license_family: OTHER

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: data.table
# Version: 1.11.4
# Title: Extension of `data.frame`
# Authors@R: c( person("Matt","Dowle",      role=c("aut","cre"), email="mattjdowle@gmail.com"), person("Arun","Srinivasan", role="aut", email="arunkumar.sriniv@gmail.com"), person("Jan","Gorecki",     role="ctb"), person("Michael","Chirico", role="ctb"), person("Pasha","Stetsenko", role="ctb"), person("Tom","Short",       role="ctb"), person("Steve","Lianoglou", role="ctb"), person("Eduard","Antonyan", role="ctb"), person("Markus","Bonsch",   role="ctb"), person("Hugh","Parsonage",  role="ctb"))
# Depends: R (>= 3.1.0)
# Imports: methods
# Suggests: bit64, curl, knitr, xts, nanotime, zoo, reshape2
# Description: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete of columns by group using no copies at all, list columns, friendly and fast character-separated-value read/write. Offers a natural and flexible syntax, for faster development.
# License: MPL-2.0 | file LICENSE
# URL: http://r-datatable.com
# BugReports: https://github.com/Rdatatable/data.table/issues
# VignetteBuilder: knitr
# ByteCompile: TRUE
# NeedsCompilation: yes
# Packaged: 2018-05-27 00:01:00.467 UTC; mdowle
# Author: Matt Dowle [aut, cre], Arun Srinivasan [aut], Jan Gorecki [ctb], Michael Chirico [ctb], Pasha Stetsenko [ctb], Tom Short [ctb], Steve Lianoglou [ctb], Eduard Antonyan [ctb], Markus Bonsch [ctb], Hugh Parsonage [ctb]
# Maintainer: Matt Dowle <mattjdowle@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-05-27 16:34:37 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
