{% set version = '0.8.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reshape
  version: {{ version|replace("-", "_") }}

source:
  fn: reshape_0.8.7.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/reshape_0.8.7.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/reshape/reshape_0.8.7.tar.gz  # [linux or win32]
  sha256: 2fa6c87d1e89f182e51bc5a4fcda3d42d83b8fb4474ca525fa7a8db5081f3992  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/reshape_0.8.7.zip  # [win64]
  sha256: 6f58050ba17a9bd082d5bb71f472722e9e98de890f6211699c4facdf08dc33b1  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/reshape_0.8.7.tgz  # [osx]
  sha256: 8109c670f2401809606d733c32575fd799eb17bf68017f856ec3a033908a5b8e  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:

  host:
    - mro-base
    - r-plyr

  run:
    - mro-base
    - r-plyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('reshape')"           # [not win]
    - "\"%R%\" -e \"library('reshape')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://had.co.nz/reshape
  license: MIT + file LICENSE
  summary: 'Flexibly restructure and aggregate data using  just two functions: melt and cast.'

  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: reshape
# Version: 0.8.7
# Title: Flexibly Reshape Data
# Description: Flexibly restructure and aggregate data using  just two functions: melt and cast.
# Authors@R:  person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre"))
# URL: http://had.co.nz/reshape
# Depends: R (>= 2.6.1)
# Imports: plyr
# License: MIT + file LICENSE
# LazyData: true
# NeedsCompilation: yes
# Packaged: 2017-08-04 16:36:57 UTC; hadley
# Author: Hadley Wickham [aut, cre]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-08-06 16:08:19 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
