{% set version = '0.8.7' %}  # [linux or win32]
{% set version = '0.8.7' %}  # [win64]
{% set version = '0.8.7' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reshape
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/reshape_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/reshape/reshape_{{ version }}.tar.gz  # [linux or win32]
  sha256: 2fa6c87d1e89f182e51bc5a4fcda3d42d83b8fb4474ca525fa7a8db5081f3992  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/reshape_0.8.7.zip  # [win64]
  sha256: 7185fbef32220c0a8887ef8ac4a307ad77a0bbfdd1ba65702bc05539afb19bb1  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/reshape_0.8.7.tgz  # [osx]
  sha256: 77fd80879b813f2c256824be5083763f8a78dc4b7b6491d4e62b485c93a0b86a  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-plyr

  run:
    - mro-base
    - r-plyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('reshape')"           # [not win]
    - "\"%R%\" -e \"library('reshape')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://had.co.nz/reshape
  license: MIT + file LICENSE
  summary: 'Flexibly restructure and aggregate data using  just two functions: melt and cast.'

  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: reshape
# Version: 0.8.7
# Title: Flexibly Reshape Data
# Description: Flexibly restructure and aggregate data using  just two functions: melt and cast.
# Authors@R:  person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre"))
# URL: http://had.co.nz/reshape
# Depends: R (>= 2.6.1)
# Imports: plyr
# License: MIT + file LICENSE
# LazyData: true
# NeedsCompilation: yes
# Packaged: 2017-08-04 16:36:57 UTC; hadley
# Author: Hadley Wickham [aut, cre]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-08-06 16:08:19 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
