{% set version = '2018.04.18' %}  # [linux or win32 or osx]
{% set version = '2018.04.18' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prodlim
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/prodlim_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/prodlim/prodlim_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 4b22b54fdf712439309be0ff74f63cde9080464667b00e19823372ac0fc254ab  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/prodlim_2018.04.18.zip  # [win64]
  sha256: 8bb0139d0971a8331bb2d440fff9414f10de204f9891f3fc6c6f9d1ee7c42cf0  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{ compiler('cxx') }}      # [linux or osx]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32 or osx]
    - {{posix}}sed               # [win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-kernsmooth
    - r-rcpp >=0.11.5
    - r-lava
    - r-survival

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-kernsmooth
    - r-rcpp >=0.11.5
    - r-lava
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('prodlim')"           # [not win]
    - "\"%R%\" -e \"library('prodlim')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=prodlim
  license: GPL (>= 2)
  summary: Fast and user friendly implementation of nonparametric estimators for censored event
    history (survival) analysis. Kaplan-Meier and Aalen-Johansen method.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: prodlim
# Title: Product-Limit Estimation for Censored Event History Analysis
# Version: 2018.04.18
# Author: Thomas A. Gerds
# Description: Fast and user friendly implementation of nonparametric estimators for censored event history (survival) analysis. Kaplan-Meier and Aalen-Johansen method.
# Depends: R (>= 2.9.0)
# Imports: Rcpp (>= 0.11.5), stats, graphics, survival, KernSmooth, lava
# LinkingTo: Rcpp
# Maintainer: Thomas A. Gerds <tag@biostat.ku.dk>
# License: GPL (>= 2)
# Packaged: 2018-04-18 06:30:07 UTC; tag
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2018-04-18 08:19:40 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
