{% set version = '0.1.1' %}  # [linux or win32]
{% set version = '0.1.1' %}  # [win64]
{% set version = '0.1.1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mro
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/mro_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/mro/mro_{{ version }}.tar.gz  # [linux or win32]
  sha256: 5bde16b8be778ef79e86cba87aeb1f88f61738c68c32ae73170b168c1a14ec01  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/mro_0.1.1.zip  # [win64]
  sha256: 57c919f5bb1864d5c521df1b2b06cca88f5a2081bd531268c8a2cedb84b48cf2  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/mro_0.1.1.tgz  # [osx]
  sha256: d5ab3e381f477f91c78e46661f7b4c513da085d6c8e646bc534e8834f95f2a5f  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-mass
    - r-matrixcalc

  run:
    - mro-base
    - r-mass
    - r-matrixcalc

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mro')"           # [not win]
    - "\"%R%\" -e \"library('mro')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mro
  license: GPL-2
  summary: Computes multiple correlation coefficient when the data matrix is given and tests
    its significance.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mro
# Type: Package
# Title: Multiple Correlation
# Version: 0.1.1
# Author: Abirami S
# Maintainer: Abirami S <abirami89@gmail.com>
# Description: Computes multiple correlation coefficient when the data matrix is given and tests its significance.
# Depends: R (>= 3.1.0), MASS,matrixcalc
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-04-16 15:29:21 UTC; Sampath
# Repository: CRAN
# Date/Publication: 2017-04-16 16:24:55 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
