{% set version = '0.1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mro
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mro_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mro/mro_{{ version }}.tar.gz
  sha256: 5bde16b8be778ef79e86cba87aeb1f88f61738c68c32ae73170b168c1a14ec01

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{native}}rtools           # [win]
    - {{posix}}zip               # [win]

  host:
    - mro-base
    - r-mass
    - r-matrixcalc

  run:
    - mro-base
    - r-mass
    - r-matrixcalc

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mro')"           # [not win]
    - "\"%R%\" -e \"library('mro')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mro
  license: GPL-2
  summary: Computes multiple correlation coefficient when the data matrix is given and tests
    its significance.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mro
# Type: Package
# Title: Multiple Correlation
# Version: 0.1.1
# Author: Abirami S
# Maintainer: Abirami S <abirami89@gmail.com>
# Description: Computes multiple correlation coefficient when the data matrix is given and tests its significance.
# Depends: R (>= 3.1.0), MASS,matrixcalc
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-04-16 15:29:21 UTC; Sampath
# Repository: CRAN
# Date/Publication: 2017-04-16 16:24:55 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
