{% set version = '0.5-13.1' %}  # [linux or win32 or osx]
{% set version = '0.5-13.1' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gmp
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/gmp_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/gmp/gmp_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 2f805374a26742cd43f6b2054130d8670eda1940070aabb9971e9e48226d0976  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/gmp_0.5-13.1.zip  # [win64]
  sha256: 6498063ac3e7f4b5748a92ef9619c70922c2abcf3d9722fc8a17a120562b64ca  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: Rmpfr
requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{ compiler('cxx') }}      # [linux or osx]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}sed               # [win32]
    - {{posix}}grep              # [win32]
    - {{posix}}autoconf          # [linux or win32 or osx]
    - {{posix}}automake          # [linux or osx]
    - {{posix}}automake-wrapper  # [win32]
    - {{posix}}pkg-config
    - {{posix}}make              # [linux or win32 or osx]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gmp')"           # [not win]
    - "\"%R%\" -e \"library('gmp')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://mulcyber.toulouse.inra.fr/projects/gmp
  license: GPL
  summary: Multiple Precision Arithmetic (big integers and rationals, prime number tests, matrix
    computation), "arithmetic without limitations" using the C library GMP (GNU Multiple
    Precision Arithmetic).
  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: gmp
# Version: 0.5-13.1
# Date: 2017-01-02
# Title: Multiple Precision Arithmetic
# Author: Antoine Lucas, Immanuel Scholz, Rainer Boehme <rb-gmp@reflex-studio.de>, Sylvain Jasson <jasson@toulouse.inra.fr>, Martin Maechler <maechler@stat.math.ethz.ch>
# Maintainer: Antoine Lucas <antoinelucas@gmail.com>
# Description: Multiple Precision Arithmetic (big integers and rationals, prime number tests, matrix computation), "arithmetic without limitations" using the C library GMP (GNU Multiple Precision Arithmetic).
# Depends: R (>= 3.0.0)
# Imports: methods
# Suggests: Rmpfr
# SystemRequirements: gmp (>= 4.2.3)
# License: GPL
# BuildResaveData: no
# LazyDataNote: not available, as we use data/*.R *and* our classes
# URL: http://mulcyber.toulouse.inra.fr/projects/gmp
# NeedsCompilation: yes
# Packaged: 2017-03-10 06:58:47 UTC; ripley
# Repository: CRAN
# Date/Publication: 2017-03-10 08:05:38

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
