{% set version = '0.8-4' %}  # [linux or win32 or osx]
{% set version = '0.8-4' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ctv
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/ctv_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/ctv/ctv_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 62ad5dece279d43519257e42aaf98cb7efa834071b1b0c5e58213024c302827a  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/ctv_0.8-4.zip  # [win64]
  sha256: 478f73ed86d269ae72b5a1d684789c7a22bbae83a4a9d6444a5a0c1d81875df7  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: XML
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ctv')"           # [not win]
    - "\"%R%\" -e \"library('ctv')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=ctv
  license: GPL-2 | GPL-3
  summary: 'Infrastructure for task views to CRAN-style repositories: Querying task views and
    installing the associated packages (client-side tools), generating HTML pages and
    storing task view information in the repository (server-side tools).'

  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: ctv
# Version: 0.8-4
# Date: 2018-01-18
# Title: CRAN Task Views
# Authors@R: c(person(given = "Achim", family = "Zeileis", role = c("aut", "cre"), email = "Achim.Zeileis@R-project.org", comment = c(ORCID = "0000-0003-0918-3766")), person(given = "Kurt", family = "Hornik", role = "aut", email = "Kurt.Hornik@R-project.org", comment = c(ORCID = "0000-0003-4198-9911")))
# Description: Infrastructure for task views to CRAN-style repositories: Querying task views and installing the associated packages (client-side tools), generating HTML pages and storing task view information in the repository (server-side tools).
# Depends: R (>= 2.13.0), utils
# Suggests: XML
# License: GPL-2 | GPL-3
# NeedsCompilation: no
# Packaged: 2018-01-18 22:02:41 UTC; zeileis
# Author: Achim Zeileis [aut, cre] (0000-0003-0918-3766), Kurt Hornik [aut] (0000-0003-4198-9911)
# Maintainer: Achim Zeileis <Achim.Zeileis@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-01-18 22:15:52 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
