{% set version = '1.4-2' %}  # [linux or win32]
{% set version = '1.4-2' %}  # [win64]
{% set version = '1.4-2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fracdiff
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/fracdiff_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/fracdiff/fracdiff_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 983781cedc2b4e3ba9fa020213957d5133ae9cd6710bc61d6225728e2f6e850e  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/fracdiff_1.4-2.zip  # [win64]
  sha256: 72d07050351b82ddf87ed71686264e0662184108d72bb15bdfa8d32799681105  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/fracdiff_1.4-2.tgz  # [osx and false]
  sha256: 566912673a48c23685ad5d63636f014f7fb66ed194545851c9dc583ecd3c9e61  # [osx and false]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: longmemo, urca
requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{ compiler('fortran') }}  # [osx]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('fracdiff')"           # [not win]
    - "\"%R%\" -e \"library('fracdiff')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=fracdiff
  license: GPL (>= 2)
  summary: Maximum likelihood estimation of the parameters of a fractionally differenced ARIMA(p,d,q)
    model (Haslett and Raftery, Appl.Statistics, 1989).
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: fracdiff
# Version: 1.4-2
# Date: 2012-12-01
# Title: Fractionally differenced ARIMA aka ARFIMA(p,d,q) models
# Author: S original by Chris Fraley, U.Washington, Seattle.  R port by Fritz Leisch at TU Wien; since 2003-12: Martin Maechler; fdGPH(), fdSperio(), etc by Valderio Reisen and Artur Lemonte.
# Maintainer: Martin Maechler <maechler@stat.math.ethz.ch>
# Description: Maximum likelihood estimation of the parameters of a fractionally differenced ARIMA(p,d,q) model (Haslett and Raftery, Appl.Statistics, 1989).
# Suggests: longmemo, urca
# License: GPL (>= 2)
# Packaged: 2012-12-01 23:24:14 UTC; maechler
# Repository: CRAN
# Date/Publication: 2012-12-02 07:08:12
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
