{% set version = '0.3.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-profvis
  version: {{ version|replace("-", "_") }}

source:
  fn: profvis_0.3.4.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/profvis_0.3.4.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/profvis/profvis_0.3.4.tar.gz  # [linux or win32]
  sha256: f0d7d581793eb61190cdc91f4db97bf4afa2c806c54837cd849629d81f41a14f  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/profvis_0.3.4.zip  # [win64]
  sha256: 5acf6dc848fa172a29046b9ff08a37919400889a09b371dd7a82697f58ea7cab  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/profvis_0.3.4.tgz  # [osx]
  sha256: c0a4a766e5e753d9ebddd9b624e96439cfae1898d4754222bdebd24447d4d063  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, ggplot2, rmarkdown, testthat, devtools
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-htmlwidgets >=0.3.2
    - r-stringr

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-htmlwidgets >=0.3.2
    - r-stringr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('profvis')"           # [not win]
    - "\"%R%\" -e \"library('profvis')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://rstudio.github.io/profvis/
  license: GPL-3 | file LICENSE
  summary: Interactive visualizations for profiling R code.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: profvis
# Title: Interactive Visualizations for Profiling R Code
# Version: 0.3.4
# Authors@R: c( person("Winston", "Chang", email = "winston@rstudio.com", role = c("aut", "cre")), person("Javier", "Luraschi", email = "javier@rstudio.com", role = "aut"), person(family = "RStudio", role = "cph"), person(family = "jQuery Foundation", role = "cph", comment = "jQuery library"), person(family = "jQuery contributors", role = c("ctb", "cph"), comment = "jQuery library; authors listed in inst/www/shared/jquery-AUTHORS.txt"), person("Mike", "Bostock", role = c("ctb", "cph"), comment = "D3 library"), person(family = "D3 contributors", role = "ctb", comment = "D3 library"), person("Ivan", "Sagalaev", role = c("ctb", "cph"), comment = "highlight.js library") )
# Description: Interactive visualizations for profiling R code.
# Depends: R (>= 3.0)
# Imports: htmlwidgets (>= 0.3.2), stringr
# License: GPL-3 | file LICENSE
# Suggests: knitr, ggplot2, rmarkdown, testthat, devtools
# RoxygenNote: 6.0.1.9000
# URL: https://rstudio.github.io/profvis/
# NeedsCompilation: yes
# Packaged: 2017-12-12 17:04:24 UTC; winston
# Author: Winston Chang [aut, cre], Javier Luraschi [aut], RStudio [cph], jQuery Foundation [cph] (jQuery library), jQuery contributors [ctb, cph] (jQuery library; authors listed in inst/www/shared/jquery-AUTHORS.txt), Mike Bostock [ctb, cph] (D3 library), D3 contributors [ctb] (D3 library), Ivan Sagalaev [ctb, cph] (highlight.js library)
# Maintainer: Winston Chang <winston@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-12-12 17:29:00 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
