{% set version = '1.20.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-getopt
  version: {{ version|replace("-", "_") }}

source:
  fn: getopt_1.20.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/getopt_1.20.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/getopt/getopt_1.20.1.tar.gz  # [linux or win32]
  sha256: 1522c35b13e8546979725a68b75e3bc9d156fb06569067472405f6b8591d8654  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/getopt_1.20.1.zip  # [win64]
  sha256: 6fe7bbe1fb61c14a93946b122416a4a4747376dae49dfa309c2fba323b49392a  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/getopt_1.20.1.tgz  # [osx]
  sha256: 3690322040073a145cef3eee9566eee00fab3dbd836f7b55f2ce5f038adc2453  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('getopt')"           # [not win]
    - "\"%R%\" -e \"library('getopt')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/trevorld/getopt
  license: GPL (>= 2)
  summary: Package designed to be used with Rscript to write ``#!'' shebang scripts that accept
    short and long flags/options. Many users will prefer using instead the packages
    optparse or argparse which add extra features like automatically generated help
    option and usage, support for default values, positional argument support, etc.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: getopt
# Type: Package
# Title: C-Like 'getopt' Behavior
# Version: 1.20.1
# Author: Allen Day. Contributions from Trevor L Davis and Roman Zenka.
# Maintainer: Trevor L Davis <trevor.l.davis@gmail.com>
# URL: https://github.com/trevorld/getopt
# Imports: stats
# BugReports: https://github.com/trevorld/getopt/issues
# Description: Package designed to be used with Rscript to write ``#!'' shebang scripts that accept short and long flags/options. Many users will prefer using instead the packages optparse or argparse which add extra features like automatically generated help option and usage, support for default values, positional argument support, etc.
# License: GPL (>= 2)
# Suggests: testthat
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-11-29 22:23:04 UTC; trevorld
# Repository: CRAN
# Date/Publication: 2017-11-29 23:47:17 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
