{% set version = '0.4-13' %}  # [linux or win32]
{% set version = '0.4-13' %}  # [win64]
{% set version = '0.4-13' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quantmod
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/quantmod_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/quantmod/quantmod_{{ version }}.tar.gz  # [linux or win32]
  sha256: 60fb13821c9d8d5bea34223b18757f04787f4440cb82946bb9559d6fd26b5499  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/quantmod_0.4-13.zip  # [win64]
  sha256: 0e3b652d079938688ceb7b7609c2a2f37c4caacf5430652e17752e940a1150f4  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/quantmod_0.4-13.tgz  # [osx]
  sha256: d17d7fc7e375bf7efa9d96e5a67c7209e31d6b51c0e7747084f075add2d3332a  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: DBI,RMySQL,RSQLite,timeSeries,XML,downloader,jsonlite(>= 1.1)
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-ttr >=0.2
    - r-curl
    - r-xts >=0.9_0
    - r-zoo

  run:
    - mro-base
    - r-ttr >=0.2
    - r-curl
    - r-xts >=0.9_0
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('quantmod')"           # [not win]
    - "\"%R%\" -e \"library('quantmod')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.quantmod.com https://github.com/joshuaulrich/quantmod
  license: GPL-3
  summary: Specify, build, trade, and analyse quantitative financial trading strategies.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: quantmod
# Type: Package
# Title: Quantitative Financial Modelling Framework
# Version: 0.4-13
# Date: 2018-04-10
# Authors@R: c( person(given=c("Jeffrey","A."), family="Ryan", role=c("aut","cph")), person(given=c("Joshua","M."), family="Ulrich", role=c("cre","aut"), email="josh.m.ulrich@gmail.com"), person(given="Wouter", family="Thielen", role="ctb"), person(given="Paul", family="Teetor", role="ctb"), person(given="Steve", family="Bronder", role="ctb") )
# Depends: R (>= 3.2.0), xts(>= 0.9-0), zoo, TTR(>= 0.2), methods
# Imports: curl
# Suggests: DBI,RMySQL,RSQLite,timeSeries,XML,downloader,jsonlite(>= 1.1)
# Description: Specify, build, trade, and analyse quantitative financial trading strategies.
# LazyLoad: yes
# License: GPL-3
# URL: http://www.quantmod.com https://github.com/joshuaulrich/quantmod
# BugReports: https://github.com/joshuaulrich/quantmod/issues
# NeedsCompilation: no
# Packaged: 2018-04-10 13:06:19 UTC; josh
# Author: Jeffrey A. Ryan [aut, cph], Joshua M. Ulrich [cre, aut], Wouter Thielen [ctb], Paul Teetor [ctb], Steve Bronder [ctb]
# Maintainer: Joshua M. Ulrich <josh.m.ulrich@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-04-13 12:36:34 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
