{% set version = '0.3.6' %}  # [linux or win32]
{% set version = '0.3.6' %}  # [win64]
{% set version = '0.3.6' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmltools
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/htmltools_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/htmltools/htmltools_{{ version }}.tar.gz  # [linux or win32]
  sha256: 44affb82f9c2fd76c9e2b58f9229adb003217932b68c3fdbf1327c8d74c868a2  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/htmltools_0.3.6.zip  # [win64]
  sha256: 6f14d1fd902b73db0f0e9a2bfd5cfe1e1df3b3a5054df400b357225643eabd7d  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/htmltools_0.3.6.tgz  # [osx]
  sha256: 7aab1f514945fc41009958bf305a612e694b5812cd596b1a71414adbe7e1ac53  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: markdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-rcpp
    - r-digest

  run:
    - mro-base
    - r-rcpp
    - r-digest
    - libcxx >=4.0.1             # [osx]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('htmltools')"           # [not win]
    - "\"%R%\" -e \"library('htmltools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstudio/htmltools
  license: GPL (>= 2)
  summary: Tools for HTML generation and output.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: htmltools
# Type: Package
# Title: Tools for HTML
# Version: 0.3.6
# Date: 2017-04-26
# Author: RStudio, Inc.
# Maintainer: Joe Cheng <joe@rstudio.com>
# Description: Tools for HTML generation and output.
# Depends: R (>= 2.14.1)
# Imports: utils, digest, Rcpp
# Suggests: markdown, testthat
# Enhances: knitr
# License: GPL (>= 2)
# URL: https://github.com/rstudio/htmltools
# BugReports: https://github.com/rstudio/htmltools/issues
# RoxygenNote: 6.0.1
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2017-04-27 00:04:32 UTC; jcheng
# Repository: CRAN
# Date/Publication: 2017-04-28 07:41:46 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
