{% set version = '0.8' %}  # [linux or win32]
{% set version = '0.8' %}  # [win64]
{% set version = '0.8' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-markdown
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/markdown_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/markdown/markdown_{{ version }}.tar.gz  # [linux or win32]
  sha256: 538fd912b2220f2df344c6cca58304ce11e0960de7bd7bd573b3385105d48fed  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/markdown_0.8.zip  # [win64]
  sha256: e35d0452f8d2b3ce2c3c4a6ce09a56fc0e6ff75e54eed184867f3cd2effe0a5d  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/markdown_0.8.tgz  # [osx]
  sha256: aae33cf1c86cf1150a011b1e27c5c8ab5c4648c91a1b96d3ddf7bdf6d7dec1fd  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, RCurl
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]
    - {{posix}}sed               # [win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-mime >=0.3

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-mime >=0.3

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('markdown')"           # [not win]
    - "\"%R%\" -e \"library('markdown')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstudio/markdown
  license: GPL-2
  summary: Provides R bindings to the 'Sundown' 'Markdown' rendering library (https://github.com/vmg/sundown).
    'Markdown' is a plain-text formatting syntax that can be converted to 'XHTML' or
    other formats. See http://en.wikipedia.org/wiki/Markdown for more information about
    'Markdown'.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: markdown
# Type: Package
# Title: 'Markdown' Rendering for R
# Version: 0.8
# Date: 2017-04-20
# Authors@R: c( person("JJ", "Allaire", role = "aut"), person("Jeffrey", "Horner", role = "aut"), person("Henrik", "Bengtsson", role = "ctb"), person("Jim", "Hester", role = "ctb"), person("Yixuan", "Qiu", role = "ctb"), person("Kohske", "Takahashi", role = "ctb"), person("Adam", "November", role = "ctb"), person("Nacho", "Caballero", role = "ctb"), person("Jeroen", "Ooms", role = "ctb"), person("Thomas", "Leeper", role = "ctb"), person("Joe", "Cheng", role = "ctb"), person("Andrzej", "Oles", role = "ctb"), person("Vicent", "Marti", role = c("aut", "cph"), comment = "The Sundown library"), person("Natacha", "Porte", role = c("aut", "cph"), comment = "The Sundown library"), person(family = "RStudio", role = "cph"), person("Yihui", "Xie", role = c("cre", "ctb"), email = "xie@yihui.name") )
# Description: Provides R bindings to the 'Sundown' 'Markdown' rendering library (https://github.com/vmg/sundown). 'Markdown' is a plain-text formatting syntax that can be converted to 'XHTML' or other formats. See http://en.wikipedia.org/wiki/Markdown for more information about 'Markdown'.
# Depends: R (>= 2.11.1)
# Imports: utils, mime (>= 0.3)
# Suggests: knitr, RCurl
# License: GPL-2
# URL: https://github.com/rstudio/markdown
# BugReports: https://github.com/rstudio/markdown/issues
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-04-19 20:14:01 UTC; yihui
# Author: JJ Allaire [aut], Jeffrey Horner [aut], Henrik Bengtsson [ctb], Jim Hester [ctb], Yixuan Qiu [ctb], Kohske Takahashi [ctb], Adam November [ctb], Nacho Caballero [ctb], Jeroen Ooms [ctb], Thomas Leeper [ctb], Joe Cheng [ctb], Andrzej Oles [ctb], Vicent Marti [aut, cph] (The Sundown library), Natacha Porte [aut, cph] (The Sundown library), RStudio [cph], Yihui Xie [cre, ctb]
# Maintainer: Yihui Xie <xie@yihui.name>
# Repository: CRAN
# Date/Publication: 2017-04-20 09:07:54 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
