{% set version = '1.2' %}  # [linux or win32]
{% set version = '1.2' %}  # [win64]
{% set version = '1.2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lars
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/lars_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/lars/lars_{{ version }}.tar.gz  # [linux or win32]
  sha256: 64745b568f20b2cfdae3dad02fba92ebf78ffee466a71aaaafd4f48c3921922e  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/lars_1.2.zip  # [win64]
  sha256: dea2234f0a56172a68887426af976ba56ae2fbbe49103b354aaf18cb062ec44c  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/lars_1.2.tgz  # [osx]
  sha256: aa8ca00dffd6a2a25794b3d575a1342e5848a76d290b431b0f7ae211962e9a73  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('fortran') }}  # [linux or osx]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lars')"           # [not win]
    - "\"%R%\" -e \"library('lars')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www-stat.stanford.edu/~hastie/Papers/#LARS
  license: GPL-2
  summary: Efficient procedures for fitting an entire lasso sequence with the cost of a single
    least squares fit. Least angle regression and infinitesimal forward stagewise regression
    are related to the lasso, as described in the paper below.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: lars
# Type: Package
# Version: 1.2
# Date: 2013-04-23
# Title: Least Angle Regression, Lasso and Forward Stagewise
# Author: Trevor Hastie <hastie@stanford.edu> and Brad Efron <brad@stat.stanford.edu>
# Maintainer: Trevor Hastie <hastie@stanford.edu>
# Description: Efficient procedures for fitting an entire lasso sequence with the cost of a single least squares fit. Least angle regression and infinitesimal forward stagewise regression are related to the lasso, as described in the paper below.
# Depends: R (>= 2.10)
# License: GPL-2
# URL: http://www-stat.stanford.edu/~hastie/Papers/#LARS
# Packaged: 2013-04-24 05:12:53 UTC; hastie
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2013-04-24 09:46:12

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
