{% set version = '6.0-0' %}  # [linux or win32 or osx]
{% set version = '6.0-0' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lahman
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Lahman_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/Lahman/Lahman_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 6662a3674adc274aed42d6769fea3c6b0cc95561d1d6bd59cfdc7c24948a2698  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/Lahman_6.0-0.zip  # [win64]
  sha256: e71df0f39e423834ccbfd2e965a6ef2a9acc830cd24b47e799a43ed7d87dce65  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: lattice, ggplot2, googleVis, data.table, vcd, reshape2, tidyr, zipcode
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-dplyr

  run:
    - mro-base
    - r-dplyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('Lahman')"           # [not win]
    - "\"%R%\" -e \"library('Lahman')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://lahman.r-forge.r-project.org/
  license: GPL
  summary: Provides the tables from the 'Sean Lahman Baseball Database' as a set of R data.frames.
    It uses the data on pitching, hitting and fielding performance and other tables
    from 1871 through 2015, as recorded in the 2016 version of the database.
  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: Lahman
# Type: Package
# Title: Sean 'Lahman' Baseball Database
# Version: 6.0-0
# Date: 2017-08-07
# Authors@R: c(person(given = "Michael", family = "Friendly", role="aut", email="friendly@yorku.ca"),  person(given= "Dennis", family = "Murphy", role="ctb"),  person(given ="Martin", family = "Monkman", role="ctb"), person(given ="Chris", family = "Dalzell", role=c("cre","ctb"), email="cdalzell@gmail.com"))
# Author: Michael Friendly [aut], Dennis Murphy [ctb], Martin Monkman [ctb], Chris Dalzell [cre, ctb]
# Maintainer: Chris Dalzell <cdalzell@gmail.com>
# Description: Provides the tables from the 'Sean Lahman Baseball Database' as a set of R data.frames. It uses the data on pitching, hitting and fielding performance and other tables from 1871 through 2015, as recorded in the 2016 version of the database.
# Depends: R (>= 2.10)
# Suggests: lattice, ggplot2, googleVis, data.table, vcd, reshape2, tidyr, zipcode
# Imports: dplyr
# License: GPL
# URL: http://lahman.r-forge.r-project.org/
# LazyLoad: yes
# LazyData: yes
# Repository: CRAN
# Repository/R-Forge/Project: lahman
# Repository/R-Forge/Revision: 39
# Repository/R-Forge/DateTimeStamp: 2013-06-01 03:33:30
# Date/Publication: 2017-08-15 05:14:24 UTC
# Packaged: 2017-08-15 01:17:49 UTC; dz
# NeedsCompilation: no
# RoxygenNote: 6.0.1

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
