{% set version = '0.10-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xts
  version: {{ version|replace("-", "_") }}

source:
  fn: xts_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/xts_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/xts/xts_{{ version }}.tar.gz  # [linux or win32]
  sha256: 8155888319c38e874ed87300decd65570e77ea4a7575136f4690123d3f7321c4  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/xts_0.10-2.zip  # [win64]
  sha256: d54d6eb0a7f08c35c1e6b383c173c78ef2783b21f342deb5e463ba1b1af870f1  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/xts_0.10-2.tgz  # [osx]
  sha256: 18daa71947232ec6a0950e698b6045d7c75e6ed6075ae200618ea3c2d04531de  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: timeSeries, timeDate, tseries, chron, fts, tis, RUnit
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]

  host:
    - mro-base
    - r-zoo >=1.7_12

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-zoo >=1.7_12

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('xts')"           # [not win]
    - "\"%R%\" -e \"library('xts')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/joshuaulrich/xts
  license: GPL (>= 2)
  summary: Provide for uniform handling of R's different time-based data classes by extending
    zoo, maximizing native format information preservation and allowing for user level
    customization and extension, while simplifying cross-class interoperability.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: xts
# Type: Package
# Title: eXtensible Time Series
# Version: 0.10-2
# Date: 2018-03-13
# Authors@R: c( person(given=c("Jeffrey","A."), family="Ryan", role=c("aut","cph")), person(given=c("Joshua","M."), family="Ulrich", role=c("cre","aut"), email="josh.m.ulrich@gmail.com"), person(given="Ross", family="Bennett", role="ctb") )
# Depends: zoo (>= 1.7-12)
# Imports: methods
# LinkingTo: zoo
# Suggests: timeSeries, timeDate, tseries, chron, fts, tis, RUnit
# LazyLoad: yes
# Description: Provide for uniform handling of R's different time-based data classes by extending zoo, maximizing native format information preservation and allowing for user level customization and extension, while simplifying cross-class interoperability.
# License: GPL (>= 2)
# URL: https://github.com/joshuaulrich/xts
# BugReports: https://github.com/joshuaulrich/xts/issues
# NeedsCompilation: yes
# Packaged: 2018-03-14 16:45:50 UTC; josh
# Author: Jeffrey A. Ryan [aut, cph], Joshua M. Ulrich [cre, aut], Ross Bennett [ctb]
# Maintainer: Joshua M. Ulrich <josh.m.ulrich@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-03-14 23:36:18 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
