{% set version = '0.37' %}  # [linux or win32]
{% set version = '0.37' %}  # [win64]
{% set version = '0.37' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bestglm
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/bestglm_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/bestglm/bestglm_{{ version }}.tar.gz  # [linux or win32]
  sha256: 9f268572dea45b9da5850a8e7d5a88628462344281ef3ced15f8d5721e89103e  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/bestglm_0.37.zip  # [win64]
  sha256: a2c6b94ab06707a690dab9d8d5cf7a3a6022c04944df3f86bfe2f93a59d427f6  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/bestglm_0.37.tgz  # [osx]
  sha256: 5e3b73e72fbba8533178478d3c40830c7a086e561b349f818442b48fdf93c9a0  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-glmnet
    - r-grpreg
    - r-lattice
    - r-leaps
    - r-pls

  run:
    - mro-base
    - r-glmnet
    - r-grpreg
    - r-lattice
    - r-leaps
    - r-pls

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bestglm')"           # [not win]
    - "\"%R%\" -e \"library('bestglm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.stats.uwo.ca/faculty/aim
  license: GPL (>= 2)
  summary: Best subset glm using information criteria or cross-validation. Implements PCR and
    PLS using AIC/BIC. Implements one-standard deviation rule for use with the `caret`
    package.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: bestglm
# Type: Package
# Title: Best Subset GLM and Regression Utilities
# Version: 0.37
# Date: 2018-05-27
# Author: A.I. McLeod  and Changjiang Xu
# Maintainer: A.I. McLeod <aimcleod@uwo.ca>
# Depends: R (>= 2.0.0), leaps
# Suggests: MASS
# Imports: lattice, glmnet, grpreg, pls
# Enhances: caret
# Description: Best subset glm using information criteria or cross-validation. Implements PCR and PLS using AIC/BIC. Implements one-standard deviation rule for use with the `caret` package.
# LazyLoad: yes
# LazyData: yes
# Classification/ACM: G.3, G.4, I.5.1
# Classification/MSC: 62M10, 91B84
# License: GPL (>= 2)
# URL: http://www.stats.uwo.ca/faculty/aim
# NeedsCompilation: yes
# Packaged: 2018-05-27 19:27:22 UTC; IanMcLeod
# Repository: CRAN
# Date/Publication: 2018-05-27 21:03:04 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
