{% set version = '0.7' %}  # [linux or win32]
{% set version = '0.7' %}  # [win64]
{% set version = '0.7' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-highr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/highr_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/highr/highr_{{ version }}.tar.gz  # [linux or win32]
  sha256: cabba5b6f2ea82024a49c5ced5f1aa476f864bc52bc129038e319e4e26b6f3b7  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/highr_0.7.zip  # [win64]
  sha256: e64685d9887cbfb5b32394989743a07a69855f830c2b480f40b547daad0c7053  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/highr_0.7.tgz  # [osx]
  sha256: db4fc61adbdc616abb12986a70c3764a0fb36dfdf7cd633d7e654a8de4a18570  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testit
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('highr')"           # [not win]
    - "\"%R%\" -e \"library('highr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/yihui/highr
  license: GPL
  summary: Provides syntax highlighting for R source code. Currently it supports LaTeX and HTML
    output. Source code of other languages is supported via Andre Simon's highlight
    package (<http://www.andre-simon.de>).
  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: highr
# Type: Package
# Title: Syntax Highlighting for R Source Code
# Version: 0.7
# Authors@R: c(person("Christopher", "Gandrud", role = "ctb"), person("Qiang", "Li", role = "ctb"), person("Yixuan", "Qiu", role = "aut"), person("Yihui", "Xie", email = "xie@yihui.name", role = c("aut", "cre")))
# Maintainer: Yihui Xie <xie@yihui.name>
# Description: Provides syntax highlighting for R source code. Currently it supports LaTeX and HTML output. Source code of other languages is supported via Andre Simon's highlight package (<http://www.andre-simon.de>).
# Depends: R (>= 3.0.2)
# Suggests: knitr, testit
# License: GPL
# URL: https://github.com/yihui/highr
# BugReports: https://github.com/yihui/highr/issues
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-06-09 07:37:11 UTC; yihui
# Author: Christopher Gandrud [ctb], Qiang Li [ctb], Yixuan Qiu [aut], Yihui Xie [aut, cre]
# Repository: CRAN
# Date/Publication: 2018-06-09 15:46:28 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
