{% set version = '1.0-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlmrev
  version: {{ version|replace("-", "_") }}

source:
  fn: mlmRev_1.0-6.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/mlmRev_1.0-6.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/mlmRev/mlmRev_1.0-6.tar.gz  # [linux or win32]
  sha256: 0796b6be29f162f6fa1bc41ca0a153649315a5a69cc846794787dcb52c547557  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/mlmRev_1.0-6.zip  # [win64]
  sha256: 0f7defdc28757ad8482d36be8828941df937e72bf628439d0b19de4c49dce2a9  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/mlmRev_1.0-6.tgz  # [osx]
  sha256: ae8e6b50ee603b12b2a2343d3d931c7266325ede1026b1594d04bd2aafc21a8f  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: lattice
requirements:
  build:

  host:
    - mro-base
    - r-lme4

  run:
    - mro-base
    - r-lme4

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mlmRev')"           # [not win]
    - "\"%R%\" -e \"library('mlmRev')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mlmRev
  license: GPL (>= 2)
  summary: Data and examples from a multilevel modelling software review as well as other well-known
    data sets from the multilevel modelling literature.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mlmRev
# Version: 1.0-6
# Date: 2014-03-11
# Title: Examples from Multilevel Modelling Software Review
# Author: Douglas Bates <bates@stat.wisc.edu>, Martin Maechler <maechler@R-project.org> and Ben Bolker <bolker@mcmaster.ca>
# Contact: LME4 Authors <lme4-authors@lists.r-forge.r-project.org>
# Maintainer: Steve Walker <steve.walker@utoronto.ca>
# Description: Data and examples from a multilevel modelling software review as well as other well-known data sets from the multilevel modelling literature.
# Depends: lme4, R (>= 2.10)
# Suggests: lattice
# LazyData: yes
# License: GPL (>= 2)
# Packaged: 2014-03-11 14:11:54 UTC; stevenwalker
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-03-11 16:41:16

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
