{% set version = '0.19-1' %}  # [linux or win32]
{% set version = '0.19-1' %}  # [win64]
{% set version = '0.19-1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coda
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/coda_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/coda/coda_{{ version }}.tar.gz  # [linux or win32]
  sha256: d41ff5731da6805170769dba75dd011ab33f916d15b2336001f279e21a524491  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/coda_0.19-1.zip  # [win64]
  sha256: 9c3d78c09e2d400f318dda6dc887982d90e3a4ea0c5dd3fe7b7910bb0ea5a487  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/coda_0.19-1.tgz  # [osx]
  sha256: 95731e826d35cb6ab20faa5f58d800123d82f6f1253126194da0abb37859c246  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-lattice

  run:
    - mro-base
    - r-lattice

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('coda')"           # [not win]
    - "\"%R%\" -e \"library('coda')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=coda
  license: GPL (>= 2)
  summary: Provides functions for summarizing and plotting the output from Markov Chain Monte
    Carlo (MCMC) simulations, as well as diagnostic tests of convergence to the equilibrium
    distribution of the Markov chain.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: coda
# Version: 0.19-1
# Date: 2016-12-07
# Title: Output Analysis and Diagnostics for MCMC
# Authors@R: c(person("Martyn", "Plummer", role=c("aut","cre","trl"), email="plummerm@iarc.fr"), person("Nicky", "Best", role="aut"), person("Kate", "Cowles", role="aut"), person("Karen", "Vines", role="aut"), person("Deepayan", "Sarkar", role="aut"), person("Douglas", "Bates", role="aut"), person("Russell", "Almond", role="aut"), person("Arni", "Magnusson", role="aut"))
# Depends: R (>= 2.14.0)
# Imports: lattice
# Description: Provides functions for summarizing and plotting the output from Markov Chain Monte Carlo (MCMC) simulations, as well as diagnostic tests of convergence to the equilibrium distribution of the Markov chain.
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2016-12-07 15:34:56 UTC; martyn
# Author: Martyn Plummer [aut, cre, trl], Nicky Best [aut], Kate Cowles [aut], Karen Vines [aut], Deepayan Sarkar [aut], Douglas Bates [aut], Russell Almond [aut], Arni Magnusson [aut]
# Maintainer: Martyn Plummer <plummerm@iarc.fr>
# Repository: CRAN
# Date/Publication: 2016-12-08 10:25:11

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
