{% set version = '1.5' %}  # [linux or win32]
{% set version = '1.5' %}  # [win64]
{% set version = '1.5' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-magrittr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/magrittr_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/magrittr/magrittr_{{ version }}.tar.gz  # [linux or win32]
  sha256: 05c45943ada9443134caa0ab24db4a962b629f00b755ccf039a2a2a7b2c92ae8  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/magrittr_1.5.zip  # [win64]
  sha256: 6ea2c3401f6e055350a2310d666f74039ea73cd2d6daebd40ffe00346848e664  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/magrittr_1.5.tgz  # [osx]
  sha256: 29acec4c48c23729247ba1d3e461fc3a7ef6bea33a5155230f4511f980c21c43  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('magrittr')"           # [not win]
    - "\"%R%\" -e \"library('magrittr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=magrittr
  license: MIT + file LICENSE
  summary: Provides a mechanism for chaining commands with a new forward-pipe operator, %>%.
    This operator will forward a value, or the result of an expression, into the next
    function call/expression. There is flexible support for the type of right-hand side
    expressions. For more information, see package vignette. To quote Rene Magritte,
    "Ceci n'est pas un pipe."
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: magrittr
# Type: Package
# Title: A Forward-Pipe Operator for R
# Version: 1.5
# Author: Stefan Milton Bache <stefan@stefanbache.dk> and Hadley Wickham <h.wickham@gmail.com>
# Maintainer: Stefan Milton Bache <stefan@stefanbache.dk>
# Description: Provides a mechanism for chaining commands with a new forward-pipe operator, %>%. This operator will forward a value, or the result of an expression, into the next function call/expression. There is flexible support for the type of right-hand side expressions. For more information, see package vignette. To quote Rene Magritte, "Ceci n'est pas un pipe."
# Suggests: testthat, knitr
# VignetteBuilder: knitr
# License: MIT + file LICENSE
# ByteCompile: Yes
# Packaged: 2014-11-22 08:50:53 UTC; shb
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-11-22 19:15:57

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
