{% set version = '0.5-9' %}  # [linux or win32]
{% set version = '0.5-9' %}  # [win64]
{% set version = '0.5-9' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-profilemodel
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/profileModel_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/profileModel/profileModel_{{ version }}.tar.gz  # [linux or win32]
  sha256: c94f25d222521867ddc86021bd0b9a6b9f7b055212985652a8511054b24c2bdd  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/profileModel_0.5-9.zip  # [win64]
  sha256: e22bc4bbad2174f1bfa42710457bdef1c0a189e8bfa675c7f15b84bb3f3147a3  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/macosx/el-capitan/contrib/3.5/profileModel_0.5-9.tgz  # [osx]
  sha256: 1862bdae92144ce715e18650cbd55a8a6285017b306baf91144e3c51ee1524f3  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, gnm
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('profileModel')"           # [not win]
    - "\"%R%\" -e \"library('profileModel')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.ucl.ac.uk/~ucakiko/index.html
  license: GPL (>= 2)
  summary: profileModel provides tools that can be used to calculate, evaluate, plot and use
    for inference the profiles of *arbitrary* inference functions for *arbitrary* 'glm'-like
    fitted models with linear predictors.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: profileModel
# Type: Package
# Title: Tools for profiling inference functions for various model classes
# Version: 0.5-9
# Date: 2013-08-07
# Author: Ioannis Kosmidis <i.kosmidis@ucl.ac.uk>
# Maintainer: Ioannis Kosmidis <i.kosmidis@ucl.ac.uk>
# URL: http://www.ucl.ac.uk/~ucakiko/index.html
# Description: profileModel provides tools that can be used to calculate, evaluate, plot and use for inference the profiles of *arbitrary* inference functions for *arbitrary* 'glm'-like fitted models with linear predictors.
# License: GPL (>= 2)
# Depends: R (>= 2.6.0)
# Suggests: MASS, gnm
# Packaged: 2013-08-14 23:43:03 UTC; yiannis
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-08-17 09:49:42

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
