FROM ubuntu:16.04
MAINTAINER Ray Donnelly (rdonnelly@anaconda.com)
ADD microsoft-r-open-3.4.3.tar.gz microsoft-r-client-*3.4.3.deb /
RUN apt-get update && \
    apt-get install -y git && \
    git clone https://github.com/AnacondaRecipes/aggregateMRO && \
    ./microsoft-r-open/install.sh -u -a && \
    dpkg -i /microsoft-r-client-packages-3.4.3.deb && \
    dpkg -i /microsoft-r-client-mml-3.4.3.deb && \
    dpkg -i /microsoft-r-client-mlm-3.4.3.deb
ENTRYPOINT ["/bin/sh"]
