{% set version = '0.9.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-diagrammer
  version: {{ version|replace("-", "_") }}

source:
  fn: DiagrammeR_0.9.2.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/DiagrammeR_0.9.2.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/DiagrammeR/DiagrammeR_0.9.2.tar.gz  # [linux or win32]
  sha256: dc9d24c5129b29688d1dd74438fe1fc5f02f3537a9a94cd26fd54f496468e63b  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/DiagrammeR_0.9.2.zip  # [win64]
  sha256: 4d45cacf3aabd3f13655e025e11021f4ecb9864cb7fe203448a227cfd431e6e8  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/DiagrammeR_0.9.2.tgz  # [osx]
  sha256: 143d823334ce850f4d68ba23347adb87a15c3ce61dfe329093759ac6234618be  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, DiagrammeRsvg, rsvg, knitr, testthat
requirements:
  build:

  host:
    - mro-base
    - r-rcolorbrewer >=1.1_2
    - r-downloader >=0.4
    - r-dplyr >=0.7.2
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=0.9
    - r-igraph >=1.1.2
    - r-influencer >=0.1.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.3
    - r-readr >=1.1.1
    - r-rgexf >=0.15.3
    - r-rlang >=0.1.1
    - r-rstudioapi >=0.6
    - r-scales >=0.5.0
    - r-stringr >=1.2.0
    - r-tibble >=1.3.3
    - r-tidyr >=0.6.3
    - r-viridis >=0.4.0
    - r-visnetwork >=2.0.1

  run:
    - mro-base
    - r-rcolorbrewer >=1.1_2
    - r-downloader >=0.4
    - r-dplyr >=0.7.2
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=0.9
    - r-igraph >=1.1.2
    - r-influencer >=0.1.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.3
    - r-readr >=1.1.1
    - r-rgexf >=0.15.3
    - r-rlang >=0.1.1
    - r-rstudioapi >=0.6
    - r-scales >=0.5.0
    - r-stringr >=1.2.0
    - r-tibble >=1.3.3
    - r-tidyr >=0.6.3
    - r-viridis >=0.4.0
    - r-visnetwork >=2.0.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('DiagrammeR')"           # [not win]
    - "\"%R%\" -e \"library('DiagrammeR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rich-iannone/DiagrammeR
  license: MIT + file LICENSE
  summary: Graph and network visualization using tabular data.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: DiagrammeR
# Type: Package
# Title: Graph/Network Visualization
# Version: 0.9.2
# Authors@R: c( person( "Knut", "Sveidqvist" , role = c("aut", "cph") , comment = "mermaid.js library in htmlwidgets/lib, http://github.com/knsv/mermaid/" ), person( "Mike", "Bostock" , role = c("aut", "cph") , comment = "d3.js library in htmlwidgets/lib, http://d3js.org" ), person( "Chris", "Pettitt" , role = c("aut", "cph") , comment = "dagre-d3.js library in htmlwidgets/lib, http://github.com/cpettitt/dagre-d3" ), person( "Mike", "Daines" , role = c("aut", "cph") , comment = "viz.js library in htmlwidgets/lib, http://github.com/mdaines/viz.js/" ), person( "Richard", "Iannone" , role = c("aut", "cre") , comment = "R interface" , email = "riannone@me.com" ) )
# Maintainer: Richard Iannone <riannone@me.com>
# Description: Graph and network visualization using tabular data.
# Depends: R (>= 3.2.0)
# License: MIT + file LICENSE
# Imports: dplyr (>= 0.7.2), downloader (>= 0.4), htmltools (>= 0.3.6), htmlwidgets (>= 0.9), igraph (>= 1.1.2), influenceR (>= 0.1.0), magrittr (>= 1.5), purrr (>= 0.2.3), RColorBrewer (>= 1.1-2), readr (>= 1.1.1), rlang (>= 0.1.1), rstudioapi (>= 0.6), rgexf (>= 0.15.3), scales (>= 0.5.0), stringr (>= 1.2.0), tibble (>= 1.3.3), tidyr (>= 0.6.3), viridis (>= 0.4.0), visNetwork (>= 2.0.1)
# URL: https://github.com/rich-iannone/DiagrammeR
# BugReports: https://github.com/rich-iannone/DiagrammeR/issues
# Suggests: covr, DiagrammeRsvg, rsvg, knitr, testthat
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-09-06 04:28:01 UTC; riannone
# Author: Knut Sveidqvist [aut, cph] (mermaid.js library in htmlwidgets/lib, http://github.com/knsv/mermaid/), Mike Bostock [aut, cph] (d3.js library in htmlwidgets/lib, http://d3js.org), Chris Pettitt [aut, cph] (dagre-d3.js library in htmlwidgets/lib, http://github.com/cpettitt/dagre-d3), Mike Daines [aut, cph] (viz.js library in htmlwidgets/lib, http://github.com/mdaines/viz.js/), Richard Iannone [aut, cre] (R interface)
# Repository: CRAN
# Date/Publication: 2017-09-06 20:37:43 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
