
{% set pfx = 'r-' %}
{% set version = '3.4.1' %}

# This does not contain MKL
# {% set url = 'https://go.microsoft.com/fwlink/?linkid=852724' %}  # [win64]
# {% set fn = 'SRO_3.4.1.0_1033.cab' %}  # [win64]
# {% set shasum = 'cb2632c339ae5211cb3475bf33b8ad9c3159f410c11d34ffca85d0527f872985' %}  # [win64]

# It is possible to extract from this, but it requires that you install the Wix SDK
# https://github.com/wixtoolset/wix3/releases/download/wix311rtm/wix311-binaries.zip
# Then run:
# dark.exe microsoft-r-open-3.4.1.exe -x $PWD
# msiexec -a $(cygpath -w $PWD/AttachedContainer/ROpen.msi) -qb TARGETDIR=$(cygpath -w /tmp/test)
# msiexec -a $(cygpath -w $PWD/AttachedContainer/ROpen.msi) -qb TARGETDIR=$(cygpath -w /tmp/test)
{% set url = 'https://mran.blob.core.windows.net/install/mro/3.4.1/microsoft-r-open-3.4.1.exe' %}  # [win64]
{% set fn = 'microsoft-r-open-3.4.1.exe' %}  # [win64]
{% set shasum = '04f7be3aaf393937b2edb536f1a3c7f279145b3aeb6e5eefdf9bee1ac137afc6' %}  # [win64]

{% set url = 'https://mran.blob.core.windows.net/install/mro/3.4.1/microsoft-r-open-3.4.1.tar.gz' %}  # [linux64]
{% set fn = 'microsoft-r-open-3.4.1.tar.gz' %}  # [linux64]
{% set shasum = '83c2f36f255483e49cefa91a143c020ad9dfdfd70a101432f1eae066825261cb' %}  # [linux64]

{% set url = 'https://mran.blob.core.windows.net/install/mro/3.4.1/microsoft-r-open-3.4.1.pkg' %}  # [osx]
{% set fn = 'microsoft-r-open-3.4.1.pkg' %}  # [osx]
{% set shasum = '643c5e953a02163ae73273da27f9c1752180f55bf836b127b6e1829fd1756fc8' %}  # [osx]

package:
  name: r
  version: {{ version }}

source:
  - url: {{ url }}
    fn: {{ fn }}
    sha256: {{ shasum }}
    folder: unpack
  - url: https://github.com/wixtoolset/wix3/releases/download/wix311rtm/wix311-binaries.zip  # [win64]
    sha256: da034c489bd1dd6d8e1623675bf5e899f32d74d6d8312f8dd125a084543193de                 # [win64]
    folder: wix                                                                              # [win64]

requirements:
  build:
    - python-libarchive-c
    - m2w64-toolchain  # [win]
    - m2-base  # [win]

outputs:
  - name: mro-base
    version: {{ version }}
    script: install-mro-base.sh
    requirements:
      build:
        - m2-base  # [win]
