
{% set pfx = 'r-' %}
{% set version = '3.4.3' %}
{% set rc_version = '3.4.1' %}

{% set url = 'https://mran.blob.core.windows.net/install/mro/3.4.3/microsoft-r-open-3.4.3.exe' %}  # [win64]
{% set fn = 'microsoft-r-open-3.4.3.exe' %}  # [win64]
{% set shasum = 'c8d50172ec8173cef503a616f9ef310dc5b274ac045ea71b9c8aed248098cbdd' %}  # [win64]

{% set url = 'https://mran.blob.core.windows.net/install/mro/3.4.3/microsoft-r-open-3.4.3.tar.gz' %}  # [linux64]
{% set fn = 'microsoft-r-open-3.4.3.tar.gz' %}  # [linux64]
{% set shasum = 'bf2cd35a11db604b1fa8f5f0c0acf0ae05756020d90fb3f6cbb639337efcee5b' %}  # [linux64]

{% set url = 'https://mran.blob.core.windows.net/install/mro/3.4.3/microsoft-r-open-3.4.3.pkg' %}  # [osx]
{% set fn = 'microsoft-r-open-3.4.3.pkg' %}  # [osx]
{% set shasum = '4998500839389821f995d3ebb89ee7e8e5a35a61a63ba0ac54d63adf53288947' %}  # [osx]

package:
  name: r
  version: {{ version }}

source:
  - url: {{ url }}
    fn: {{ fn }}
    sha256: {{ shasum }}
    folder: unpack
  - url: https://packages.microsoft.com/rhel/6/prod/microsoft-r-client-packages-{{ rc_version }}.rpm  # [linux]
    sha256: 5fd191776bfb5cfb6e2bac54a466ccc2714372b620d1fb1a82e19e40d3962d31  # [linux]
    folder: unpack-r-client  # [linux]
  - url: https://github.com/wixtoolset/wix3/releases/download/wix311rtm/wix311-binaries.zip  # [win64]
    sha256: da034c489bd1dd6d8e1623675bf5e899f32d74d6d8312f8dd125a084543193de                 # [win64]
    folder: wix                                                                              # [win64]

requirements:
  build:
    - python-libarchive-c
    - posix  # [win]
  host:
    - m2w64-toolchain  # [win]
    - m2-base  # [win]

outputs:
  - name: mro-base
    version: {{ version }}
    script: install-mro-base.sh
    requirements:
      build:
        - m2-base  # [win]
        - {{ compiler('fortran') }}  # [not win]
        - {{ compiler('cxx') }}  # [not win]
        - {{ compiler('c') }}  # [not win]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libxrender') }}            # [linux]
        - {{ cdt('libxext') }}               # [linux]
        - {{ cdt('libuuid') }}               # [linux]
        - {{ cdt('libsm-devel') }}           # [linux]
        - {{ cdt('libice-devel') }}          # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxft') }}                # [linux]
        - {{ cdt('libxt') }}                 # [linux]
        - {{ cdt('libxt-devel') }}           # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxau') }}                # [linux]
        - {{ cdt('java-1.7.0-openjdk') }}    # [linux]
      host:
        - libgfortran >=3.0.1  # [osx]
        - llvm-openmp >=4.0.1  # [osx]
        - expat  # [osx]
        - libcurl  # [osx]
        - libiconv  # [osx]
        - ncurses  # [osx]
        - libgcc-ng >=7.2.0  # [linux]
        - zlib  # [linux]
        - libgfortran-ng >=7.2.0 # [linux]
        - pango 1.40.*  # [linux]
        - cairo 1.14.*  # [linux]
        - glib 2.*  # [linux]
      run:
        - {{ compiler('fortran') }}  # [not win]
        - {{ compiler('cxx') }}  # [not win]
        - {{ compiler('c') }}  # [not win]
        - libgfortran >=3.0.1  # [osx]
        - llvm-openmp >=4.0.1  # [osx]
        - libcurl  # [osx]
        - pango 1.*             # [linux]
        - cairo 1.14.*  # [linux]
        - glib 2.*  # [linux]

#  - name: r-base
#    version: {{ version }}
#    requirements:
#      build:
#        - {{ pin_subpackage('mro-base', min_pin='x.x.x.x', max_pin='x.x.x.x') }}
#      run:
#        - {{ pin_subpackage('mro-base', min_pin='x.x.x.x', max_pin='x.x.x.x') }}


  - name: r-boot
    version: '1.3_20'
    script: install-r-package.sh
    # This is required to make R link correctly on Linux.
    build:

      rpaths:
        - lib/R/lib/
        - lib/

    # Suggests: MASS, survival
    requirements:
      build:
        - m2-base  # [win]
      host:
        - mro-base {{ version }}
      run:
        - mro-base {{ version }}

    test:
      commands:
        # You can put additional test commands to be run here.
        - $R -e "library('boot')"           # [not win]
        - "\"%R%\" -e \"library('boot')\""  # [win]

    about:
      home: https://mran.microsoft.com/package/boot
      license: Unlimited
      summary: Functions and datasets for bootstrapping from the book "Bootstrap Methods and Their
        Application" by A. C. Davison and  D. V. Hinkley (1997, CUP), originally written
        by Angelo Canty for S.
      license_family: MIT

  - name: r-client  # [linux or win]
    version: '3.4.1'  # [linux or win]
    script: install-r-client.sh  # [linux or win]
    about:  # [linux or win]
      home: https://docs.microsoft.com/en-us/machine-learning-server/r-client/what-is-microsoft-r-client  # [linux or win]
      license: Proprietary  # [linux or win]
      summary: A free, community-supported, data science tool for high performance analytics  # [linux or win]
      license_family: Proprietary  # [linux or win]

  - name: mro-basics
    version: {{ version }}
    requirements:
      run:
        - mro-base
        - r-boot

