{% set version = '0.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-scales
  version: {{ version|replace("-", "_") }}

source:
  fn: scales_0.5.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/scales_0.5.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/scales/scales_0.5.0.tar.gz  # [linux or win32]
  sha256: dbfcc0817c4ab8b8777ec7d68ebfe220177c193cfb5bd0e8ba5d365dbfe3e97d  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/scales_0.5.0.zip  # [win64]
  sha256: 549b28cea47e974fb06cca46a8878a123748c8afc1769430eb2be5c9e5a25fd2  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/scales_0.5.0.tgz  # [osx]
  sha256: f5110734714b20fdba8a68a44bd0ed6d5a8d0b15a4a143cad64c1784707760f8  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 0.8), bit64, covr, hms
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-r6
    - r-rcolorbrewer
    - r-rcpp
    - r-dichromat
    - r-labeling
    - r-munsell >=0.2
    - r-plyr
    - r-viridislite

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-r6
    - r-rcolorbrewer
    - r-rcpp
    - r-dichromat
    - r-labeling
    - r-munsell >=0.2
    - r-plyr
    - r-viridislite

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('scales')"           # [not win]
    - "\"%R%\" -e \"library('scales')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/scales
  license: MIT + file LICENSE
  summary: Graphical scales map data to aesthetics, and provide methods for automatically determining
    breaks and labels for axes and legends.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: scales
# Version: 0.5.0
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph") )
# Title: Scale Functions for Visualization
# Description: Graphical scales map data to aesthetics, and provide methods for automatically determining breaks and labels for axes and legends.
# URL: https://github.com/hadley/scales
# BugReports: https://github.com/hadley/scales/issues
# Depends: R (>= 2.13)
# Imports: RColorBrewer, dichromat, plyr, munsell (>= 0.2), labeling, Rcpp, R6, viridisLite
# LinkingTo: Rcpp
# Suggests: testthat (>= 0.8), bit64, covr, hms
# License: MIT + file LICENSE
# LazyLoad: yes
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-08-23 21:21:31 UTC; Kara
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-08-24 14:35:38 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
