{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-blob
  version: {{ version|replace("-", "_") }}

source:
  fn: blob_1.1.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/blob_1.1.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/blob/blob_1.1.0.tar.gz  # [linux or win32]
  sha256: 16d6603df3ddba177f0ac4d9469c938f89131c4bf8834345db838defd9ffea16  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/blob_1.1.0.zip  # [win64]
  sha256: ee2eaab872036ffc0bf7677c06a63deef227015c758a62e487164b4dd2f18ef3  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/blob_1.1.0.tgz  # [osx]
  sha256: d2a64ad17e2012483de3b725f41d8071111d8b24e1e68c11dcfe4f37db573c7a  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, covr
requirements:
  build:

  host:
    - mro-base
    - r-tibble

  run:
    - mro-base
    - r-tibble

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('blob')"           # [not win]
    - "\"%R%\" -e \"library('blob')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/blob
  license: GPL-3
  summary: R's raw vector is useful for storing a single binary object. What if you want to put
    a vector of them in a data frame? The blob package provides the blob object, a list
    of raw vectors, suitable for use as a column in data frame.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: blob
# Title: A Simple S3 Class for Representing Vectors of Binary Data ('BLOBS')
# Version: 1.1.0
# Authors@R: c( person("Hadley", "Wickham", role = c("aut")), person("Kirill", "Muller", , "krlmlr+r@mailbox.org", role = c("cre")), person("RStudio", role = "cph") )
# Description: R's raw vector is useful for storing a single binary object. What if you want to put a vector of them in a data frame? The blob package provides the blob object, a list of raw vectors, suitable for use as a column in data frame.
# Imports: tibble
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/hadley/blob
# BugReports: https://github.com/hadley/blob/issues
# Suggests: testthat, covr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-06-17 04:01:59 UTC; muelleki
# Author: Hadley Wickham [aut], Kirill Muller [cre], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2017-06-17 14:57:46 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
