{% set version = '1.0-4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmariadb
  version: {{ version|replace("-", "_") }}

source:
  fn: RMariaDB_1.0-4.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/RMariaDB_1.0-4.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/RMariaDB/RMariaDB_1.0-4.tar.gz  # [linux or win32]
  sha256: aa29906bdfa14e59343afba4001648125d3d9fd5edd18f48f592011e9c0afe77  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/RMariaDB_1.0-4.zip  # [win64]
  sha256: 5eeaf8f5fb851e1daf343586deb6c3f1f2cd22e633de3630bde8f92fc4169d0f  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/RMariaDB_1.0-4.tgz  # [osx]
  sha256: 24386a3dae10bcb4726f12b3ab391857563d155e08b9665efa9caf1b30c6816b  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: DBItest, rprojroot, testthat
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}sed                 # [win32]
    - {{posix}}grep                # [win32]
    - {{posix}}autoconf            # [linux or win32]
    - {{posix}}automake-wrapper    # [win32]
    - {{posix}}automake            # [win32]
    - {{posix}}pkg-config
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-bh
    - r-dbi >=0.5
    - r-rcpp >=0.12.4
    - r-bit64
    - r-hms
    - r-plogr
    - {{native}}mysql              # [linux or win32]

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-bh
    - r-dbi >=0.5
    - r-rcpp >=0.12.4
    - r-bit64
    - r-hms
    - r-plogr
    - {{native}}mysql              # [linux or win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RMariaDB')"           # [not win]
    - "\"%R%\" -e \"library('RMariaDB')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstats-db/RMariaDB, https://downloads.mariadb.org/connector-c/
  license: GPL-2
  summary: Implements a 'DBI'-compliant interface to 'MariaDB' (<https://mariadb.org/>) and 'MySQL'
    (<https://www.mysql.com/>) databases.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: RMariaDB
# Version: 1.0-4
# Title: Database Interface and 'MariaDB' Driver
# Encoding: UTF-8
# Description: Implements a 'DBI'-compliant interface to 'MariaDB' (<https://mariadb.org/>) and 'MySQL' (<https://www.mysql.com/>) databases.
# Authors@R: c( person("Kirill", "Muller", email = "krlmlr+r@mailbox.org", role = c("aut", "cre")), person("Jeroen", "Ooms", role = "aut"), person("David", "James", role = "aut"), person("Saikat", "DebRoy", role = "aut"), person("Hadley", "Wickham", role = "aut"), person("Jeffrey", "Horner", role = "aut"), person("RStudio", role = "cph"), person("Kungliga Tekniska Hogskolan", role = "ctb", comment = "Source code for timegm"))
# Depends: R (>= 2.8.0)
# Imports: bit64, DBI (>= 0.5), hms, methods, Rcpp (>= 0.12.4)
# Suggests: DBItest, rprojroot, testthat
# LinkingTo: Rcpp, BH, plogr
# License: GPL-2
# URL: https://github.com/rstats-db/RMariaDB, https://downloads.mariadb.org/connector-c/
# BugReports: https://github.com/rstats-db/RMariaDB/issues
# SystemRequirements: libmariadb-client-lgpl-dev or libmysqlclient-dev (deb), mariadb-connector-c-devel or mariadb-devel (rpm), mariadb-connector-c or mysql-connector-c (brew)
# NeedsCompilation: yes
# Collate: 'MariaDBConnection.R' 'MariaDBDriver.R' 'MariaDBResult.R' 'RMariaDB.R' 'RcppExports.R' 'coerce.R' 'connect.R' 'default.R' 'export.R' 'query.R' 'quote.R' 'rownames.R' 'table.R' 'transaction.R' 'utils.R' 'zzz.R'
# RoxygenNote: 6.0.1
# Packaged: 2017-12-11 17:57:16 UTC; muelleki
# Author: Kirill Muller [aut, cre], Jeroen Ooms [aut], David James [aut], Saikat DebRoy [aut], Hadley Wickham [aut], Jeffrey Horner [aut], RStudio [cph], Kungliga Tekniska Hogskolan [ctb] (Source code for timegm)
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2017-12-11 22:55:30 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
