{% set version = '3.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gtools
  version: {{ version|replace("-", "_") }}

source:
  fn: gtools_3.5.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/gtools_3.5.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/gtools/gtools_3.5.0.tar.gz  # [linux or win32]
  sha256: 86b6a51a92ddb3c78095e0c5dc20414c67f6e28f915bf0ee11406adad3e476f6  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/gtools_3.5.0.zip  # [win64]
  sha256: ca586d3622d3a341e761cc31481351ddfc9fb3f9fb906f6ae7190afdb8f46b86  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/gtools_3.5.0.tgz  # [osx]
  sha256: 4f89fa120a03d39c01ec235511c19cd7a3b410c11e4fcc25b0e11105c2fed962  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gtools')"           # [not win]
    - "\"%R%\" -e \"library('gtools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=gtools
  license: GPL-2
  summary: 'Functions to assist in R programming, including: - assist in developing, updating,
    and maintaining R and R packages (''ask'', ''checkRVersion'', ''getDependencies'',
    ''keywords'', ''scat''), - calculate the logit and inverse logit transformations
    (''logit'', ''inv.logit''), - test if a value is missing, empty or contains only
    NA and NULL values (''invalid''), - manipulate R''s .Last function (''addLast''),
    - define macros (''defmacro''), - detect odd and even integers (''odd'', ''even''),
    - convert strings containing non-ASCII characters (like single quotes) to plain
    ASCII (''ASCIIfy''), - perform a binary search (''binsearch''), - sort strings containing
    both numeric and character components (''mixedsort''), - create a factor variable
    from the quantiles of a continuous variable (''quantcut''), - enumerate permutations
    and combinations (''combinations'', ''permutation''), - calculate and convert between
    fold-change and log-ratio (''foldchange'', ''logratio2foldchange'', ''foldchange2logratio''),
    - calculate probabilities and generate random numbers from Dirichlet distributions
    (''rdirichlet'', ''ddirichlet''), - apply a function over adjacent subsets of a
    vector (''running''), - modify the TCP\_NODELAY (''de-Nagle'') flag for socket objects,
    - efficient ''rbind'' of data frames, even if the column names don''t match (''smartbind''),
    - generate significance stars from p-values (''stars.pval''), - convert characters
    to/from ASCII codes.'

  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: gtools
# Title: Various R Programming Tools
# Description: Functions to assist in R programming, including: - assist in developing, updating, and maintaining R and R packages ('ask', 'checkRVersion', 'getDependencies', 'keywords', 'scat'), - calculate the logit and inverse logit transformations ('logit', 'inv.logit'), - test if a value is missing, empty or contains only NA and NULL values ('invalid'), - manipulate R's .Last function ('addLast'), - define macros ('defmacro'), - detect odd and even integers ('odd', 'even'), - convert strings containing non-ASCII characters (like single quotes) to plain ASCII ('ASCIIfy'), - perform a binary search ('binsearch'), - sort strings containing both numeric and character components ('mixedsort'), - create a factor variable from the quantiles of a continuous variable ('quantcut'), - enumerate permutations and combinations ('combinations', 'permutation'), - calculate and convert between fold-change and log-ratio ('foldchange', 'logratio2foldchange', 'foldchange2logratio'), - calculate probabilities and generate random numbers from Dirichlet distributions ('rdirichlet', 'ddirichlet'), - apply a function over adjacent subsets of a vector ('running'), - modify the TCP\_NODELAY ('de-Nagle') flag for socket objects, - efficient 'rbind' of data frames, even if the column names don't match ('smartbind'), - generate significance stars from p-values ('stars.pval'), - convert characters to/from ASCII codes.
# Version: 3.5.0
# Date: 2015-05-26
# Author: Gregory R. Warnes, Ben Bolker, and Thomas Lumley
# Maintainer: Gregory R. Warnes <greg@warnes.net>
# License: GPL-2
# Repository: CRAN
# Repository/R-Forge/Project: r-gregmisc
# Repository/R-Forge/Revision: 2048
# Repository/R-Forge/DateTimeStamp: 2015-05-27 16:38:37
# Date/Publication: 2015-05-29 10:36:40
# NeedsCompilation: yes
# Packaged: 2015-05-27 16:45:10 UTC; rforge
# Depends: R (>= 2.10)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
