{% set version = '0.3.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-feather
  version: {{ version|replace("-", "_") }}

source:
  fn: feather_0.3.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/feather_0.3.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/feather/feather_0.3.1.tar.gz  # [linux or win32]
  sha256: f1069bf920e9bc3da6bf43542a3a7ccc3142544d759945115ecade69dd5ccde0  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/feather_0.3.1.zip  # [win64]
  sha256: f975ec53a89be38c3b3e81c16b28366276ce58028040e706ccd39c6075abb02e  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/feather_0.3.1.tgz  # [osx]
  sha256: 09581d58f1735879ea734cd7fc3a427fa9aaada7a91e7c270113e3f07c66d37e  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, dplyr
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}sed                 # [win32]
    - {{posix}}grep                # [win32]
    - {{posix}}autoconf            # [linux or win32]
    - {{posix}}automake-wrapper    # [win32]
    - {{posix}}automake            # [win32]
    - {{posix}}pkg-config
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-rcpp
    - r-hms
    - r-tibble

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-rcpp
    - r-hms
    - r-tibble

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('feather')"           # [not win]
    - "\"%R%\" -e \"library('feather')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/wesm/feather
  license: Apache License 2.0
  summary: Read and write feather files, a lightweight binary columnar data store designed for
    maximum speed.
  license_family: APACHE

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: feather
# Title: R Bindings to the Feather 'API'
# Version: 0.3.1
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph"), person("Feather developers", role = "ctb", comment = "Bundled feather library"), person("Google", role = "ctb", comment = "Bundled flatbuffers code"), person("LevelDB Authors", role = "ctb") )
# Description: Read and write feather files, a lightweight binary columnar data store designed for maximum speed.
# Encoding: UTF-8
# License: Apache License 2.0
# LazyData: true
# URL: https://github.com/wesm/feather
# BugReports: https://github.com/wesm/feather/issues
# LinkingTo: Rcpp
# Imports: Rcpp, tibble, hms
# Suggests: testthat, dplyr
# SystemRequirements: little-endian platform
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2016-11-08 22:45:11 UTC; kevin
# Author: Hadley Wickham [aut, cre], RStudio [cph], Feather developers [ctb] (Bundled feather library), Google [ctb] (Bundled flatbuffers code), LevelDB Authors [ctb]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2016-11-09 00:35:01

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
