{% set version = '3.1-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-grpreg
  version: {{ version|replace("-", "_") }}

source:
  fn: grpreg_3.1-2.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/grpreg_3.1-2.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/grpreg/grpreg_3.1-2.tar.gz  # [linux or win32]
  sha256: 38d5f277b8fbbdc3a760277c2372ae993f7bda4f0198338609ccc91110575c10  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/grpreg_3.1-2.zip  # [win64]
  sha256: f844d7a3f136dc5b645afdc81fa5e5a90928c89be2dc67a3fcddfe8ce092e520  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/grpreg_3.1-2.tgz  # [osx]
  sha256: 4ad379ffc9d9eb32b658e0691704219e6d88152a96a1e0860cbb79bd425f70d4  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: grpregOverlap, knitr, survival
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-matrix

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-matrix

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('grpreg')"           # [not win]
    - "\"%R%\" -e \"library('grpreg')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=grpreg
  license: GPL-3
  summary: Efficient algorithms for fitting the regularization path of linear or logistic regression
    models with grouped penalties.  This includes group selection methods such as group
    lasso, group MCP, and group SCAD as well as bi-level selection methods such as the
    group exponential lasso, the composite MCP, and the group bridge.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: grpreg
# Title: Regularization Paths for Regression Models with Grouped Covariates
# Version: 3.1-2
# Date: 2017-07-05
# Author: Patrick Breheny [aut, cre], Yaohui Zeng [ctb]
# Maintainer: Patrick Breheny <patrick-breheny@uiowa.edu>
# Depends: R (>= 3.1.0), Matrix
# Suggests: grpregOverlap, knitr, survival
# VignetteBuilder: knitr
# Description: Efficient algorithms for fitting the regularization path of linear or logistic regression models with grouped penalties.  This includes group selection methods such as group lasso, group MCP, and group SCAD as well as bi-level selection methods such as the group exponential lasso, the composite MCP, and the group bridge.
# BugReports: http://github.com/pbreheny/grpreg/issues
# License: GPL-3
# NeedsCompilation: yes
# Packaged: 2017-07-05 21:31:51 UTC; pbreheny
# Repository: CRAN
# Date/Publication: 2017-07-06 10:19:31 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
