{% set version = '0.1-2' %}  # [linux or win32]
{% set version = '0.1-2' %}  # [win64]
{% set version = '0.1-2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-uuid
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/uuid_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/uuid/uuid_{{ version }}.tar.gz  # [linux or win32]
  sha256: dd71704dc336b0857981b92a75ed9877d4ca47780b1682def28839304cd3b1be  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/uuid_0.1-2.zip  # [win64]
  sha256: 472c41c4856eda9889dc4b97ff38f691d98809e31b0b53d106bee4ab8773e4b4  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/uuid_0.1-2.tgz  # [osx]
  sha256: 3b19f220c98e50429e091127720ec9d4adb6343c130786c77546d2c430cd9b3d  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('uuid')"           # [not win]
    - "\"%R%\" -e \"library('uuid')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.rforge.net/uuid
  license: MIT + file LICENSE
  summary: Tools for generating and handling of UUIDs (Universally Unique Identifiers).
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: uuid
# Version: 0.1-2
# Title: Tools for generating and handling of UUIDs
# Author: Simon Urbanek <Simon.Urbanek@r-project.org> (R package), Theodore Ts'o <tytso@thunk.org> (libuuid)
# Maintainer: Simon Urbanek <Simon.Urbanek@r-project.org>
# Depends: R (>= 2.9.0)
# Description: Tools for generating and handling of UUIDs (Universally Unique Identifiers).
# License: MIT + file LICENSE
# URL: http://www.rforge.net/uuid
# NeedsCompilation: yes
# Packaged: 2015-07-27 20:57:43 UTC; svnuser
# Repository: CRAN
# Date/Publication: 2015-07-28 08:03:46

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
