{% set version = '1.0-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bitops
  version: {{ version|replace("-", "_") }}

source:
  fn: bitops_1.0-6.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/bitops_1.0-6.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/bitops/bitops_1.0-6.tar.gz  # [linux or win32]
  sha256: 9b731397b7166dd54941fb0d2eac6df60c7a483b2e790f7eb15b4d7b79c9d69c  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/bitops_1.0-6.zip  # [win64]
  sha256: 2adebafa9751794faf6da1c0002462d297f33ead03b9995df8cb200b620d915a  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/bitops_1.0-6.tgz  # [osx]
  sha256: 5f8628a6f9b18efbb1e22fc1db3ebfb668bb92e96819280ee004b21b94cd847c  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bitops')"           # [not win]
    - "\"%R%\" -e \"library('bitops')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=bitops
  license: GPL (>= 2)
  summary: Functions for bitwise operations on integer vectors.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: bitops
# Version: 1.0-6
# Date: 2013-08-17
# Author: S original by Steve Dutky <sdutky@terpalum.umd.edu> initial R port and extensions by Martin Maechler; revised and modified by Steve Dutky
# Maintainer: Martin Maechler <maechler@stat.math.ethz.ch>
# Title: Bitwise Operations
# Description: Functions for bitwise operations on integer vectors.
# License: GPL (>= 2)
# Packaged: 2013-08-17 15:58:57 UTC; maechler
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2013-08-17 21:10:34

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
