{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-haven
  version: {{ version|replace("-", "_") }}

source:
  fn: haven_1.1.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/haven_1.1.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/haven/haven_1.1.0.tar.gz  # [linux or win32]
  sha256: 089fb4d0955f320abc48d0a3031799f96f3a20b82492474743903fdf12001d19  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/haven_1.1.0.zip  # [win64]
  sha256: 7a316f6172064f0dcd813429a275adbadf4f0fd35c21133b7142f31fbf2cb711  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/haven_1.1.0.tgz  # [osx]
  sha256: 979c4e5efcb857167ebcfb5540321869e69ef115247ceba2c4f7a7abba22dc27  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown, covr
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-rcpp >=0.11.4
    - r-forcats >=0.2.0
    - r-hms
    - r-readr >=0.1.0
    - r-tibble

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-rcpp >=0.11.4
    - r-forcats >=0.2.0
    - r-hms
    - r-readr >=0.1.0
    - r-tibble

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('haven')"           # [not win]
    - "\"%R%\" -e \"library('haven')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://haven.tidyverse.org, https://github.com/tidyverse/haven, https://github.com/WizardMac/ReadStat
  license: MIT + file LICENSE
  summary: Import foreign statistical formats into R via the embedded 'ReadStat' C library, <https://github.com/WizardMac/ReadStat>.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: haven
# Version: 1.1.0
# Title: Import and Export 'SPSS', 'Stata' and 'SAS' Files
# Description: Import foreign statistical formats into R via the embedded 'ReadStat' C library, <https://github.com/WizardMac/ReadStat>.
# License: MIT + file LICENSE
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("Evan", "Miller", , role = c("aut", "cph"), comment = "Author of included ReadStat code"), person("RStudio", role = c("cph", "fnd")) )
# Depends: R (>= 3.1.0)
# Suggests: testthat, knitr, rmarkdown, covr
# LinkingTo: Rcpp
# Imports: Rcpp (>= 0.11.4), readr (>= 0.1.0), hms, tibble, forcats (>= 0.2.0)
# LazyData: true
# URL: http://haven.tidyverse.org, https://github.com/tidyverse/haven, https://github.com/WizardMac/ReadStat
# BugReports: https://github.com/hadley/haven/issues
# VignetteBuilder: knitr
# SystemRequirements: GNU make
# RoxygenNote: 6.0.1
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2017-07-08 15:47:00 UTC; hadley
# Author: Hadley Wickham [aut, cre], Evan Miller [aut, cph] (Author of included ReadStat code), RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-07-09 06:40:47 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
