{% set version = '0.2.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bindrcpp
  version: {{ version|replace("-", "_") }}

source:
  fn: bindrcpp_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/bindrcpp_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/bindrcpp/bindrcpp_{{ version }}.tar.gz  # [linux or win32]
  sha256: 48130709eba9d133679a0e959e49a7b14acbce4f47c1e15c4ab46bd9e48ae467  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/bindrcpp_0.2.2.zip  # [win64]
  sha256: a359bbe1c5ba39134cabdfaddd3ea0354fa96bd14e717b175b777da76073e0ba  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/bindrcpp_0.2.2.tgz  # [osx]
  sha256: e917e1ad38974c887bfd3e3b894a3f8c31af65ed54f22f8a2cc9b9fa8829c20f  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]

  host:
    - mro-base
    - r-rcpp >=0.12.16
    - r-bindr >=0.1.1
    - r-plogr

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-rcpp >=0.12.16
    - r-bindr >=0.1.1
    - r-plogr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bindrcpp')"           # [not win]
    - "\"%R%\" -e \"library('bindrcpp')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/krlmlr/bindrcpp, https://krlmlr.github.io/bindrcpp
  license: MIT + file LICENSE
  summary: Provides an easy way to fill an environment with active bindings that call a C++ function.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: bindrcpp
# Title: An 'Rcpp' Interface to Active Bindings
# Version: 0.2.2
# Date: 2018-03-29
# Authors@R: c( person("Kirill", "M\u00fcller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org", comment = c(ORCID = "0000-0002-1416-3412")), person("RStudio", role = "cph") )
# Description: Provides an easy way to fill an environment with active bindings that call a C++ function.
# License: MIT + file LICENSE
# URL: https://github.com/krlmlr/bindrcpp, https://krlmlr.github.io/bindrcpp
# BugReports: https://github.com/krlmlr/bindrcpp/issues
# Imports: bindr (>= 0.1.1), Rcpp (>= 0.12.16)
# Suggests: testthat
# LinkingTo: plogr, Rcpp
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: yes
# Packaged: 2018-03-29 13:33:00 UTC; muelleki
# Author: Kirill Muller [aut, cre] (<https://orcid.org/0000-0002-1416-3412>), RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2018-03-29 14:09:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
