{% set version = '0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bindrcpp
  version: {{ version|replace("-", "_") }}

source:
  fn: bindrcpp_0.2.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/bindrcpp_0.2.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/bindrcpp/bindrcpp_0.2.tar.gz  # [linux or win32]
  sha256: d0efa1313cb8148880f7902a4267de1dcedae916f28d9a0ef5911f44bf103450  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/bindrcpp_0.2.zip  # [win64]
  sha256: 403989e8fdf5a2b2b73b5bdfc091280a1ca7b7c00c2cb61919b6babee42cd288  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/bindrcpp_0.2.tgz  # [osx]
  sha256: a7c9ac1aadf90c3668862b1b44cc2ee89549f49164b7c75d5b1a741dcd904898  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-rcpp
    - r-bindr
    - r-plogr

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-rcpp
    - r-bindr
    - r-plogr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bindrcpp')"           # [not win]
    - "\"%R%\" -e \"library('bindrcpp')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/krlmlr/bindrcpp, https://krlmlr.github.io/bindrcpp
  license: MIT + file LICENSE
  summary: Provides an easy way to fill an environment with active bindings that call a C++ function.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: bindrcpp
# Title: An 'Rcpp' Interface to Active Bindings
# Description: Provides an easy way to fill an environment with active bindings that call a C++ function.
# Authors@R: c( person("Kirill", "Muller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org"), person("RStudio", role = "cph") )
# Version: 0.2
# Date: 2017-06-15
# URL: https://github.com/krlmlr/bindrcpp, https://krlmlr.github.io/bindrcpp
# BugReports: https://github.com/krlmlr/bindrcpp/issues
# Imports: Rcpp, bindr
# Suggests: testthat
# LinkingTo: Rcpp, plogr
# RoxygenNote: 6.0.1
# LazyData: true
# License: MIT + file LICENSE
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2017-06-15 20:53:22 UTC; muelleki
# Author: Kirill Muller [aut, cre], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2017-06-17 23:52:40 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
