{% set version = '3.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-processx
  version: {{ version|replace("-", "_") }}

source:
  fn: processx_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/processx_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/processx/processx_{{ version }}.tar.gz  # [linux or win32]
  sha256: 11ac120ab4e4aa0e99c9b2eda87d07bc683bab735f1761e95e5ddacd311b5972  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/processx_3.1.0.zip  # [win64]
  sha256: 588f7b3ce61f563eb1d576a1c8bcf7a70d5d9d3b547c738205fe548861672ec1  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/processx_3.1.0.tgz  # [osx]
  sha256: 3b6a335d01165ce45708211b8fc1f63bb6e03ec79b9b398b21341a056528118f  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, debugme, parallel, testthat, withr
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]

  host:
    - mro-base
    - r-r6
    - r-assertthat
    - r-crayon
    - r-testthat

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-r6
    - r-assertthat
    - r-crayon
    - r-testthat

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('processx')"           # [not win]
    - "\"%R%\" -e \"library('processx')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/processx#readme
  license: MIT + file LICENSE
  summary: Tools to run system processes in the background. It can check if a background process
    is running; wait on a background process to finish; get the exit status of finished
    processes; kill background processes and their children; restart processes. It can
    read the standard output and error of the processes, using non-blocking connections.
    'processx' can poll a process for standard output or error, with a timeout. It can
    also poll several processes at once.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: processx
# Title: Execute and Control System Processes
# Version: 3.1.0
# Authors@R: c( person("Gabor", "Csardi", role = c("aut", "cre", "cph"), email = "csardi.gabor@gmail.com", comment = c(ORCID = "0000-0001-7098-9676")), person("Winston", "Chang", role = "aut"), person("RStudio", role = c("cph", "fnd")), person("Mango Solutions", role  = c("cph", "fnd")))
# Description: Tools to run system processes in the background. It can check if a background process is running; wait on a background process to finish; get the exit status of finished processes; kill background processes and their children; restart processes. It can read the standard output and error of the processes, using non-blocking connections. 'processx' can poll a process for standard output or error, with a timeout. It can also poll several processes at once.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-lib/processx#readme
# BugReports: https://github.com/r-lib/processx/issues
# RoxygenNote: 6.0.1.9000
# Imports: assertthat, crayon, R6, utils
# LinkingTo: testthat
# Suggests: covr, debugme, parallel, testthat, withr
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2018-05-14 20:52:07 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre, cph] (<https://orcid.org/0000-0001-7098-9676>), Winston Chang [aut], RStudio [cph, fnd], Mango Solutions [cph, fnd]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-05-15 07:48:21 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
