package:
  name: rwinlib
  version: 1

source:
  git_url: https://github.com/rwinlib/base

requirements:
  build:
    - m2-filesystem  # [win]
    - m2-git         # [win]
    - git            # [not win]

  # Try to workaround a bug where files created by activation of msys2
  # end up in the built package (/dev for example)
  host:
    - fonts-anaconda
