{% set version = '0.2-21' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeltools
  version: {{ version|replace("-", "_") }}

source:
  fn: modeltools_0.2-21.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/modeltools_0.2-21.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/modeltools/modeltools_0.2-21.tar.gz  # [linux or win32]
  sha256: 07b331475625674ab00e6ddfc479cbdbf0b22d5d237e8c25d83ddf3e0ad1cd7a  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/modeltools_0.2-21.zip  # [win64]
  sha256: dd3fa0ce0fad00f955a812f80d7f898cb3bcf10b61ab34e6427cd78f6b1ca49c  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/modeltools_0.2-21.tgz  # [osx]
  sha256: 87cb6df0a51dc6c7b353d8e75c3cd4f78ba09328c5f6cab6a5ffa51bb4c53a68  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('modeltools')"           # [not win]
    - "\"%R%\" -e \"library('modeltools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=modeltools
  license: GPL-2
  summary: A collection of tools to deal with statistical models.  The functionality is experimental
    and the user interface is likely to change in the future. The documentation is rather
    terse, but packages `coin' and `party' have some working examples. However, if you
    find the implemented ideas interesting we would be very interested in a discussion
    of this proposal. Contributions are more than welcome!
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: modeltools
# Title: Tools and Classes for Statistical Models
# Date: 2013-09-02
# Version: 0.2-21
# Author: Torsten Hothorn, Friedrich Leisch, Achim Zeileis
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Description: A collection of tools to deal with statistical models.  The functionality is experimental and the user interface is likely to change in the future. The documentation is rather terse, but packages `coin' and `party' have some working examples. However, if you find the implemented ideas interesting we would be very interested in a discussion of this proposal. Contributions are more than welcome!
# Depends: stats, stats4
# Imports: methods
# LazyLoad: yes
# License: GPL-2
# Packaged: 2013-09-02 11:15:31 UTC; hothorn
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-09-02 14:29:21

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
