{% set version = '0.10.15' %}  # [linux or win32]
{% set version = '0.10.15' %}  # [win64]
{% set version = '0.10.15' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmysql
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/RMySQL_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/RMySQL/RMySQL_{{ version }}.tar.gz  # [linux or win32]
  sha256: 7610de7ebc4c7739bf07af2b575faa620c1fa786803d3dc6704a4eeb0a3fac2e  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/RMySQL_0.10.15.zip  # [win64]
  sha256: 9d7a73e521a1d9e2df7cba8d569dfe37b207b20dd8fe47c16a724ca892428d53  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/RMySQL_0.10.15.tgz  # [osx]
  sha256: 61176ecd76dc48f8bedc86f40caf7ce264ce80fab02c7b3bccdc76444c19aa2d  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, curl
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}sed               # [win32]
    - {{posix}}grep              # [win32]
    - {{posix}}autoconf          # [linux or win32]
    - {{posix}}automake          # [linux]
    - {{posix}}automake-wrapper  # [win32]
    - {{posix}}pkg-config
    - {{posix}}make              # [linux or win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-dbi >=0.4

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-dbi >=0.4

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RMySQL')"           # [not win]
    - "\"%R%\" -e \"library('RMySQL')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://downloads.mariadb.org/connector-c/ (upstream)
  license: GPL-2
  summary: Legacy 'DBI' interface to 'MySQL' / 'MariaDB' based on old code ported from S-PLUS.
    A modern 'MySQL' client based on 'Rcpp' is available  from the 'RMariaDB' package.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: RMySQL
# Version: 0.10.15
# Title: Database Interface and 'MySQL' Driver for R
# Description: Legacy 'DBI' interface to 'MySQL' / 'MariaDB' based on old code ported from S-PLUS. A modern 'MySQL' client based on 'Rcpp' is available  from the 'RMariaDB' package.
# Authors@R: c(person("Jeroen", "Ooms", email = "jeroen@berkeley.edu",  role = c("aut", "cre"), comment = c(ORCID = "0000-0002-4035-0289")), person("David", "James", role = "aut"), person("Saikat", "DebRoy", role = "aut"), person("Hadley", "Wickham", email = "hadley@rstudio.com", role = "aut"), person("Jeffrey", "Horner", role = "aut"), person("RStudio", role = "cph"))
# Depends: R (>= 2.8.0), DBI (>= 0.4)
# Imports: methods
# License: GPL-2
# URL: https://downloads.mariadb.org/connector-c/ (upstream)
# BugReports: https://github.com/r-dbi/rmysql/issues
# SystemRequirements: libmariadb-client-dev | libmariadb-client-lgpl-dev | libmysqlclient-dev (deb), mariadb-devel (rpm), mariadb | mysql-connector-c (brew), mysql56_dev (csw)
# NeedsCompilation: yes
# Collate: 'mysql.R' 'driver.R' 'connection.R' 'data-type.R' 'default.R' 'escaping.R' 'result.R' 'extension.R' 'is-valid.R' 'table.R' 'transaction.R'
# Suggests: testthat, curl
# Packaged: 2018-05-13 17:23:38 UTC; jeroen
# Author: Jeroen Ooms [aut, cre] (<https://orcid.org/0000-0002-4035-0289>), David James [aut], Saikat DebRoy [aut], Hadley Wickham [aut], Jeffrey Horner [aut], RStudio [cph]
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-05-13 19:33:05 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
