{% set version = '0.10.14' %}  # [linux or win32]
{% set version = '0.10.14' %}  # [win64]
{% set version = '0.10.14' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmysql
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/RMySQL_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/RMySQL/RMySQL_{{ version }}.tar.gz  # [linux or win32]
  sha256: 2095aa0a9aa9fbf4dad978e105423dafab62dff0f7b5a68c17600d23ec0c0905  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/RMySQL_0.10.14.zip  # [win64]
  sha256: c0bec5511431be6d9fc4fbbcda185666db3cca55f6df6da2fe39c4a1af71c9b6  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/macosx/el-capitan/contrib/3.5/RMySQL_0.10.14.tgz  # [osx]
  sha256: f51711fc9a2ab59df66b9473af1c7bc680af7a14407369ee7ac440b4d8eae815  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, curl
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}sed               # [win32]
    - {{posix}}grep              # [win32]
    - {{posix}}autoconf          # [linux or win32]
    - {{posix}}automake          # [linux]
    - {{posix}}automake-wrapper  # [win32]
    - {{posix}}pkg-config
    - {{posix}}make              # [linux or win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-dbi >=0.4

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]
    - r-dbi >=0.4

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RMySQL')"           # [not win]
    - "\"%R%\" -e \"library('RMySQL')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://downloads.mariadb.org/connector-c/ (upstream)
  license: GPL-2
  summary: A 'DBI' interface to 'MySQL' / 'MariaDB'. The 'RMySQL' package contains an  old implementation
    based on legacy code from S-PLUS which being phased out. A modern 'MySQL' client
    based on 'Rcpp' is available from the 'RMariaDB' package.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: RMySQL
# Version: 0.10.14
# Title: Database Interface and 'MySQL' Driver for R
# Description: A 'DBI' interface to 'MySQL' / 'MariaDB'. The 'RMySQL' package contains an  old implementation based on legacy code from S-PLUS which being phased out. A modern 'MySQL' client based on 'Rcpp' is available from the 'RMariaDB' package.
# Authors@R: c(person("Jeroen", "Ooms", email = "jeroen@berkeley.edu", role = c("aut", "cre")), person("David", "James", role = "aut"), person("Saikat", "DebRoy", role = "aut"), person("Hadley", "Wickham", email = "hadley@rstudio.com", role = "aut"), person("Jeffrey", "Horner", role = "aut"), person("RStudio", role = "cph"))
# Depends: R (>= 2.8.0), DBI (>= 0.4)
# Imports: methods
# License: GPL-2
# URL: https://downloads.mariadb.org/connector-c/ (upstream)
# BugReports: https://github.com/r-dbi/rmysql/issues
# SystemRequirements: libmariadb-client-dev | libmariadb-client-lgpl-dev | libmysqlclient-dev (deb), mariadb-devel (rpm), mariadb | mysql-connector-c (brew), mysql56_dev (csw)
# NeedsCompilation: yes
# Collate: 'mysql.R' 'driver.R' 'connection.R' 'data-type.R' 'default.R' 'escaping.R' 'result.R' 'extension.R' 'is-valid.R' 'table.R' 'transaction.R'
# Suggests: testthat, curl
# Packaged: 2018-02-26 12:50:13 UTC; jeroen
# Author: Jeroen Ooms [aut, cre], David James [aut], Saikat DebRoy [aut], Hadley Wickham [aut], Jeffrey Horner [aut], RStudio [cph]
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-02-26 17:17:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
