{% set version = '0.4.9-2' %}  # [linux or win32]
{% set version = '0.4.9-2' %}  # [win64]
{% set version = '0.4.9-2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-packrat
  version: {{ version|replace("-", "_") }}

source:
    url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/packrat_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/packrat/packrat_{{ version }}.tar.gz  # [linux or win32]
  sha256: 5a7e0bf0b2f0129790a88d936c949dedcf98847ad2f088bda1b84bdc3ed60d46  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/windows/contrib/3.5/packrat_0.4.9-2.zip  # [win64]
  sha256: 6092f8ed9bdc01dc1a285cedbbb12c9bc6369fe6ca2fc2a40157dddc0c492dd9  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-04-23/bin/macosx/el-capitan/contrib/3.5/packrat_0.4.9-2.tgz  # [osx]
  sha256: cc943a9abbc33ad572b7dc60010d28ae19b9e583af99a21f14f7ea92610680a0  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 0.7), devtools, httr, knitr, rmarkdown
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('packrat')"           # [not win]
    - "\"%R%\" -e \"library('packrat')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstudio/packrat/
  license: GPL-2
  summary: Manage the R packages your project depends on in an isolated, portable, and reproducible
    way.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: packrat
# Type: Package
# Title: A Dependency Management System for Projects and their R Package Dependencies
# Version: 0.4.9-2
# Author: Kevin Ushey, Jonathan McPherson, Joe Cheng, Aron Atkins, JJ Allaire
# Maintainer: Kevin Ushey <kevin@rstudio.com>
# Description: Manage the R packages your project depends on in an isolated, portable, and reproducible way.
# License: GPL-2
# Depends: R (>= 3.0.0)
# Imports: tools, utils
# Suggests: testthat (>= 0.7), devtools, httr, knitr, rmarkdown
# Enhances: BiocInstaller
# URL: https://github.com/rstudio/packrat/
# BugReports: https://github.com/rstudio/packrat/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-04-20 03:31:02 UTC; kevin
# Repository: CRAN
# Date/Publication: 2018-04-20 04:18:14 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
