{% set version = '0.4.8-1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-packrat
  version: {{ version|replace("-", "_") }}

source:
  fn: packrat_0.4.8-1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/packrat_0.4.8-1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/packrat/packrat_0.4.8-1.tar.gz  # [linux or win32]
  sha256: a283caf4fda419e6571ae9ca6210a59002a030721feb8a50c0d0787fd6f672f3  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/packrat_0.4.8-1.zip  # [win64]
  sha256: 21db16996ef8c3bc5f036a57fc84065211d994468a3c3cc4015e9fde803fdf9c  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/packrat_0.4.8-1.tgz  # [osx]
  sha256: e491d7caaeb5b96835583710ed29abc2be3fff05846e2cb862ddf659da664491  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 0.7), devtools, httr, knitr, rmarkdown
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('packrat')"           # [not win]
    - "\"%R%\" -e \"library('packrat')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstudio/packrat/
  license: GPL-2
  summary: Manage the R packages your project depends on in an isolated, portable, and reproducible
    way.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: packrat
# Type: Package
# Title: A Dependency Management System for Projects and their R Package Dependencies
# Version: 0.4.8-1
# Author: Kevin Ushey, Jonathan McPherson, Joe Cheng, Aron Atkins, JJ Allaire
# Maintainer: Kevin Ushey <kevin@rstudio.com>
# Description: Manage the R packages your project depends on in an isolated, portable, and reproducible way.
# License: GPL-2
# Depends: R (>= 3.0.0)
# Imports: tools, utils
# Suggests: testthat (>= 0.7), devtools, httr, knitr, rmarkdown
# Enhances: BiocInstaller
# URL: https://github.com/rstudio/packrat/
# BugReports: https://github.com/rstudio/packrat/issues
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-09-07 21:30:04 UTC; kevin
# Repository: CRAN
# Date/Publication: 2016-09-07 23:37:52

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
