{% set version = '0.4-1' %}  # [linux or win32]
{% set version = '0.4-1' %}  # [win64]
{% set version = '0.4-1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-selectr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/selectr_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/selectr/selectr_{{ version }}.tar.gz  # [linux or win32]
  sha256: 8bd42f167629344e485e586f9b05fed342746132489079084d82133d7b3ee2ca  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/selectr_0.4-1.zip  # [win64]
  sha256: b5d89547670608eee38b434ffc12372ae772028c74f6b9d61173072b66f29e46  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/selectr_0.4-1.tgz  # [osx]
  sha256: 42cc47ba03bf48882c8f83ff6a58fbe6db194c565841ce95ee1537ee804dc0d0  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, XML, xml2
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-r6
    - r-stringr

  run:
    - mro-base
    - r-r6
    - r-stringr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('selectr')"           # [not win]
    - "\"%R%\" -e \"library('selectr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://sjp.co.nz/projects/selectr
  license: BSD_3_clause + file LICENCE
  summary: Translates a CSS3 selector into an equivalent XPath expression. This allows us to
    use CSS selectors when working with the XML package as it can only evaluate XPath
    expressions. Also provided are convenience functions useful for using CSS selectors
    on XML nodes. This package is a port of the Python package 'cssselect' (<https://cssselect.readthedocs.io/>).
  license_family: BSD

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: selectr
# Type: Package
# Title: Translate CSS Selectors to XPath Expressions
# Version: 0.4-1
# Date: 2018-04-05
# Authors@R: c(person("Simon", "Potter", role = c("aut", "trl", "cre"), email = "simon@sjp.co.nz"), person("Simon", "Sapin", role = "aut"), person("Ian", "Bicking", role = "aut"))
# License: BSD_3_clause + file LICENCE
# Depends: R (>= 3.0)
# Imports: methods, stringr, R6
# Suggests: testthat, XML, xml2
# URL: https://sjp.co.nz/projects/selectr
# BugReports: https://github.com/sjp/selectr/issues
# Description: Translates a CSS3 selector into an equivalent XPath expression. This allows us to use CSS selectors when working with the XML package as it can only evaluate XPath expressions. Also provided are convenience functions useful for using CSS selectors on XML nodes. This package is a port of the Python package 'cssselect' (<https://cssselect.readthedocs.io/>).
# NeedsCompilation: no
# Packaged: 2018-04-06 00:16:15 UTC; simon
# Author: Simon Potter [aut, trl, cre], Simon Sapin [aut], Ian Bicking [aut]
# Maintainer: Simon Potter <simon@sjp.co.nz>
# Repository: CRAN
# Date/Publication: 2018-04-06 04:14:27 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
