{% set version = '0.4-7' %}  # [linux or win32]
{% set version = '0.4-7' %}  # [win64]
{% set version = '0.4-7' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gridbase
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/gridBase_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/gridBase/gridBase_{{ version }}.tar.gz  # [linux or win32]
  sha256: be8718d24cd10f6e323dce91b15fc40ed88bccaa26acf3192d5e38fe33e15f26  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/gridBase_0.4-7.zip  # [win64]
  sha256: e75a5005b0148f52e530d676a31690ea6ba5b46618cff8433d20869989c5edda  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/gridBase_0.4-7.tgz  # [osx]
  sha256: 4af91a16df757d0912b64cb373e58a29d291f8406375a861614c2b34ddf65005  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: lattice
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gridBase')"           # [not win]
    - "\"%R%\" -e \"library('gridBase')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=gridBase
  license: GPL
  summary: Integration of base and grid graphics
  license_family: GPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: gridBase
# Title: Integration of base and grid graphics
# Version: 0.4-7
# Author: Paul Murrell
# Depends: R (>= 2.3.0)
# Imports: graphics, grid
# Suggests: lattice
# Description: Integration of base and grid graphics
# Maintainer: Paul Murrell <paul@stat.auckland.ac.nz>
# License: GPL
# Packaged: 2014-02-24 01:35:23 UTC; EC\pmur002
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-02-24 07:20:37

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
