{% set version = '0.12.14' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcpp
  version: {{ version|replace("-", "_") }}

source:
  fn: Rcpp_0.12.14.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Rcpp_0.12.14.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/Rcpp/Rcpp_0.12.14.tar.gz  # [linux or win32]
  sha256: da28fcfc3fe7c48d02f9f3e309b56f4be52b14a01216a23e3de8f9d6deeb7e63  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/Rcpp_0.12.14.zip  # [win64]
  sha256: 6dcfc3eb48977e46c7c7e2d088a900e1b38f3146ae64872b51ad99c746b8e648  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/Rcpp_0.12.14.tgz  # [osx]
  sha256: 6aab6f3da849ed560e33c63637fae8fdb7b6f6af7c72528f0b190c6c10d3aef2  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit, inline, rbenchmark, knitr, rmarkdown, pinp, pkgKitten (>= 0.1.2)
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('cxx') }}        # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('Rcpp')"           # [not win]
    - "\"%R%\" -e \"library('Rcpp')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.rcpp.org, http://dirk.eddelbuettel.com/code/rcpp.html, https://github.com/RcppCore/Rcpp
  license: GPL (>= 2)
  summary: The 'Rcpp' package provides R functions as well as C++ classes which offer a seamless
    integration of R and C++. Many R data types and objects can be mapped back and forth
    to C++ equivalents which facilitates both writing of new code as well as easier
    integration of third-party libraries. Documentation  about 'Rcpp' is provided by
    several vignettes included in this package, via the  'Rcpp Gallery' site at <http://gallery.rcpp.org>,
    the paper by Eddelbuettel and  Francois (2011, <doi:10.18637/jss.v040.i08>), the
    book by Eddelbuettel (2013, <doi:10.1007/978-1-4614-6868-4>) and the paper by Eddelbuettel
    and Balamuta (2017, <doi:10.7287/peerj.preprints.3188v1>); see 'citation("Rcpp")'
    for details.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: Rcpp
# Title: Seamless R and C++ Integration
# Version: 0.12.14
# Date: 2017-11-17
# Author: Dirk Eddelbuettel, Romain Francois, JJ Allaire, Kevin Ushey, Qiang Kou, Nathan Russell, Douglas Bates and John Chambers
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Description: The 'Rcpp' package provides R functions as well as C++ classes which offer a seamless integration of R and C++. Many R data types and objects can be mapped back and forth to C++ equivalents which facilitates both writing of new code as well as easier integration of third-party libraries. Documentation  about 'Rcpp' is provided by several vignettes included in this package, via the  'Rcpp Gallery' site at <http://gallery.rcpp.org>, the paper by Eddelbuettel and  Francois (2011, <doi:10.18637/jss.v040.i08>), the book by Eddelbuettel (2013, <doi:10.1007/978-1-4614-6868-4>) and the paper by Eddelbuettel and Balamuta (2017, <doi:10.7287/peerj.preprints.3188v1>); see 'citation("Rcpp")' for details.
# Depends: R (>= 3.0.0)
# Imports: methods, utils
# Suggests: RUnit, inline, rbenchmark, knitr, rmarkdown, pinp, pkgKitten (>= 0.1.2)
# VignetteBuilder: knitr
# URL: http://www.rcpp.org, http://dirk.eddelbuettel.com/code/rcpp.html, https://github.com/RcppCore/Rcpp
# License: GPL (>= 2)
# BugReports: https://github.com/RcppCore/Rcpp/issues
# MailingList: Please send questions and comments regarding Rcpp to rcpp-devel@lists.r-forge.r-project.org
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-11-17 12:51:38.259396 UTC; edd
# Repository: CRAN
# Date/Publication: 2017-11-23 21:24:19 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
