{% set version = '1.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-callr
  version: {{ version|replace("-", "_") }}

source:
  fn: callr_1.0.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/callr_1.0.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/callr/callr_1.0.0.tar.gz  # [linux or win32]
  sha256: 2c56808c723aba2ea8a8b6bbdc9b8332c96f59b119079861dd52f5988c27f715  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/callr_1.0.0.zip  # [win64]
  sha256: f3b6b517501a8760f51baa7b06bce47fa59c3ec148ffac1e279070654a90f605  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/callr_1.0.0.tgz  # [osx]
  sha256: 072cab2554372fdaeade153be7048777fa6c86b47a80209254fa15fa35e8daff  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, testthat
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('callr')"           # [not win]
    - "\"%R%\" -e \"library('callr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/MangoTheCat/callr
  license: MIT + file LICENSE
  summary: It is sometimes useful to perform a computation in a separate R process, without affecting
    the current R process at all. This packages does exactly that.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: callr
# Title: Call R from R
# Version: 1.0.0
# Author: Gabor Csardi
# Maintainer: Gabor Csardi <gcsardi@mango-solutions.com>
# Description: It is sometimes useful to perform a computation in a separate R process, without affecting the current R process at all. This packages does exactly that.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/MangoTheCat/callr
# BugReports: https://github.com/MangoTheCat/callr/issues
# RoxygenNote: 5.0.1.9000
# Suggests: covr, testthat
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2016-06-17 21:09:31 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2016-06-18 15:24:15

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
