{% set version = '0.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-highcharter
  version: {{ version|replace("-", "_") }}

source:
  fn: highcharter_0.5.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/highcharter_0.5.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/highcharter/highcharter_0.5.0.tar.gz  # [linux or win32]
  sha256: d77ab493f6eb8648b352205df1bf60848c8f2155d46920077bac57809cbbded7  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/highcharter_0.5.0.zip  # [win64]
  sha256: 61da8750ae0ea0312a7bb894ed5d07bdd85965d8291659f22eedc2273c996bbc  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/highcharter_0.5.0.tgz  # [osx]
  sha256: e787667fd7df274401d53ac01a76ef8b2265924db5c646a3eaeaa5bc3f1a5c6a  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, survival, ggplot2, httr, viridisLite
requirements:
  build:

  host:
    - mro-base
    - r-assertthat
    - r-broom
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets
    - r-igraph
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-quantmod
    - r-rlist
    - r-stringr
    - r-tibble >=1.1
    - r-tidyr
    - r-xts
    - r-zoo

  run:
    - mro-base
    - r-assertthat
    - r-broom
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets
    - r-igraph
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-quantmod
    - r-rlist
    - r-stringr
    - r-tibble >=1.1
    - r-tidyr
    - r-xts
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('highcharter')"           # [not win]
    - "\"%R%\" -e \"library('highcharter')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://jkunst.com/highcharter
  license: MIT + file LICENSE
  summary: A wrapper for the 'Highcharts' library including shortcut functions to plot R objects.
    'Highcharts'  <http://www.highcharts.com/> is a charting library offering numerous
    chart types with a simple configuration syntax.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: highcharter
# Type: Package
# Version: 0.5.0
# Title: A Wrapper for the 'Highcharts' Library
# Description: A wrapper for the 'Highcharts' library including shortcut functions to plot R objects. 'Highcharts'  <http://www.highcharts.com/> is a charting library offering numerous chart types with a simple configuration syntax.
# Authors@R: c( person("Joshua", "Kunst", role = c("aut", "cre"), email = "jbkunst@gmail.com"), person("Nuno", "Agostinho", role = c("ctb"), comment  = "hchart.survfit, densities and hc_add_series_scatter"),   person("Eduardo", "Flores", role = c("ctb"), comment  = "First version hc_add_series_df_tidy"), person("Dean", "Kilfoyle", role = c("ctb"), comment  = "First version hc_add_series_boxplot"), person("Adline", "Dsilva", role = c("ctb"), comment  = "First version Matrix heatmap") )
# Date: 2016-09-05
# URL: http://jkunst.com/highcharter
# BugReports: https://github.com/jbkunst/highcharter/issues
# Maintainer: Joshua Kunst <jbkunst@gmail.com>
# License: MIT + file LICENSE
# RoxygenNote: 5.0.1
# Depends: R (>= 2.10)
# Imports: htmlwidgets, magrittr, purrr, rlist, assertthat, zoo, dplyr, tibble (>= 1.1), stringr, broom, xts, quantmod, tidyr, htmltools, jsonlite, igraph, lubridate
# Suggests: knitr, rmarkdown, survival, ggplot2, httr, viridisLite
# VignetteBuilder: knitr
# LazyData: true
# NeedsCompilation: no
# Packaged: 2017-01-17 02:03:58 UTC; Joshua
# Author: Joshua Kunst [aut, cre], Nuno Agostinho [ctb] (hchart.survfit, densities and hc_add_series_scatter), Eduardo Flores [ctb] (First version hc_add_series_df_tidy), Dean Kilfoyle [ctb] (First version hc_add_series_boxplot), Adline Dsilva [ctb] (First version Matrix heatmap)
# Repository: CRAN
# Date/Publication: 2017-01-17 08:36:29

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
