{% set version = '0.2-7.1' %}  # [linux or win32]
{% set version = '0.2-7.1' %}  # [win64]
{% set version = '0.2-7.1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rjdbc
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/RJDBC_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/RJDBC/RJDBC_{{ version }}.tar.gz  # [linux or win32]
  sha256: 4540ad34a6dc46b07aee4da39e79872088b72da2f96ce8bad4f0513e879666b4  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/RJDBC_0.2-7.1.zip  # [win64]
  sha256: a5881d687fc7e0c21744158f78909ea4d5c6be7285816b45fbbc9f906d2004e3  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/RJDBC_0.2-7.1.tgz  # [osx]
  sha256: d1b6d998a37fdcfdeb06db8df115964fa2696631c6f645b0485859968137dc81  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-dbi
    - r-rjava >=0.4_15

  run:
    - mro-base
    - r-dbi
    - r-rjava >=0.4_15

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RJDBC')"           # [not win]
    - "\"%R%\" -e \"library('RJDBC')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.rforge.net/RJDBC/
  license: MIT + file LICENSE
  summary: The RJDBC package is an implementation of R's DBI interface using JDBC as a back-end.
    This allows R to connect to any DBMS that has a JDBC driver.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: RJDBC
# Version: 0.2-7.1
# Title: Provides Access to Databases Through the JDBC Interface
# Author: Simon Urbanek <Simon.Urbanek@r-project.org>
# Maintainer: Simon Urbanek <Simon.Urbanek@r-project.org>
# Depends: methods, DBI, rJava (>= 0.4-15), R (>= 2.4.0)
# Description: The RJDBC package is an implementation of R's DBI interface using JDBC as a back-end. This allows R to connect to any DBMS that has a JDBC driver.
# License: MIT + file LICENSE
# URL: http://www.rforge.net/RJDBC/
# NeedsCompilation: no
# Packaged: 2018-04-16 13:03:02 UTC; hornik
# Repository: CRAN
# Date/Publication: 2018-04-16 15:01:33 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
