{% set version = '1.1.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-utf8
  version: {{ version|replace("-", "_") }}

source:
  fn: utf8_{{ version }}.tar.gz   # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/utf8_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/utf8/utf8_{{ version }}.tar.gz  # [linux or win32]
  sha256: f6da9cadfc683057d45f54b43312a359cf96ec2731c0dda18a8eae31d1e31e54  # [linux or win32]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/windows/contrib/3.5/utf8_1.1.4.zip  # [win64]
  sha256: fd18f3d01d1ee9b1419878861e62ce6e770cb8ed532d46e4130a250404dfc91b  # [win64]

  url: https://mran.microsoft.com/snapshot/2018-06-01/bin/macosx/el-capitan/contrib/3.5/utf8_1.1.4.tgz  # [osx]
  sha256: c4139fdb54bf577fe78bc6b8af08f2564db47b1965359f43084da855b9ff3b34  # [osx]

build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('utf8')"           # [not win]
    - "\"%R%\" -e \"library('utf8')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/patperry/r-utf8
  license: Apache License (== 2.0) | file LICENSE
  summary: Process and print 'UTF-8' encoded international text (Unicode). Input, validate, normalize,
    encode, format, and display.
  license_family: APACHE

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: utf8
# Version: 1.1.4
# Title: Unicode Text Processing
# Authors@R: c( person(c("Patrick", "O."), "Perry", role = c("aut", "cph", "cre"), email = "patperry@gmail.com"), person("Unicode, Inc.", role = c("cph", "dtc"), comment = "Unicode Character Database"))
# Depends: R (>= 2.10)
# Suggests: knitr, rmarkdown, testthat
# Description: Process and print 'UTF-8' encoded international text (Unicode). Input, validate, normalize, encode, format, and display.
# License: Apache License (== 2.0) | file LICENSE
# URL: https://github.com/patperry/r-utf8
# BugReports: https://github.com/patperry/r-utf8/issues
# LazyData: Yes
# Encoding: UTF-8
# VignetteBuilder: knitr, rmarkdown
# NeedsCompilation: yes
# Packaged: 2018-05-24 15:00:57 UTC; ptrck
# Author: Patrick O. Perry [aut, cph, cre], Unicode, Inc. [cph, dtc] (Unicode Character Database)
# Maintainer: Patrick O. Perry <patperry@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-05-24 17:09:15 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
