{% set version = '2.2.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r6
  version: {{ version|replace("-", "_") }}

source:
  fn: R6_2.2.2.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/R6_2.2.2.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/R6/R6_2.2.2.tar.gz  # [linux or win32]
  sha256: 087756f471884c3b3ead80215a7cc5636a78b8a956e91675acfe2896426eae8f  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/R6_2.2.2.zip  # [win64]
  sha256: 75df2240ccf7b016bc16203606210b6895661a9275b7ea5150328ec2f198bf3f  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/R6_2.2.2.tgz  # [osx]
  sha256: 4113783e60d5dc9da8b823eb5c377e4257b52d9404006d5ac51122a1836cf187  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, microbenchmark, pryr, testthat, ggplot2, scales
requirements:
  build:

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('R6')"           # [not win]
    - "\"%R%\" -e \"library('R6')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/wch/R6/
  license: MIT + file LICENSE
  summary: The R6 package allows the creation of classes with reference semantics, similar to
    R's built-in reference classes. Compared to reference classes, R6 classes are simpler
    and lighter-weight, and they are not built on S4 classes so they do not require
    the methods package. These classes allow public and private members, and they support
    inheritance, even when the classes are defined in different packages.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: R6
# Title: Classes with Reference Semantics
# Version: 2.2.2
# Authors@R: person("Winston", "Chang", role = c("aut", "cre"), email = "winston@stdout.org")
# Description: The R6 package allows the creation of classes with reference semantics, similar to R's built-in reference classes. Compared to reference classes, R6 classes are simpler and lighter-weight, and they are not built on S4 classes so they do not require the methods package. These classes allow public and private members, and they support inheritance, even when the classes are defined in different packages.
# Depends: R (>= 3.0)
# Suggests: knitr, microbenchmark, pryr, testthat, ggplot2, scales
# License: MIT + file LICENSE
# URL: https://github.com/wch/R6/
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-06-12 18:48:43 UTC; winston
# Author: Winston Chang [aut, cre]
# Maintainer: Winston Chang <winston@stdout.org>
# Repository: CRAN
# Date/Publication: 2017-06-17 08:22:59 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
