{% set version = '7.3-12' %}  # [linux or win32 or osx]
{% set version = '7.3-12' %}  # [win64]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nnet
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/nnet_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/nnet/nnet_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 2723523e8581cc0e2215435ac773033577a16087a3f41d111757dd96b8c5559d  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/nnet_7.3-12.zip  # [win64]
  sha256: e7cf7153387d04772af86ebf764700e61a7603cb9b7e8bfa4f81da58ab1b3e33  # [win64]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS
requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{native}}rtools           # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('nnet')"           # [not win]
    - "\"%R%\" -e \"library('nnet')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.stats.ox.ac.uk/pub/MASS4/
  license: GPL-2 | GPL-3
  summary: Software for feed-forward neural networks with a single hidden layer, and for multinomial
    log-linear models.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: nnet
# Priority: recommended
# Version: 7.3-12
# Date: 2016-02-02
# Depends: R (>= 2.14.0), stats, utils
# Suggests: MASS
# Authors@R: c(person("Brian", "Ripley", role = c("aut", "cre", "cph"), email = "ripley@stats.ox.ac.uk"), person("William", "Venables", role = "cph"))
# Description: Software for feed-forward neural networks with a single hidden layer, and for multinomial log-linear models.
# Title: Feed-Forward Neural Networks and Multinomial Log-Linear Models
# ByteCompile: yes
# License: GPL-2 | GPL-3
# URL: http://www.stats.ox.ac.uk/pub/MASS4/
# NeedsCompilation: yes
# Packaged: 2016-02-02 09:12:29 UTC; ripley
# Author: Brian Ripley [aut, cre, cph], William Venables [cph]
# Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
# Repository: CRAN
# Date/Publication: 2016-02-02 14:52:39

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
