{% set version = '1.2' %}  # [linux or win32]
{% set version = '1.2' %}  # [win64]
{% set version = '1.2' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmlwidgets
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/htmlwidgets_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/htmlwidgets/htmlwidgets_{{ version }}.tar.gz  # [linux or win32]
  sha256: 1a7d21c1f3306d53a36c05d6ea7873ddeffeda654cd9be689b6d78e62a688411  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/htmlwidgets_1.2.zip  # [win64]
  sha256: ac683af87847966459ff8c35ee8242e24603accf0a0fca759343871f7f0f179c  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/htmlwidgets_1.2.tgz  # [osx]
  sha256: d00095f6f4de50b1bfc53a322b84a0ce579c0f96371b6e057fe5cfb43734dba3  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr (>= 1.8)
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-htmltools >=0.3
    - r-jsonlite >=0.9.16
    - r-yaml

  run:
    - mro-base
    - r-htmltools >=0.3
    - r-jsonlite >=0.9.16
    - r-yaml

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('htmlwidgets')"           # [not win]
    - "\"%R%\" -e \"library('htmlwidgets')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ramnathv/htmlwidgets
  license: MIT + file LICENSE
  summary: A framework for creating HTML widgets that render in various contexts including the
    R console, 'R Markdown' documents, and 'Shiny' web applications.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: htmlwidgets
# Type: Package
# Title: HTML Widgets for R
# Version: 1.2
# Authors@R: c( person("Ramnath", "Vaidyanathan", role = c("aut", "cph")), person("Yihui", "Xie", role = c("aut")), person("JJ", "Allaire", role = c("aut", "cre"), email = "jj@rstudio.com"), person("Joe", "Cheng", role = c("aut")), person("Kenton", "Russell", role = c("aut", "cph")), person(family = "RStudio", role = "cph") )
# Description: A framework for creating HTML widgets that render in various contexts including the R console, 'R Markdown' documents, and 'Shiny' web applications.
# License: MIT + file LICENSE
# VignetteBuilder: knitr
# Imports: grDevices, htmltools (>= 0.3), jsonlite (>= 0.9.16), yaml
# Suggests: knitr (>= 1.8)
# Enhances: shiny (>= 1.0.5)
# URL: https://github.com/ramnathv/htmlwidgets
# BugReports: https://github.com/ramnathv/htmlwidgets/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-04-18 14:06:07 UTC; jjallaire
# Author: Ramnath Vaidyanathan [aut, cph], Yihui Xie [aut], JJ Allaire [aut, cre], Joe Cheng [aut], Kenton Russell [aut, cph], RStudio [cph]
# Maintainer: JJ Allaire <jj@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-04-19 12:43:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
