{% set version = '0.1-3' %}  # [linux or win32]
{% set version = '0.1-3' %}  # [win64]
{% set version = '0.1-3' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-base64enc
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/base64enc_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/base64enc/base64enc_{{ version }}.tar.gz  # [linux or win32]
  sha256: 6d856d8a364bcdc499a0bf38bfd283b7c743d08f0b288174fba7dbf0a04b688d  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/base64enc_0.1-3.zip  # [win64]
  sha256: debf32da63a2cbd1d66c119b971cb7821c00b81c31c1d5879976e9be5c8ac6aa  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/base64enc_0.1-3.tgz  # [osx]
  sha256: 943714b4762990a247f5725e76605e22d6b50ef2b4c37dc03493f7c9052f2eec  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('base64enc')"           # [not win]
    - "\"%R%\" -e \"library('base64enc')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.rforge.net/base64enc
  license: GPL-2 | GPL-3
  summary: This package provides tools for handling base64 encoding. It is more flexible than
    the orphaned base64 package.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: base64enc
# Version: 0.1-3
# Title: Tools for base64 encoding
# Author: Simon Urbanek <Simon.Urbanek@r-project.org>
# Maintainer: Simon Urbanek <Simon.Urbanek@r-project.org>
# Depends: R (>= 2.9.0)
# Enhances: png
# Description: This package provides tools for handling base64 encoding. It is more flexible than the orphaned base64 package.
# License: GPL-2 | GPL-3
# URL: http://www.rforge.net/base64enc
# NeedsCompilation: yes
# Packaged: 2015-02-04 20:31:00 UTC; svnuser
# Repository: CRAN
# Date/Publication: 2015-07-28 08:03:37

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
