{% set version = '0.13' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-udunits2
  version: {{ version|replace("-", "_") }}

source:
  fn: udunits2_0.13.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/udunits2_0.13.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/udunits2/udunits2_0.13.tar.gz  # [linux or win32]
  sha256: d155d3c07f6202b65dec4075ffd1e1c3f4f35f5fdece8cfb319d39256a3e5b79  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/udunits2_0.13.zip  # [win64]
  sha256: ac169f52f077cd5a91b4a037590c71f948ea501645383d6633cadeb0be333cfa  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/udunits2_0.13.tgz  # [osx]
  sha256: 4ebf164f1ba51d384b7800e91533ffe0c0c6ea79e27e95e76ea16a5efb9d72f3  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}sed                 # [win32]
    - {{posix}}grep                # [win32]
    - {{posix}}autoconf            # [linux or win32]
    - {{posix}}automake-wrapper    # [win32]
    - {{posix}}automake            # [win32]
    - {{posix}}pkg-config
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('udunits2')"           # [not win]
    - "\"%R%\" -e \"library('udunits2')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/pacificclimate/Rudunits2 https://www.unidata.ucar.edu/software/udunits/
  license: GPL-2
  summary: Provides simple bindings to Unidata's udunits library.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: udunits2
# Type: Package
# Title: Udunits-2 Bindings for R
# Version: 0.13
# Date: 2016-11-16
# Author: James Hiebert <hiebert@uvic.ca>
# Maintainer: James Hiebert <hiebert@uvic.ca>
# Description: Provides simple bindings to Unidata's udunits library.
# URL: https://github.com/pacificclimate/Rudunits2 https://www.unidata.ucar.edu/software/udunits/
# SystemRequirements: udunits-2
# License: GPL-2
# LazyLoad: yes
# Depends: R (>= 2.10.0)
# NeedsCompilation: yes
# Packaged: 2016-11-16 23:23:15 UTC; james
# Repository: CRAN
# Date/Publication: 2016-11-17 08:27:56

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
