{% set version = '1.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pillar
  version: {{ version|replace("-", "_") }}

source:
  fn: pillar_1.0.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/pillar_1.0.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/pillar/pillar_1.0.1.tar.gz  # [linux or win32]
  sha256: 7b37189ab9ab0bbf2e6f49e9d5e678acb31500739d3c3ea2b5326b457716277d  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/pillar_1.0.1.zip  # [win64]
  sha256: a729f27d1c98fb9db77d7993c1c1bacf044c7c5eb9de26e33a19c43e426fa77d  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/pillar_1.0.1.tgz  # [osx]
  sha256: 213edd0769277ddd2c34a57fadc36a9ef2d776abde7a3f3b84a6356fddb1eded  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat
requirements:
  build:

  host:
    - mro-base
    - r-cli
    - r-crayon >=1.3.4
    - r-rlang
    - r-utf8

  run:
    - mro-base
    - r-cli
    - r-crayon >=1.3.4
    - r-rlang
    - r-utf8

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pillar')"           # [not win]
    - "\"%R%\" -e \"library('pillar')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/pillar
  license: GPL-3
  summary: Provides a 'pillar' generic designed for formatting columns of data using the full
    range of colours provided by modern terminals.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: pillar
# Title: Coloured Formatting for Columns
# Version: 1.0.1
# Authors@R: c( person("Kirill", "Muller", , "krlmlr+r@mailbox.org", role = c("aut", "cre")), person("Hadley", "Wickham", role = "aut"), person("RStudio", role = "cph") )
# Description: Provides a 'pillar' generic designed for formatting columns of data using the full range of colours provided by modern terminals.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/hadley/pillar
# BugReports: https://github.com/hadley/pillar/issues
# Imports: cli, crayon (>= 1.3.4), methods, rlang, utf8
# Suggests: knitr, testthat
# RoxygenNote: 6.0.1
# Collate: 'compat-purrr.R' 'dim.R' 'extent.R' 'multi.R' 'ornament.R' 'pillar.R' 'rowid-data.R' 'rowid-title.R' 'rowid-type.R' 'scientific.R' 'shaft.R' 'shaft-simple.R' 'sigfig.R' 'spark-bar.R' 'spark-line.R' 'strrep.R' 'styles.R' 'testthat.R' 'tick.R' 'title.R' 'type-sum.R' 'type.R' 'utils.R' 'width.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2017-11-27 10:31:09 UTC; muelleki
# Author: Kirill Muller [aut, cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2017-11-27 10:34:24 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
