{% set version = '0.9-26' %}  # [linux or win32]
{% set version = '0.9-26' %}  # [win64]
{% set version = '0.9-26' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kernlab
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/kernlab_{{ version }}.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/kernlab/kernlab_{{ version }}.tar.gz  # [linux or win32 or osx]
  sha256: 954940478c6fcf60433e50e43cf10d70bcb0a809848ca8b9d683bf371cd56077  # [linux or win32 or osx]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/kernlab_0.9-26.zip  # [win64]
  sha256: 7d7a4f0a97927a8deb6cce631dd9e2a2f2afe6f035b69ff9de8f0be2312260d0  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/kernlab_0.9-26.tgz  # [osx and false]
  sha256: 58c08c4e61300bc542baca4129081edc29b82538bb950500942b6407e76d41b9  # [osx and false]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux or osx]
    - {{ compiler('cxx') }}      # [linux or osx]
    - {{ compiler('fortran') }}  # [linux]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('kernlab')"           # [not win]
    - "\"%R%\" -e \"library('kernlab')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=kernlab
  license: GPL-2
  summary: Kernel-based machine learning methods for classification, regression, clustering,
    novelty detection, quantile regression and dimensionality reduction.  Among other
    methods 'kernlab' includes Support Vector Machines, Spectral Clustering, Kernel
    PCA, Gaussian Processes and a QP solver.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: kernlab
# Version: 0.9-26
# Title: Kernel-Based Machine Learning Lab
# Authors@R: c(person("Alexandros", "Karatzoglou", role = c("aut", "cre"), email = "alexandros.karatzoglou@gmail.com"), person("Alex", "Smola", role = "aut"), person("Kurt", "Hornik", role = "aut"))
# Description: Kernel-based machine learning methods for classification, regression, clustering, novelty detection, quantile regression and dimensionality reduction.  Among other methods 'kernlab' includes Support Vector Machines, Spectral Clustering, Kernel PCA, Gaussian Processes and a QP solver.
# Depends: R (>= 2.10)
# Imports: methods, stats, grDevices, graphics
# LazyLoad: Yes
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2018-04-30 15:49:11 UTC; hornik
# Author: Alexandros Karatzoglou [aut, cre], Alex Smola [aut], Kurt Hornik [aut]
# Maintainer: Alexandros Karatzoglou <alexandros.karatzoglou@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-04-30 15:53:29 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
