{% set version = '1.5-9' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cairo
  version: {{ version|replace("-", "_") }}

source:
  fn: Cairo_1.5-9.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Cairo_1.5-9.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/Cairo/Cairo_1.5-9.tar.gz  # [linux or win32]
  sha256: 2a867b6cae96671d6bc3acf9334d6615dc01f6ecf1953a27cde8a43c724a38f4  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/Cairo_1.5-9.zip  # [win64]
  sha256: 6f8c8e3de5ef0c73cfe332d32e0f28711518da8d43da3ea68520cec1d0da3871  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/Cairo_1.5-9.tgz  # [osx]
  sha256: 96b903c66fbebf6764ad272ebb63c07a8bbe9f62b19ce4454549e41f40600bdb  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: png
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}sed                 # [win32]
    - {{posix}}grep                # [win32]
    - {{posix}}autoconf            # [linux or win32]
    - {{posix}}automake-wrapper    # [win32]
    - {{posix}}automake            # [win32]
    - {{posix}}pkg-config
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('Cairo')"           # [not win]
    - "\"%R%\" -e \"library('Cairo')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.rforge.net/Cairo/
  license: GPL-2
  summary: Cairo graphics device that can be use to create high-quality vector (PDF, PostScript
    and SVG) and bitmap output (PNG,JPEG,TIFF), and high-quality rendering in displays
    (X11 and Win32). Since it uses the same back-end for all output, copying across
    formats is WYSIWYG. Files are created without the dependence on X11 or other external
    programs. This device supports alpha channel (semi-transparent drawing) and resulting
    images can contain transparent and semi-transparent regions. It is ideal for use
    in server environments (file output) and as a replacement for other devices that
    don't have Cairo's capabilities such as alpha support or anti-aliasing. Backends
    are modular such that any subset of backends is supported.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: Cairo
# Version: 1.5-9
# Title: R graphics device using cairo graphics library for creating high-quality bitmap (PNG, JPEG, TIFF), vector (PDF, SVG, PostScript) and display (X11 and Win32) output
# Author: Simon Urbanek <Simon.Urbanek@r-project.org>, Jeffrey Horner <jeff.horner@vanderbilt.edu>
# Maintainer: Simon Urbanek <Simon.Urbanek@r-project.org>
# Depends: R (>= 2.4.0)
# Imports: grDevices, graphics
# Suggests: png
# Enhances: FastRWeb
# Description: Cairo graphics device that can be use to create high-quality vector (PDF, PostScript and SVG) and bitmap output (PNG,JPEG,TIFF), and high-quality rendering in displays (X11 and Win32). Since it uses the same back-end for all output, copying across formats is WYSIWYG. Files are created without the dependence on X11 or other external programs. This device supports alpha channel (semi-transparent drawing) and resulting images can contain transparent and semi-transparent regions. It is ideal for use in server environments (file output) and as a replacement for other devices that don't have Cairo's capabilities such as alpha support or anti-aliasing. Backends are modular such that any subset of backends is supported.
# License: GPL-2
# SystemRequirements: cairo (>= 1.2 http://www.cairographics.org/)
# URL: http://www.rforge.net/Cairo/
# NeedsCompilation: yes
# Packaged: 2015-09-25 17:49:11 UTC; svnuser
# Repository: CRAN
# Date/Publication: 2015-09-26 09:05:40

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
