{% set version = '0.5.0' %}  # [linux or win32]
{% set version = '0.5.0' %}  # [win64]
{% set version = '0.5.0' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-munsell
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/munsell_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/munsell/munsell_{{ version }}.tar.gz  # [linux or win32]
  sha256: d0f3a9fb30e2b5d411fa61db56d4be5733a2621c0edf017d090bdfa5e377e199  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/munsell_0.5.0.zip  # [win64]
  sha256: d36387e7d65495867449743b04a5508c9db0e2be42c5feee3286ef049acf33af  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/munsell_0.5.0.tgz  # [osx]
  sha256: 122e37f2a62c4a0d13465e9bf6661e4a268470b6b35c3887649b5a6b202dc3f8  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: ggplot2, testthat
requirements:
  build:
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-colorspace

  run:
    - mro-base
    - r-colorspace

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('munsell')"           # [not win]
    - "\"%R%\" -e \"library('munsell')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://cran.r-project.org/package=munsell, https://github.com/cwickham/munsell/
  license: MIT + file LICENSE
  summary: Provides easy access to, and manipulation of, the Munsell  colours. Provides a mapping
    between Munsell's  original notation (e.g. "5R 5/10") and hexadecimal strings suitable  for
    use directly in R graphics. Also provides utilities  to explore slices through the
    Munsell colour tree, to transform  Munsell colours and display colour palettes.
  license_family: MIT

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: munsell
# Type: Package
# Title: Utilities for Using Munsell Colours
# Version: 0.5.0
# Author: Charlotte Wickham <cwickham@gmail.com>
# Maintainer: Charlotte Wickham <cwickham@gmail.com>
# Description: Provides easy access to, and manipulation of, the Munsell  colours. Provides a mapping between Munsell's  original notation (e.g. "5R 5/10") and hexadecimal strings suitable  for use directly in R graphics. Also provides utilities  to explore slices through the Munsell colour tree, to transform  Munsell colours and display colour palettes.
# Suggests: ggplot2, testthat
# Imports: colorspace, methods
# License: MIT + file LICENSE
# URL: https://cran.r-project.org/package=munsell, https://github.com/cwickham/munsell/
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-06-11 23:15:15 UTC; wickhamc
# Repository: CRAN
# Date/Publication: 2018-06-12 04:29:06 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
