{% set version = '0.4-1' %}  # [linux or win32]
{% set version = '0.4-1' %}  # [win64]
{% set version = '0.4-1' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-matrixmodels
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/MatrixModels_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/MatrixModels/MatrixModels_{{ version }}.tar.gz  # [linux or win32]
  sha256: fe878e401e697992a480cd146421c3a10fa331f6b37a51bac83b5c1119dcce33  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/MatrixModels_0.4-1.zip  # [win64]
  sha256: 405669a222cee7d63a89d856eeca03fd76573c4a79ac11b488f14047a6cb1c73  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/MatrixModels_0.4-1.tgz  # [osx]
  sha256: f0b3cbe8276605733b86da2951bade59ec37aaaafeeb3364719dd0f5c626fc67  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base
    - r-matrix >=1.1_5

  run:
    - mro-base
    - r-matrix >=1.1_5

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('MatrixModels')"           # [not win]
    - "\"%R%\" -e \"library('MatrixModels')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://Matrix.R-forge.R-project.org/
  license: GPL (>= 2)
  summary: Modelling with sparse and dense 'Matrix' matrices, using modular prediction and response
    module classes.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: MatrixModels
# Version: 0.4-1
# Date: 2015-08-22
# Title: Modelling with Sparse And Dense Matrices
# Author: Douglas Bates <bates@stat.wisc.edu> and Martin Maechler <maechler@stat.math.ethz.ch>
# Maintainer: Martin Maechler <mmaechler+Matrix@gmail.com>
# Contact: Doug and Martin <Matrix-authors@R-project.org>
# Description: Modelling with sparse and dense 'Matrix' matrices, using modular prediction and response module classes.
# Depends: R (>= 3.0.1)
# Imports: stats, methods, Matrix (>= 1.1-5)
# Encoding: UTF-8
# LazyLoad: yes
# License: GPL (>= 2)
# URL: http://Matrix.R-forge.R-project.org/
# NeedsCompilation: no
# Packaged: 2015-08-22 20:32:14 UTC; maechler
# Repository: CRAN
# Date/Publication: 2015-08-22 23:37:45

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
