{% set version = '1.8-0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-zoo
  version: {{ version|replace("-", "_") }}

source:
  fn: zoo_1.8-0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/zoo_1.8-0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/zoo/zoo_1.8-0.tar.gz  # [linux or win32]
  sha256: 09922c46f15de378bd955dfe526e028aef9632a9f79dca1550dc4591faa21357  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/zoo_1.8-0.zip  # [win64]
  sha256: f82463eef288039b035a42bcd64cb987704dfc6d65c0fd6eb2d3cc8d6841b34a  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/zoo_1.8-0.tgz  # [osx]
  sha256: e3d0d58fe8cd9cbdfe9a06a3e725bbd7345bd64ae639ec591865a4ab517dbe0f  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: coda, chron, DAAG, fts, ggplot2, mondate, scales, strucchange, timeDate, timeSeries, tis, tseries, xts
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-lattice >=0.20_27

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-lattice >=0.20_27

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('zoo')"           # [not win]
    - "\"%R%\" -e \"library('zoo')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://zoo.R-Forge.R-project.org/
  license: GPL-2 | GPL-3
  summary: An S3 class with methods for totally ordered indexed observations. It is particularly
    aimed at irregular time series of numeric vectors/matrices and factors. zoo's key
    design goals are independence of a particular index/date/time class and consistency
    with ts and base R by providing methods to extend standard generics.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: zoo
# Version: 1.8-0
# Date: 2017-04-13
# Title: S3 Infrastructure for Regular and Irregular Time Series (Z's Ordered Observations)
# Authors@R: c(person(given = "Achim", family = "Zeileis", role = c("aut", "cre"), email = "Achim.Zeileis@R-project.org"), person(given = "Gabor", family = "Grothendieck", role = "aut", email = "ggrothendieck@gmail.com"), person(given = c("Jeffrey", "A."), family = "Ryan", role = "aut", email = "jeff.a.ryan@gmail.com"), person(given = c("Joshua", "M."), family = "Ulrich", role = "ctb", email = "josh.m.ulrich@gmail.com"), person(given = "Felix", family = "Andrews", role = "ctb", email = "felix@nfrac.org"))
# Description: An S3 class with methods for totally ordered indexed observations. It is particularly aimed at irregular time series of numeric vectors/matrices and factors. zoo's key design goals are independence of a particular index/date/time class and consistency with ts and base R by providing methods to extend standard generics.
# Depends: R (>= 2.10.0), stats
# Suggests: coda, chron, DAAG, fts, ggplot2, mondate, scales, strucchange, timeDate, timeSeries, tis, tseries, xts
# Imports: utils, graphics, grDevices, lattice (>= 0.20-27)
# License: GPL-2 | GPL-3
# URL: http://zoo.R-Forge.R-project.org/
# NeedsCompilation: yes
# Packaged: 2017-04-12 22:23:52 UTC; zeileis
# Author: Achim Zeileis [aut, cre], Gabor Grothendieck [aut], Jeffrey A. Ryan [aut], Joshua M. Ulrich [ctb], Felix Andrews [ctb]
# Maintainer: Achim Zeileis <Achim.Zeileis@R-project.org>
# Repository: CRAN
# Date/Publication: 2017-04-12 23:15:13 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
