{% set version = '1.0.4' %}  # [linux or win32]
{% set version = '1.0.4' %}  # [win64]
{% set version = '1.0.4' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nloptr
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/nloptr_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/nloptr/nloptr_{{ version }}.tar.gz  # [linux or win32]
  sha256: 84225b993cb1ef7854edda9629858662cc8592b0d1344baadea4177486ece1eb  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/nloptr_1.0.4.zip  # [win64]
  sha256: 22540021f7d41586a4b6bc211a3836e4dd60749c001f0688009d006cfc0bf0a1  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/nloptr_1.0.4.tgz  # [osx]
  sha256: cb20b0ea82b63cc4a4e2c5073de09a018ab7e17025ab48ed30f27e4b8d7f4ffc  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 0.8.1)
requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux or osx]
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('nloptr')"           # [not win]
    - "\"%R%\" -e \"library('nloptr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=nloptr
  license: LGPL-3
  summary: ' nloptr is an R interface to NLopt. NLopt is a free/open-source library for nonlinear
    optimization, providing a common interface for a number of different free optimization
    routines available online as well as original implementations of various other algorithms.
    See http://ab-initio.mit.edu/wiki/index.php/NLopt_Introduction for more information
    on the available algorithms. During installation on Unix the NLopt code is downloaded
    and compiled from the NLopt website.'

  license_family: LGPL

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: nloptr
# Type: Package
# Title: R interface to NLopt
# Version: 1.0.4
# Date: 2014-08-02
# Author: Jelmer Ypma <uctpjyy@ucl.ac.uk>, with contributions by Hans W. Borchers <hwborchers@googlemail.com> and  Dirk Eddelbuettel <edd@debian.org>
# Maintainer: Jelmer Ypma <uctpjyy@ucl.ac.uk>
# Description:  nloptr is an R interface to NLopt. NLopt is a free/open-source library for nonlinear optimization, providing a common interface for a number of different free optimization routines available online as well as original implementations of various other algorithms. See http://ab-initio.mit.edu/wiki/index.php/NLopt_Introduction for more information on the available algorithms. During installation on Unix the NLopt code is downloaded and compiled from the NLopt website.
# License: LGPL-3
# Suggests: testthat (>= 0.8.1)
# LazyLoad: yes
# Packaged: 2017-08-22 10:59:12 UTC; ripley
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2017-08-22 13:02:45

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
