{% set version = '1.0.11' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-doparallel
  version: {{ version|replace("-", "_") }}

source:
  fn: doParallel_1.0.11.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/doParallel_1.0.11.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/doParallel/doParallel_1.0.11.tar.gz  # [linux or win32]
  sha256: 4ccbd2eb46d3e4f5251b0c3de4d93d9168b02bb0be493656d6aea236667ff76a  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/doParallel_1.0.11.zip  # [win64]
  sha256: 75aa506a45c0563f415b34b9a751dab4982973d744c3f2227e0dfb7479857483  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/doParallel_1.0.11.tgz  # [osx]
  sha256: b43ffabc2e32cbda89cca4ba1d2514a623b612a27d57bf13d7d68799ed20ff19  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: caret, mlbench, rpart
requirements:
  build:

  host:
    - mro-base
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0

  run:
    - mro-base
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('doParallel')"           # [not win]
    - "\"%R%\" -e \"library('doParallel')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=doParallel
  license: GPL-2
  summary: Provides a parallel backend for the %dopar% function using the parallel package.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: doParallel
# Type: Package
# Title: Foreach Parallel Adaptor for the 'parallel' Package
# Version: 1.0.11
# Authors@R: c(person("Rich", "Calaway", role="cre", email="richcala@microsoft.com"), person("Microsoft", "Corporation", role=c("aut", "cph")), person("Steve", "Weston", role="aut"), person("Dan", "Tenenbaum", role="ctb"))
# Description: Provides a parallel backend for the %dopar% function using the parallel package.
# Depends: R (>= 2.14.0), foreach(>= 1.2.0), iterators(>= 1.0.0), parallel, utils
# Suggests: caret, mlbench, rpart
# Enhances: compiler, RUnit
# License: GPL-2
# Author: Rich Calaway [cre], Microsoft Corporation [aut, cph], Steve Weston [aut], Dan Tenenbaum [ctb]
# Maintainer: Rich Calaway <richcala@microsoft.com>
# Repository: CRAN
# Repository/R-Forge/Project: doparallel
# Repository/R-Forge/Revision: 16
# Repository/R-Forge/DateTimeStamp: 2017-09-18 23:27:23
# Date/Publication: 2017-09-28 16:24:39 UTC
# NeedsCompilation: no
# Packaged: 2017-09-18 23:46:05 UTC; rforge

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
