{% set version = '0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-influencer
  version: {{ version|replace("-", "_") }}

source:
  fn: influenceR_0.1.0.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/influenceR_0.1.0.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/influenceR/influenceR_0.1.0.tar.gz  # [linux or win32]
  sha256: 4fc9324179bd8896875fc0e879a8a96b9ef2a6cf42a296c3b7b4d9098519e98a  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/influenceR_0.1.0.zip  # [win64]
  sha256: 00ea1f1ed1f54c5760396646723311a1aa2ba0c588bc7a11bed90aa2fb02b81c  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/influenceR_0.1.0.tgz  # [osx]
  sha256: 22b3069e8a5f88e46dd27a99e30913ad25a154e284c48d782217b81ec1eed029  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-matrix >=1.1_4
    - r-igraph >=1.0.1

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-matrix >=1.1_4
    - r-igraph >=1.0.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('influenceR')"           # [not win]
    - "\"%R%\" -e \"library('influenceR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rcc-uchicago/influenceR
  license: GPL-2
  summary: Provides functionality to compute various node centrality measures on networks. Included
    are functions to compute betweenness centrality (by utilizing Madduri and Bader's
    SNAP library), implementations of Burt's constraint and effective network size (ENS)
    metrics, Borgatti's algorithm to identify key players, and Valente's bridging metric.
    On Unix systems, the betweenness, Key Players, and bridging implementations are
    parallelized with OpenMP, which may run faster on systems which have OpenMP configured.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: influenceR
# Title: Software Tools to Quantify Structural Importance of Nodes in a Network
# Version: 0.1.0
# Authors@R: c( person("Jacobs", "Simon", email = "sdjacobs@uchicago.edu", role = "aut"), person("Khanna", "Aditya", email = "khanna7@uchicago.edu", role = c("aut", "cre")), person("Madduri", "Kamesh", email = "madduri@cse.psu.edu", role = "ctb"), person("Bader", "David", email = "bader@cc.gatech.edu", role = "ctb"))
# Description: Provides functionality to compute various node centrality measures on networks. Included are functions to compute betweenness centrality (by utilizing Madduri and Bader's SNAP library), implementations of Burt's constraint and effective network size (ENS) metrics, Borgatti's algorithm to identify key players, and Valente's bridging metric. On Unix systems, the betweenness, Key Players, and bridging implementations are parallelized with OpenMP, which may run faster on systems which have OpenMP configured.
# Depends: R (>= 3.2.0)
# License: GPL-2
# LazyData: true
# Imports: igraph (>= 1.0.1), Matrix (>= 1.1-4), methods, utils
# NeedsCompilation: yes
# Suggests: testthat
# URL: https://github.com/rcc-uchicago/influenceR
# Packaged: 2015-09-02 16:20:53 UTC; sdjacobs
# Author: Jacobs Simon [aut], Khanna Aditya [aut, cre], Madduri Kamesh [ctb], Bader David [ctb]
# Maintainer: Khanna Aditya <khanna7@uchicago.edu>
# Repository: CRAN
# Date/Publication: 2015-09-03 12:20:15

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
