{% set version = '1.3-1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rprojroot
  version: {{ version|replace("-", "_") }}

source:
  fn: rprojroot_1.3-1.tar.gz  # [linux or win32 or osx]
  url:  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/rprojroot_1.3-1.tar.gz  # [linux or win32 or osx]
    - {{ cran_mirror }}/src/contrib/Archive/rprojroot/rprojroot_1.3-1.tar.gz  # [linux or win32 or osx]
  sha256: 628c2c064b2b288264ecab6e670f9fd1d380b017a546926019fec301a5c82fca  # [linux or win32 or osx]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/rprojroot_1.3-1.zip  # [win64]
  sha256: f939b417261ddebef467f00bc5b3eb9c940f438fe744174c11b7bc1a805ea7ba  # [win64]



build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, mockr, knitr, withr, rmarkdown
requirements:
  build:

  host:
    - mro-base
    - r-backports

  run:
    - mro-base
    - r-backports

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rprojroot')"           # [not win]
    - "\"%R%\" -e \"library('rprojroot')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/krlmlr/rprojroot, https://krlmlr.github.io/rprojroot
  license: GPL-3
  summary: Robust, reliable and flexible paths to files below a project root. The 'root' of a
    project is defined as a directory that matches a certain criterion, e.g., it contains
    a certain regular file.
  license_family: GPL3

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rprojroot
# Title: Finding Files in Project Subdirectories
# Version: 1.3-1
# Authors@R: person(given = "Kirill", family = "Muller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org")
# Description: Robust, reliable and flexible paths to files below a project root. The 'root' of a project is defined as a directory that matches a certain criterion, e.g., it contains a certain regular file.
# Depends: R (>= 3.0.0)
# Imports: backports
# Suggests: testthat, mockr, knitr, withr, rmarkdown
# VignetteBuilder: knitr
# License: GPL-3
# LazyData: true
# Encoding: UTF-8
# URL: https://github.com/krlmlr/rprojroot, https://krlmlr.github.io/rprojroot
# BugReports: https://github.com/krlmlr/rprojroot/issues
# RoxygenNote: 6.0.1
# Collate: 'rrmake.R' 'criterion.R' 'file.R' 'has-file.R' 'root.R' 'rprojroot-package.R' 'shortcut.R' 'thisfile.R'
# NeedsCompilation: no
# Packaged: 2017-12-18 16:45:58 UTC; muelleki
# Author: Kirill Muller [aut, cre]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2017-12-18 19:09:07 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
