{% set version = '1.0-8' %}  # [linux or win32]
{% set version = '1.0-8' %}  # [win64]
{% set version = '1.0-8' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mvtnorm
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/mvtnorm_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/mvtnorm/mvtnorm_{{ version }}.tar.gz  # [linux or win32]
  sha256: 2010cab50fb7a5117e3c61f06e4a797ea6bf92b1ab20c132cb929d453d154451  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/mvtnorm_1.0-8.zip  # [win64]
  sha256: e30704cdbe67e24134d154bccfd955951ed7be600b3c006748e08f8a69672abc  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/mvtnorm_1.0-8.tgz  # [osx]
  sha256: 2c6645f4914414164e8d99d2fd9549622f757403752f92fc4329868094f95da2  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - {{native}}toolchain        # [win32]
    - {{posix}}filesystem        # [win32]
    - {{posix}}make              # [linux or win32]
    - {{posix}}sed               # [win32]
    - {{posix}}coreutils         # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs         # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mvtnorm')"           # [not win]
    - "\"%R%\" -e \"library('mvtnorm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://mvtnorm.R-forge.R-project.org
  license: GPL-2
  summary: Computes multivariate normal and t probabilities, quantiles, random deviates and densities.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mvtnorm
# Title: Multivariate Normal and t Distributions
# Version: 1.0-8
# Date: 2018-05-31
# Authors@R: c(person("Alan", "Genz", role = "aut"), person("Frank", "Bretz", role = "aut"), person("Tetsuhisa", "Miwa", role = "aut"), person("Xuefei", "Mi", role = "aut"), person("Friedrich", "Leisch", role = "ctb"), person("Fabian", "Scheipl", role = "ctb"), person("Bjoern", "Bornkamp", role = "ctb"), person("Martin", "Maechler", role = "ctb"), person("Torsten", "Hothorn", role = c("aut", "cre"), email = "Torsten.Hothorn@R-project.org", comment = c(ORCID = "0000-0001-8301-0471")))
# Description: Computes multivariate normal and t probabilities, quantiles, random deviates and densities.
# Imports: stats, methods
# Depends: R(>= 1.9.0)
# License: GPL-2
# URL: http://mvtnorm.R-forge.R-project.org
# NeedsCompilation: yes
# Packaged: 2018-05-31 08:37:50 UTC; hothorn
# Author: Alan Genz [aut], Frank Bretz [aut], Tetsuhisa Miwa [aut], Xuefei Mi [aut], Friedrich Leisch [ctb], Fabian Scheipl [ctb], Bjoern Bornkamp [ctb], Martin Maechler [ctb], Torsten Hothorn [aut, cre] (<https://orcid.org/0000-0001-8301-0471>)
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-05-31 20:38:18 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
