{% set version = '1.0-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mvtnorm
  version: {{ version|replace("-", "_") }}

source:
  fn: mvtnorm_1.0-6.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/mvtnorm_1.0-6.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/mvtnorm/mvtnorm_1.0-6.tar.gz  # [linux or win32]
  sha256: 4a015b57b645b520151b213eb04b7331598c06442a3f652c7dc149425bd2e444  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/mvtnorm_1.0-6.zip  # [win64]
  sha256: 1ae020e6f487f99d95d84aa571152048715e53d256fddacbbfb9725e59d151cb  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/mvtnorm_1.0-6.tgz  # [osx]
  sha256: dab4397eaa4225603eab3d2b775d8f98dc0b9dc8e8ec34a5dae80bf694ad98bb  # [osx]


build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{ compiler('fortran') }}    # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mvtnorm')"           # [not win]
    - "\"%R%\" -e \"library('mvtnorm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://mvtnorm.R-forge.R-project.org
  license: GPL-2
  summary: Computes multivariate normal and t probabilities, quantiles, random deviates and densities.
  license_family: GPL2

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: mvtnorm
# Title: Multivariate Normal and t Distributions
# Version: 1.0-6
# Date: 2017-03-01
# Authors@R: c(person("Alan", "Genz", role = "aut"), person("Frank", "Bretz", role = "aut"), person("Tetsuhisa", "Miwa", role = "aut"), person("Xuefei", "Mi", role = "aut"), person("Friedrich", "Leisch", role = "ctb"), person("Fabian", "Scheipl", role = "ctb"), person("Bjoern", "Bornkamp", role = "ctb"), person("Martin", "Maechler", role = "ctb"), person("Torsten", "Hothorn", role = c("aut", "cre"), email = "Torsten.Hothorn@R-project.org"))
# Description: Computes multivariate normal and t probabilities, quantiles, random deviates and densities.
# Imports: stats, methods
# Depends: R(>= 1.9.0)
# License: GPL-2
# URL: http://mvtnorm.R-forge.R-project.org
# NeedsCompilation: yes
# Packaged: 2017-03-02 13:15:25 UTC; hothorn
# Author: Alan Genz [aut], Frank Bretz [aut], Tetsuhisa Miwa [aut], Xuefei Mi [aut], Friedrich Leisch [ctb], Fabian Scheipl [ctb], Bjoern Bornkamp [ctb], Martin Maechler [ctb], Torsten Hothorn [aut, cre]
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2017-03-02 16:14:20

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
