{% set version = '1.4-2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-microbenchmark
  version: {{ version|replace("-", "_") }}

source:
  fn: microbenchmark_1.4-2.1.tar.gz  # [linux or win32]
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/microbenchmark_1.4-2.1.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/microbenchmark/microbenchmark_1.4-2.1.tar.gz  # [linux or win32]
  sha256: 6feb06819b6a57346f24d7fc3f588ff60a236b5b170aa62383af456c54c8c562  # [linux or win32]




  url:  {{ cran_mirror }}/bin/windows/contrib/3.4/microbenchmark_1.4-2.1.zip  # [win64]
  sha256: 29d2681568661ef5e5804e9c058583d59001a8cd98d04b47086dff76cba29b2e  # [win64]

  url:  {{ cran_mirror }}/bin/macosx/el-capitan/contrib/3.4/microbenchmark_1.4-2.1.tgz  # [osx]
  sha256: 5ed3632de980025b0742e5bdaf3d262588db30772bf149f973e86afe48b1e8e4  # [osx]


build:
  merge_build_host: True  # [linux or win32]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: multcomp
requirements:
  build:
    - {{ compiler('c') }}          # [linux]
    - {{native}}toolchain          # [win32]
    - {{posix}}filesystem          # [win32]
    - {{posix}}make                # [linux or win32]

  host:
    - mro-base
    - r-ggplot2

  run:
    - mro-base
    - {{native}}gcc-libs           # [win32]
    - r-ggplot2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('microbenchmark')"           # [not win]
    - "\"%R%\" -e \"library('microbenchmark')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=microbenchmark
  license: BSD_2_clause + file LICENSE
  summary: Provides infrastructure to accurately measure and compare the execution time of R
    expressions.
  license_family: BSD

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: microbenchmark
# Title: Accurate Timing Functions
# Description: Provides infrastructure to accurately measure and compare the execution time of R expressions.
# Authors@R: c( person("Olaf", "Mersmann", role=c("aut", "cre"), email="olafm@p-value.net"), person("Claudia", "Beleites", role=c("ctb")), person("Rainer", "Hurling", role=c("ctb")), person("Ari", "Friedman", role=c("ctb")))
# License: BSD_2_clause + file LICENSE
# Imports: graphics, ggplot2, stats
# Suggests: multcomp
# ByteCompile: yes
# LazyData: yes
# Version: 1.4-2.1
# SystemRequirements: GNU Make
# NeedsCompilation: yes
# Packaged: 2015-11-25 10:59:00 UTC; ligges
# Author: Olaf Mersmann [aut, cre], Claudia Beleites [ctb], Rainer Hurling [ctb], Ari Friedman [ctb]
# Maintainer: Olaf Mersmann <olafm@p-value.net>
# Repository: CRAN
# Date/Publication: 2015-11-25 12:02:00

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
