{% set version = '1.0.10' %}  # [linux or win32]
{% set version = '1.0.10' %}  # [win64]
{% set version = '1.0.10' %}  # [osx]

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-iterators
  version: {{ version|replace("-", "_") }}

source:
  url:  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/iterators_{{ version }}.tar.gz  # [linux or win32]
    - {{ cran_mirror }}/src/contrib/Archive/iterators/iterators_{{ version }}.tar.gz  # [linux or win32]
  sha256: a9e1b2302828d4527766ce12fa9ae06faf8d51e819a43f8efef632b6ddf471e8  # [linux or win32]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/iterators_1.0.10.zip  # [win64]
  sha256: 6a24f3b96583f634e270d0a77e307714fc1f924e107a77504876a96c024ab5ff  # [win64]

  url: https://cran.microsoft.com/snapshot/2018-08-01/bin/macosx/el-capitan/contrib/3.5/iterators_1.0.10.tgz  # [osx]
  sha256: 1c53b6dd18833a0b1c2c0c2ddcfa02e0bf05ed0c5c62b268b13260641cb51f24  # [osx]

build:
  merge_build_host: True  # [win32]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit, foreach
requirements:
  build:
    - rtools                     # [win32]
    - {{posix}}zip               # [win32]

  host:
    - mro-base

  run:
    - mro-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('iterators')"           # [not win]
    - "\"%R%\" -e \"library('iterators')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=iterators
  license: Apache License (== 2.0)
  summary: Support for iterators, which allow a programmer to traverse through all the elements
    of a vector, list, or other collection of data.
  license_family: APACHE

extra:
  recipe-maintainers:
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: iterators
# Type: Package
# Title: Provides Iterator Construct for R
# Version: 1.0.10
# Authors@R: c(person("Rich", "Calaway", role="cre", email="richcala@microsoft.com"), person("Revolution", "Analytics", role=c("aut", "cph")), person("Steve", "Weston", role="aut"))
# Description: Support for iterators, which allow a programmer to traverse through all the elements of a vector, list, or other collection of data.
# Depends: R (>= 2.5.0), utils
# Suggests: RUnit, foreach
# License: Apache License (== 2.0)
# Author: Rich Calaway [cre], Revolution Analytics [aut, cph], Steve Weston [aut]
# Maintainer: Rich Calaway <richcala@microsoft.com>
# Repository: CRAN
# Repository/R-Forge/Project: foreach
# Repository/R-Forge/Revision: 34
# Repository/R-Forge/DateTimeStamp: 2018-05-24 17:41:04
# Date/Publication: 2018-07-13 15:20:03 UTC
# NeedsCompilation: no
# Packaged: 2018-05-24 17:55:14 UTC; rforge

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
